#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

# Navigate to your frontend directory
cd frontend2

# Running lint-staged for linting and formatting
npx lint-staged --allow-empty

# Run a subset of unit tests
npm run test:quick
