# Auto-curated non-production user seed subsets for anonymizer flow.
# Source: filtered from existing env seed data by explicit business rules.

from typing import Any

NONPROD_USER_SEED_DATA: dict[str, dict[str, list[dict[str, Any]]]] = {
    "local": {
        "profiles": [
            {
                "email": "lindsy.grunert@gov.bc.ca",
                "first_name": "Lindsy",
                "is_active": True,
                "keycloak_email": "lindsy.grunert@gov.bc.ca",
                "keycloak_username": "LGRUNERT",
                "last_name": "Grunert",
                "mobile_phone": "1234567890",
                "organization_id": None,
                "phone": "1234567890",
                "title": "Admin",
                "user_profile_id": 6,
            },
            {
                "email": "tfrs@gov.bc.ca",
                "first_name": "Jane",
                "is_active": True,
                "keycloak_email": "tfrs@gov.bc.ca",
                "keycloak_username": "lcfs1",
                "last_name": "Doe",
                "mobile_phone": "1112223333",
                "organization_id": 1,
                "phone": "1112223333",
                "title": "Analyst",
                "user_profile_id": 7,
            },
            {
                "email": "tfrs@gov.bc.ca",
                "first_name": "John",
                "is_active": True,
                "keycloak_email": "tfrs@gov.bc.ca",
                "keycloak_username": "LCFS2",
                "last_name": "Smith",
                "mobile_phone": "2223334444",
                "organization_id": 2,
                "phone": "2223334444",
                "title": "Analyst",
                "user_profile_id": 8,
            },
            {
                "email": "tfrs@gov.bc.ca",
                "first_name": "Alice",
                "is_active": True,
                "keycloak_email": "tfrs@gov.bc.ca",
                "keycloak_username": "LCFS3",
                "last_name": "Woo",
                "mobile_phone": "3334445555",
                "organization_id": 3,
                "phone": "3334445555",
                "title": "Analyst",
                "user_profile_id": 9,
            },
            {
                "email": "tfrs@gov.bc.ca",
                "first_name": "Bob",
                "is_active": True,
                "keycloak_email": "tfrs@gov.bc.ca",
                "keycloak_username": "LCFS4",
                "last_name": "Lee",
                "mobile_phone": "4445556666",
                "organization_id": 4,
                "phone": "4445556666",
                "title": "Analyst",
                "user_profile_id": 10,
            },
            {
                "email": "tfrs@gov.bc.ca",
                "first_name": "David",
                "is_active": True,
                "keycloak_email": "tfrs@gov.bc.ca",
                "keycloak_username": "LCFS5",
                "last_name": "Clark",
                "mobile_phone": "6667778888",
                "organization_id": 5,
                "phone": "6667778888",
                "title": "Analyst",
                "user_profile_id": 11,
            },
            {
                "email": "tfrs@gov.bc.ca",
                "first_name": "Frank",
                "is_active": True,
                "keycloak_email": "tfrs@gov.bc.ca",
                "keycloak_username": "LCFS6",
                "last_name": "Wilson",
                "mobile_phone": "8889990000",
                "organization_id": 6,
                "phone": "8889990000",
                "title": "Analyst",
                "user_profile_id": 12,
            },
            {
                "email": "tfrs@gov.bc.ca",
                "first_name": "Bill",
                "is_active": True,
                "keycloak_email": "tfrs@gov.bc.ca",
                "keycloak_username": "LCFS7",
                "last_name": "Teller",
                "mobile_phone": "0001112222",
                "organization_id": 7,
                "phone": "0001112222",
                "title": "Analyst",
                "user_profile_id": 13,
            },
            {
                "email": "tfrs@gov.bc.ca",
                "first_name": "James",
                "is_active": True,
                "keycloak_email": "tfrs@gov.bc.ca",
                "keycloak_username": "LCFS8",
                "last_name": "Bell",
                "mobile_phone": "2223334445",
                "organization_id": 8,
                "phone": "2223334445",
                "title": "Analyst",
                "user_profile_id": 14,
            },
            {
                "email": "tfrs@gov.bc.ca",
                "first_name": "Leo",
                "is_active": True,
                "keycloak_email": "tfrs@gov.bc.ca",
                "keycloak_username": "LCFS9",
                "last_name": "Martin",
                "mobile_phone": "4445556667",
                "organization_id": 9,
                "phone": "4445556667",
                "title": "Analyst",
                "user_profile_id": 15,
            },
            {
                "email": "tfrs@gov.bc.ca",
                "first_name": "Noah",
                "is_active": True,
                "keycloak_email": "tfrs@gov.bc.ca",
                "keycloak_username": "LCFS10",
                "last_name": "Thomas",
                "mobile_phone": "6667778889",
                "organization_id": 10,
                "phone": "6667778889",
                "title": "Analyst",
                "user_profile_id": 16,
            },
            {
                "email": "alasdair.ring@gov.bc.ca",
                "first_name": "Al",
                "is_active": True,
                "keycloak_email": "alasdair.ring@gov.bc.ca",
                "keycloak_username": "AIRING",
                "last_name": "Ring",
                "mobile_phone": "1234567890",
                "organization_id": None,
                "phone": "1234567890",
                "title": "Product Owner",
                "user_profile_id": 18,
            },
            {
                "email": "alex.zorkin@gov.bc.ca",
                "first_name": "Alex",
                "is_active": True,
                "keycloak_email": "alex.zorkin@gov.bc.ca",
                "keycloak_username": "ALZORKIN",
                "last_name": "Zorkin",
                "mobile_phone": "1234567890",
                "organization_id": None,
                "phone": "1234567890",
                "title": "Developer",
                "user_profile_id": 22,
            },
        ],
        "roles": [
            {"role_id": 1, "user_profile_id": 6},
            {"role_id": 3, "user_profile_id": 6},
            {"role_id": 2, "user_profile_id": 7},
            {"role_id": 8, "user_profile_id": 7},
            {"role_id": 9, "user_profile_id": 7},
            {"role_id": 10, "user_profile_id": 7},
            {"role_id": 2, "user_profile_id": 8},
            {"role_id": 8, "user_profile_id": 8},
            {"role_id": 10, "user_profile_id": 8},
            {"role_id": 2, "user_profile_id": 9},
            {"role_id": 8, "user_profile_id": 9},
            {"role_id": 9, "user_profile_id": 9},
            {"role_id": 10, "user_profile_id": 9},
            {"role_id": 2, "user_profile_id": 10},
            {"role_id": 8, "user_profile_id": 10},
            {"role_id": 10, "user_profile_id": 10},
            {"role_id": 2, "user_profile_id": 11},
            {"role_id": 8, "user_profile_id": 11},
            {"role_id": 10, "user_profile_id": 11},
            {"role_id": 2, "user_profile_id": 12},
            {"role_id": 2, "user_profile_id": 13},
            {"role_id": 2, "user_profile_id": 14},
            {"role_id": 2, "user_profile_id": 15},
            {"role_id": 2, "user_profile_id": 16},
            {"role_id": 1, "user_profile_id": 18},
            {"role_id": 3, "user_profile_id": 18},
            {"role_id": 1, "user_profile_id": 22},
            {"role_id": 3, "user_profile_id": 22},
        ],
    },
    "test": {
        "profiles": [
            {
                "email": "lindsy.grunert@gov.bc.ca",
                "first_name": "Lindsy",
                "is_active": True,
                "keycloak_email": "lindsy.grunert@gov.bc.ca",
                "keycloak_username": "LGRUNERT",
                "last_name": "Grunert",
                "mobile_phone": "1234567890",
                "organization_id": None,
                "phone": "1234567890",
                "title": "Admin",
                "user_profile_id": 6,
            },
            {
                "email": "tfrs@gov.bc.ca",
                "first_name": "Jane",
                "is_active": True,
                "keycloak_email": "tfrs@gov.bc.ca",
                "keycloak_username": "tfs1",
                "last_name": "Doe",
                "mobile_phone": "1112223333",
                "organization_id": 1,
                "phone": "(604) 567-8976",
                "title": "Supplier - Liquid",
                "user_profile_id": 7,
            },
            {
                "email": "tfrs@gov.bc.ca",
                "first_name": "John",
                "is_active": True,
                "keycloak_email": "tfrs@gov.bc.ca",
                "keycloak_username": "tfs2",
                "last_name": "Smith",
                "mobile_phone": "2223334444",
                "organization_id": 2,
                "phone": "(778) 896-1198",
                "title": "Allocator Rep - Fleet",
                "user_profile_id": 8,
            },
            {
                "email": "tfrs@gov.bc.ca",
                "first_name": "Alice",
                "is_active": True,
                "keycloak_email": "tfrs@gov.bc.ca",
                "keycloak_username": "tfs3",
                "last_name": "Woo",
                "mobile_phone": "3334445555",
                "organization_id": 3,
                "phone": "(250) 765-9901",
                "title": "Supplier - Biofuel",
                "user_profile_id": 9,
            },
            {
                "email": "tfrs@gov.bc.ca",
                "first_name": "Bob",
                "is_active": True,
                "keycloak_email": "tfrs@gov.bc.ca",
                "keycloak_username": "tfs4",
                "last_name": "Lee",
                "mobile_phone": "4445556666",
                "organization_id": 4,
                "phone": "(250) 555-1122",
                "title": "Supplier - Electricity, Liquid Fuel, Exporter",
                "user_profile_id": 10,
            },
            {
                "email": "tfrs@gov.bc.ca",
                "first_name": "David",
                "is_active": True,
                "keycloak_email": "tfrs@gov.bc.ca",
                "keycloak_username": "tfs5",
                "last_name": "Clark",
                "mobile_phone": "6667778888",
                "organization_id": 5,
                "phone": "6667778888",
                "title": "Analyst",
                "user_profile_id": 11,
            },
            {
                "email": "tfrs@gov.bc.ca",
                "first_name": "Frank",
                "is_active": True,
                "keycloak_email": "tfrs@gov.bc.ca",
                "keycloak_username": "tfs6",
                "last_name": "Wilson",
                "mobile_phone": "8889990000",
                "organization_id": 6,
                "phone": "8889990000",
                "title": "Analyst",
                "user_profile_id": 12,
            },
            {
                "email": "tfrs@gov.bc.ca",
                "first_name": "Bill",
                "is_active": True,
                "keycloak_email": "tfrs@gov.bc.ca",
                "keycloak_username": "tfs7",
                "last_name": "Teller",
                "mobile_phone": "0001112222",
                "organization_id": 7,
                "phone": "0001112222",
                "title": "Analyst",
                "user_profile_id": 13,
            },
            {
                "email": "tfrs@gov.bc.ca",
                "first_name": "James",
                "is_active": True,
                "keycloak_email": "tfrs@gov.bc.ca",
                "keycloak_username": "tfs8",
                "last_name": "Bell",
                "mobile_phone": "2223334445",
                "organization_id": 8,
                "phone": "2223334445",
                "title": "Analyst",
                "user_profile_id": 14,
            },
            {
                "email": "tfrs@gov.bc.ca",
                "first_name": "Leo",
                "is_active": True,
                "keycloak_email": "tfrs@gov.bc.ca",
                "keycloak_username": "tfs9",
                "last_name": "Martin",
                "mobile_phone": "4445556667",
                "organization_id": 9,
                "phone": "4445556667",
                "title": "Analyst",
                "user_profile_id": 15,
            },
            {
                "email": "tfrs@gov.bc.ca",
                "first_name": "Noah",
                "is_active": True,
                "keycloak_email": "tfrs@gov.bc.ca",
                "keycloak_username": "tfs10",
                "last_name": "Thomas",
                "mobile_phone": "6667778889",
                "organization_id": 10,
                "phone": "6667778889",
                "title": "Analyst",
                "user_profile_id": 16,
            },
            {
                "email": "alasdair.ring@gov.bc.ca",
                "first_name": "Al",
                "is_active": True,
                "keycloak_email": "alasdair.ring@gov.bc.ca",
                "keycloak_username": "AIRING",
                "last_name": "Ring",
                "mobile_phone": "1234567890",
                "organization_id": None,
                "phone": "1234567890",
                "title": "Product Owner",
                "user_profile_id": 18,
            },
            {
                "email": "alex.zorkin@gov.bc.ca",
                "first_name": "Alex",
                "is_active": True,
                "keycloak_email": "alex.zorkin@gov.bc.ca",
                "keycloak_username": "ALZORKIN",
                "last_name": "Zorkin",
                "mobile_phone": "1234567890",
                "organization_id": None,
                "phone": "1234567890",
                "title": "Lead Developer",
                "user_profile_id": 55,
            },
        ],
        "roles": [
            {"role_id": 1, "user_profile_id": 6},
            {"role_id": 3, "user_profile_id": 6},
            {"role_id": 4, "user_profile_id": 6},
            {"role_id": 2, "user_profile_id": 7},
            {"role_id": 7, "user_profile_id": 7},
            {"role_id": 8, "user_profile_id": 7},
            {"role_id": 9, "user_profile_id": 7},
            {"role_id": 10, "user_profile_id": 7},
            {"role_id": 2, "user_profile_id": 8},
            {"role_id": 7, "user_profile_id": 8},
            {"role_id": 8, "user_profile_id": 8},
            {"role_id": 9, "user_profile_id": 8},
            {"role_id": 10, "user_profile_id": 8},
            {"role_id": 2, "user_profile_id": 9},
            {"role_id": 7, "user_profile_id": 9},
            {"role_id": 8, "user_profile_id": 9},
            {"role_id": 9, "user_profile_id": 9},
            {"role_id": 10, "user_profile_id": 9},
            {"role_id": 2, "user_profile_id": 10},
            {"role_id": 7, "user_profile_id": 10},
            {"role_id": 8, "user_profile_id": 10},
            {"role_id": 9, "user_profile_id": 10},
            {"role_id": 10, "user_profile_id": 10},
            {"role_id": 2, "user_profile_id": 11},
            {"role_id": 7, "user_profile_id": 11},
            {"role_id": 8, "user_profile_id": 11},
            {"role_id": 9, "user_profile_id": 11},
            {"role_id": 10, "user_profile_id": 11},
            {"role_id": 2, "user_profile_id": 12},
            {"role_id": 7, "user_profile_id": 12},
            {"role_id": 8, "user_profile_id": 12},
            {"role_id": 9, "user_profile_id": 12},
            {"role_id": 10, "user_profile_id": 12},
            {"role_id": 2, "user_profile_id": 13},
            {"role_id": 7, "user_profile_id": 13},
            {"role_id": 8, "user_profile_id": 13},
            {"role_id": 9, "user_profile_id": 13},
            {"role_id": 10, "user_profile_id": 13},
            {"role_id": 2, "user_profile_id": 14},
            {"role_id": 7, "user_profile_id": 14},
            {"role_id": 8, "user_profile_id": 14},
            {"role_id": 9, "user_profile_id": 14},
            {"role_id": 10, "user_profile_id": 14},
            {"role_id": 2, "user_profile_id": 15},
            {"role_id": 7, "user_profile_id": 15},
            {"role_id": 8, "user_profile_id": 15},
            {"role_id": 9, "user_profile_id": 15},
            {"role_id": 10, "user_profile_id": 15},
            {"role_id": 2, "user_profile_id": 16},
            {"role_id": 7, "user_profile_id": 16},
            {"role_id": 8, "user_profile_id": 16},
            {"role_id": 9, "user_profile_id": 16},
            {"role_id": 10, "user_profile_id": 16},
            {"role_id": 1, "user_profile_id": 18},
            {"role_id": 3, "user_profile_id": 18},
            {"role_id": 4, "user_profile_id": 18},
            {"role_id": 1, "user_profile_id": 55},
            {"role_id": 3, "user_profile_id": 55},
        ],
    },
}
