# Use the official node image as the base image
FROM node:20

# Set the working directory
WORKDIR /app

# Copy package files and install dependencies
COPY package.json ./
COPY package-lock.json ./
RUN npm install

# Copy other source files - node modules is excluded in .dockerignore
COPY . .

# Expose port 3000 for the app
EXPOSE 3000

CMD [ "npm" , "run" , "dev" ]
