# Use the official node image as the base image
FROM node:20

# Set the working directory
WORKDIR /app

# Copy package files and install dependencies
COPY package*.json ./
RUN npm install
RUN npm install -g concurrently

# Copy other source files
COPY . .

# Expose port 3000 for the app
EXPOSE 3000

CMD ["sh", "-c", "npm run openapi:generate && concurrently \"npm run openapi:watch\" \"npm run dev --force\""]