-- Create Transfer Summary View
CREATE OR REPLACE VIEW public.vw_allocation_agreement_base AS
SELECT
      "source"."group_uuid" AS "group_uuid",
      "source"."max" AS "max",
      CASE
        WHEN "Allocation Agreement - Group UUID"."allocation_transaction_type_id" = 1 THEN 'Allocated From'
        WHEN "Allocation Agreement - Group UUID"."allocation_transaction_type_id" = 2 THEN 'Allocation To'
      END AS "Allocation transaction type",
      "Allocation Agreement - Group UUID"."allocation_agreement_id" AS "Allocation Agreement - Group UUID__allocation_agreement_id",
      "Allocation Agreement - Group UUID"."transaction_partner" AS "Allocation Agreement - Group UUID__transaction_partner",
      "Allocation Agreement - Group UUID"."postal_address" AS "Allocation Agreement - Group UUID__postal_address",
      "Allocation Agreement - Group UUID"."transaction_partner_email" AS "Allocation Agreement - Group UUID__transaction_partner_email",
      "Allocation Agreement - Group UUID"."transaction_partner_phone" AS "Allocation Agreement - Group UUID__transaction_partner_phone",
      "Allocation Agreement - Group UUID"."ci_of_fuel" AS "Allocation Agreement - Group UUID__ci_of_fuel",
      "Allocation Agreement - Group UUID"."quantity" AS "Allocation Agreement - Group UUID__quantity",
      "Allocation Agreement - Group UUID"."units" AS "Allocation Agreement - Group UUID__units",
      "Allocation Agreement - Group UUID"."fuel_type_other" AS "Allocation Agreement - Group UUID__fuel_type_other",
      "Allocation Agreement - Group UUID"."allocation_transaction_type_id" AS "Allocation Agreement - Group UUID__allocation_trans_ad55ef48",
      "Allocation Agreement - Group UUID"."fuel_type_id" AS "Allocation Agreement - Group UUID__fuel_type_id",
      "Allocation Agreement - Group UUID"."fuel_category_id" AS "Allocation Agreement - Group UUID__fuel_category_id",
      "Allocation Agreement - Group UUID"."provision_of_the_act_id" AS "Allocation Agreement - Group UUID__provision_of_the_act_id",
      "Allocation Agreement - Group UUID"."fuel_code_id" AS "Allocation Agreement - Group UUID__fuel_code_id",
      "Allocation Agreement - Group UUID"."compliance_report_id" AS "Allocation Agreement - Group UUID__compliance_report_id",
      "Allocation Agreement - Group UUID"."create_date" AS "Allocation Agreement - Group UUID__create_date",
      "Allocation Agreement - Group UUID"."update_date" AS "Allocation Agreement - Group UUID__update_date",
      "Allocation Agreement - Group UUID"."create_user" AS "Allocation Agreement - Group UUID__create_user",
      "Allocation Agreement - Group UUID"."update_user" AS "Allocation Agreement - Group UUID__update_user",
      "Allocation Agreement - Group UUID"."display_order" AS "Allocation Agreement - Group UUID__display_order",
      "Allocation Agreement - Group UUID"."group_uuid" AS "Allocation Agreement - Group UUID__group_uuid",
      "Allocation Agreement - Group UUID"."version" AS "Allocation Agreement - Group UUID__version",
      "Allocation Agreement - Group UUID"."action_type" AS "Allocation Agreement - Group UUID__action_type",
      "Allocation Agreement - Group UUID"."quantity_not_sold" AS "Allocation Agreement - Group UUID__quantity_not_sold",
      "Compliance Report Base - Compliance Report"."compliance_report_id" AS "Compliance Report Base - Compliance Report__complia_6afb9aaa",
      "Compliance Report Base - Compliance Report"."compliance_period_id" AS "Compliance Report Base - Compliance Report__complia_cda244b4",
      "Compliance Report Base - Compliance Report"."organization_id" AS "Compliance Report Base - Compliance Report__organization_id",
      "Compliance Report Base - Compliance Report"."current_status_id" AS "Compliance Report Base - Compliance Report__current_4315b3a2",
      "Compliance Report Base - Compliance Report"."transaction_id" AS "Compliance Report Base - Compliance Report__transaction_id",
      "Compliance Report Base - Compliance Report"."compliance_report_group_uuid" AS "Compliance Report Base - Compliance Report__complia_8e1217db",
      "Compliance Report Base - Compliance Report"."legacy_id" AS "Compliance Report Base - Compliance Report__legacy_id",
      "Compliance Report Base - Compliance Report"."version" AS "Compliance Report Base - Compliance Report__version",
      "Compliance Report Base - Compliance Report"."supplemental_initiator" AS "Compliance Report Base - Compliance Report__supplem_3e383c17",
      "Compliance Report Base - Compliance Report"."reporting_frequency" AS "Compliance Report Base - Compliance Report__reporti_c3204642",
      "Compliance Report Base - Compliance Report"."nickname" AS "Compliance Report Base - Compliance Report__nickname",
      "Compliance Report Base - Compliance Report"."supplemental_note" AS "Compliance Report Base - Compliance Report__supplem_76c93d97",
      "Compliance Report Base - Compliance Report"."create_date" AS "Compliance Report Base - Compliance Report__create_date",
      "Compliance Report Base - Compliance Report"."update_date" AS "Compliance Report Base - Compliance Report__update_date",
      "Compliance Report Base - Compliance Report"."create_user" AS "Compliance Report Base - Compliance Report__create_user",
      "Compliance Report Base - Compliance Report"."update_user" AS "Compliance Report Base - Compliance Report__update_user",
      "Compliance Report Base - Compliance Report"."assessment_statement" AS "Compliance Report Base - Compliance Report__assessm_7b8d860b",
      "Compliance Report Base - Compliance Report"."Renewable Requirements" AS "Compliance Report Base - Compliance Report__Renewab_f11c34b5",
      "Compliance Report Base - Compliance Report"."Low Carbon Requirements" AS "Compliance Report Base - Compliance Report__Low Car_035b150f",
      "Compliance Report Base - Compliance Report"."Compliance Period__compliance_period_id" AS "Compliance Report Base - Compliance Report__Complia_dd118a33",
      "Compliance Report Base - Compliance Report"."Compliance Period__description" AS "Compliance Report Base - Compliance Report__Complia_cb30ad19",
      "Compliance Report Base - Compliance Report"."Compliance Period__display_order" AS "Compliance Report Base - Compliance Report__Complia_721c9a5e",
      "Compliance Report Base - Compliance Report"."Compliance Period__create_date" AS "Compliance Report Base - Compliance Report__Complia_8deb472c",
      "Compliance Report Base - Compliance Report"."Compliance Period__update_date" AS "Compliance Report Base - Compliance Report__Complia_d8268dda",
      "Compliance Report Base - Compliance Report"."Compliance Period__effective_date" AS "Compliance Report Base - Compliance Report__Complia_6a450a4b",
      "Compliance Report Base - Compliance Report"."Compliance Period__effective_status" AS "Compliance Report Base - Compliance Report__Complia_e535ee64",
      "Compliance Report Base - Compliance Report"."Compliance Period__expiration_date" AS "Compliance Report Base - Compliance Report__Complia_27d99d4c",
      "Compliance Report Base - Compliance Report"."Compliance Report Status - Current Status__complian_8aca39b7" AS "Compliance Report Base - Compliance Report__Complia_35a08ff4",
      "Compliance Report Base - Compliance Report"."Compliance Report Status - Current Status__display_order" AS "Compliance Report Base - Compliance Report__Complia_617d3c08",
      "Compliance Report Base - Compliance Report"."Compliance Report Status - Current Status__status" AS "Compliance Report Base - Compliance Report__Complia_f6d97a34",
      "Compliance Report Base - Compliance Report"."Compliance Report Status - Current Status__create_date" AS "Compliance Report Base - Compliance Report__Complia_de8161a6",
      "Compliance Report Base - Compliance Report"."Compliance Report Status - Current Status__update_date" AS "Compliance Report Base - Compliance Report__Complia_8b4cab50",
      "Compliance Report Base - Compliance Report"."Compliance Report Status - Current Status__effective_date" AS "Compliance Report Base - Compliance Report__Complia_e85e9f2c",
      "Compliance Report Base - Compliance Report"."Compliance Report Status - Current Status__effective_status" AS "Compliance Report Base - Compliance Report__Complia_4fecf6d4",
      "Compliance Report Base - Compliance Report"."Compliance Report Status - Current Status__expiration_date" AS "Compliance Report Base - Compliance Report__Complia_f48d7222",
      "Compliance Report Base - Compliance Report"."Compliance Report Summary - Compliance Report__summary_id" AS "Compliance Report Base - Compliance Report__Complia_fe5bffa9",
      "Compliance Report Base - Compliance Report"."Compliance Report Summary - Compliance Report__comp_1db2e1e9" AS "Compliance Report Base - Compliance Report__Complia_ac5855d3",
      "Compliance Report Base - Compliance Report"."Compliance Report Summary - Compliance Report__quarter" AS "Compliance Report Base - Compliance Report__Complia_716d2691",
      "Compliance Report Base - Compliance Report"."Compliance Report Summary - Compliance Report__is_locked" AS "Compliance Report Base - Compliance Report__Complia_9880522d",
      "Compliance Report Base - Compliance Report"."Compliance Report Summary - Compliance Report__line_2c0818fb" AS "Compliance Report Base - Compliance Report__Complia_e084f95e",
      "Compliance Report Base - Compliance Report"."Compliance Report Summary - Compliance Report__line_2ff66c5b" AS "Compliance Report Base - Compliance Report__Complia_bbf3740d",
      "Compliance Report Base - Compliance Report"."Compliance Report Summary - Compliance Report__line_1fcf7a18" AS "Compliance Report Base - Compliance Report__Complia_0948e373",
      "Compliance Report Base - Compliance Report"."Compliance Report Summary - Compliance Report__line_d70f8aef" AS "Compliance Report Base - Compliance Report__Complia_1151727e",
      "Compliance Report Base - Compliance Report"."Compliance Report Summary - Compliance Report__line_2773c83c" AS "Compliance Report Base - Compliance Report__Complia_8c046bfd",
      "Compliance Report Base - Compliance Report"."Compliance Report Summary - Compliance Report__line_e4c8e80c" AS "Compliance Report Base - Compliance Report__Complia_0c86fc50",
      "Compliance Report Base - Compliance Report"."Compliance Report Summary - Compliance Report__line_9cec896d" AS "Compliance Report Base - Compliance Report__Complia_817c5f4a",
      "Compliance Report Base - Compliance Report"."Compliance Report Summary - Compliance Report__line_489bea32" AS "Compliance Report Base - Compliance Report__Complia_d930be19",
      "Compliance Report Base - Compliance Report"."Compliance Report Summary - Compliance Report__line_af2beb8e" AS "Compliance Report Base - Compliance Report__Complia_c9668257",
      "Compliance Report Base - Compliance Report"."Compliance Report Summary - Compliance Report__line_a26a000d" AS "Compliance Report Base - Compliance Report__Complia_eef8c8e5",
      "Compliance Report Base - Compliance Report"."Compliance Report Summary - Compliance Report__line_0ef43e75" AS "Compliance Report Base - Compliance Report__Complia_469410d8",
      "Compliance Report Base - Compliance Report"."Compliance Report Summary - Compliance Report__line_91ad62ee" AS "Compliance Report Base - Compliance Report__Complia_169c9f01",
      "Compliance Report Base - Compliance Report"."Compliance Report Summary - Compliance Report__line_b1027537" AS "Compliance Report Base - Compliance Report__Complia_ba262a42",
      "Compliance Report Base - Compliance Report"."Compliance Report Summary - Compliance Report__line_38be33f3" AS "Compliance Report Base - Compliance Report__Complia_3609a003",
      "Compliance Report Base - Compliance Report"."Compliance Report Summary - Compliance Report__line_82c517d4" AS "Compliance Report Base - Compliance Report__Complia_3d0e6803",
      "Compliance Report Base - Compliance Report"."Compliance Report Summary - Compliance Report__line_6927f733" AS "Compliance Report Base - Compliance Report__Complia_aad5cfd2",
      "Compliance Report Base - Compliance Report"."Compliance Report Summary - Compliance Report__line_93d805cb" AS "Compliance Report Base - Compliance Report__Complia_c437462d",
      "Compliance Report Base - Compliance Report"."Compliance Report Summary - Compliance Report__line_5ae095d0" AS "Compliance Report Base - Compliance Report__Complia_6bd2da0d",
      "Compliance Report Base - Compliance Report"."Compliance Report Summary - Compliance Report__line_157d6973" AS "Compliance Report Base - Compliance Report__Complia_ed316fbb",
      "Compliance Report Base - Compliance Report"."Compliance Report Summary - Compliance Report__line_31fd1f1b" AS "Compliance Report Base - Compliance Report__Complia_2c880057",
      "Compliance Report Base - Compliance Report"."Compliance Report Summary - Compliance Report__line_26ba0b90" AS "Compliance Report Base - Compliance Report__Complia_84fd8648",
      "Compliance Report Base - Compliance Report"."Compliance Report Summary - Compliance Report__line_27419684" AS "Compliance Report Base - Compliance Report__Complia_c8859563",
      "Compliance Report Base - Compliance Report"."Compliance Report Summary - Compliance Report__line_ac263897" AS "Compliance Report Base - Compliance Report__Complia_45fe3e7a",
      "Compliance Report Base - Compliance Report"."Compliance Report Summary - Compliance Report__line_1486f467" AS "Compliance Report Base - Compliance Report__Complia_256023d8",
      "Compliance Report Base - Compliance Report"."Compliance Report Summary - Compliance Report__line_c12cb8c0" AS "Compliance Report Base - Compliance Report__Complia_eee3c998",
      "Compliance Report Base - Compliance Report"."Compliance Report Summary - Compliance Report__line_05eb459f" AS "Compliance Report Base - Compliance Report__Complia_c90c8a63",
      "Compliance Report Base - Compliance Report"."Compliance Report Summary - Compliance Report__line_f2ebda23" AS "Compliance Report Base - Compliance Report__Complia_c7afbbd2",
      "Compliance Report Base - Compliance Report"."Compliance Report Summary - Compliance Report__line_1be763e7" AS "Compliance Report Base - Compliance Report__Complia_b7c1da7c",
      "Compliance Report Base - Compliance Report"."Compliance Report Summary - Compliance Report__line_b72177b0" AS "Compliance Report Base - Compliance Report__Complia_eddee97b",
      "Compliance Report Base - Compliance Report"."Compliance Report Summary - Compliance Report__line_28200104" AS "Compliance Report Base - Compliance Report__Complia_656afc20",
      "Compliance Report Base - Compliance Report"."Compliance Report Summary - Compliance Report__line_53735f1d" AS "Compliance Report Base - Compliance Report__Complia_5698e212",
      "Compliance Report Base - Compliance Report"."Compliance Report Summary - Compliance Report__line_64a07c80" AS "Compliance Report Base - Compliance Report__Complia_91c16e81",
      "Compliance Report Base - Compliance Report"."Compliance Report Summary - Compliance Report__line_60b43dfe" AS "Compliance Report Base - Compliance Report__Complia_a38eca8f",
      "Compliance Report Base - Compliance Report"."Compliance Report Summary - Compliance Report__line_da2710ad" AS "Compliance Report Base - Compliance Report__Complia_83fb46a6",
      "Compliance Report Base - Compliance Report"."Compliance Report Summary - Compliance Report__line_b25fca1c" AS "Compliance Report Base - Compliance Report__Complia_677a2191",
      "Compliance Report Base - Compliance Report"."Compliance Report Summary - Compliance Report__line_4b98033f" AS "Compliance Report Base - Compliance Report__Complia_d3db4f29",
      "Compliance Report Base - Compliance Report"."Compliance Report Summary - Compliance Report__line_1d7d6a31" AS "Compliance Report Base - Compliance Report__Complia_805e5698",
      "Compliance Report Base - Compliance Report"."Compliance Report Summary - Compliance Report__line_684112bb" AS "Compliance Report Base - Compliance Report__Complia_ba662a5c",
      "Compliance Report Base - Compliance Report"."Compliance Report Summary - Compliance Report__line_b1d3ad5e" AS "Compliance Report Base - Compliance Report__Complia_407ecab4",
      "Compliance Report Base - Compliance Report"."Compliance Report Summary - Compliance Report__line_e173956e" AS "Compliance Report Base - Compliance Report__Complia_884b89fd",
      "Compliance Report Base - Compliance Report"."Compliance Report Summary - Compliance Report__line_9a885574" AS "Compliance Report Base - Compliance Report__Complia_6030ea9c",
      "Compliance Report Base - Compliance Report"."Compliance Report Summary - Compliance Report__line_8e71546f" AS "Compliance Report Base - Compliance Report__Complia_392f751b",
      "Compliance Report Base - Compliance Report"."Compliance Report Summary - Compliance Report__line_00d2728d" AS "Compliance Report Base - Compliance Report__Complia_889450ac",
      "Compliance Report Base - Compliance Report"."Compliance Report Summary - Compliance Report__line_29d9cb9c" AS "Compliance Report Base - Compliance Report__Complia_875531b4",
      "Compliance Report Base - Compliance Report"."Compliance Report Summary - Compliance Report__line_d8942234" AS "Compliance Report Base - Compliance Report__Complia_ea067573",
      "Compliance Report Base - Compliance Report"."Compliance Report Summary - Compliance Report__line_125e31fc" AS "Compliance Report Base - Compliance Report__Complia_a93845e5",
      "Compliance Report Base - Compliance Report"."Compliance Report Summary - Compliance Report__line_eb5340d7" AS "Compliance Report Base - Compliance Report__Complia_2ef7cee4",
      "Compliance Report Base - Compliance Report"."Compliance Report Summary - Compliance Report__line_bff5157d" AS "Compliance Report Base - Compliance Report__Complia_87c65017",
      "Compliance Report Base - Compliance Report"."Compliance Report Summary - Compliance Report__line_7c9c21b1" AS "Compliance Report Base - Compliance Report__Complia_4bc20903",
      "Compliance Report Base - Compliance Report"."Compliance Report Summary - Compliance Report__tota_0e1e6fb3" AS "Compliance Report Base - Compliance Report__Complia_0dd060c1",
      "Compliance Report Base - Compliance Report"."Compliance Report Summary - Compliance Report__cred_0f455db6" AS "Compliance Report Base - Compliance Report__Complia_e72f37f4",
      "Compliance Report Base - Compliance Report"."Compliance Report Summary - Compliance Report__cred_964c0c0c" AS "Compliance Report Base - Compliance Report__Complia_cdfb8319",
      "Compliance Report Base - Compliance Report"."Compliance Report Summary - Compliance Report__cred_e14b3c9a" AS "Compliance Report Base - Compliance Report__Complia_1acc0725",
      "Compliance Report Base - Compliance Report"."Compliance Report Summary - Compliance Report__create_date" AS "Compliance Report Base - Compliance Report__Complia_e63c35ab",
      "Compliance Report Base - Compliance Report"."Compliance Report Summary - Compliance Report__update_date" AS "Compliance Report Base - Compliance Report__Complia_b3f1ff5d",
      "Compliance Report Base - Compliance Report"."Compliance Report Summary - Compliance Report__create_user" AS "Compliance Report Base - Compliance Report__Complia_c131d498",
      "Compliance Report Base - Compliance Report"."Compliance Report Summary - Compliance Report__update_user" AS "Compliance Report Base - Compliance Report__Complia_94fc1e6e",
      "Compliance Report Base - Compliance Report"."Compliance Report Summary - Compliance Report__earl_6d4994a4" AS "Compliance Report Base - Compliance Report__Complia_df1f10d1",
      "Compliance Report Base - Compliance Report"."Compliance Report Summary - Compliance Report__earl_f440c51e" AS "Compliance Report Base - Compliance Report__Complia_a759d116",
      "Compliance Report Base - Compliance Report"."Compliance Report Summary - Compliance Report__earl_8347f588" AS "Compliance Report Base - Compliance Report__Complia_63b4b44e",
      "Compliance Report Base - Compliance Report"."Compliance Report Summary - Compliance Report__earl_1d23602b" AS "Compliance Report Base - Compliance Report__Complia_05c7a0a8",
      "Compliance Report Base - Compliance Report"."Transaction__transaction_id" AS "Compliance Report Base - Compliance Report__Transac_cf3e7bc2",
      "Compliance Report Base - Compliance Report"."Transaction__compliance_units" AS "Compliance Report Base - Compliance Report__Transac_2787ccf9",
      "Compliance Report Base - Compliance Report"."Transaction__organization_id" AS "Compliance Report Base - Compliance Report__Transac_d7fde363",
      "Compliance Report Base - Compliance Report"."Transaction__transaction_action" AS "Compliance Report Base - Compliance Report__Transac_5afd1852",
      "Compliance Report Base - Compliance Report"."Transaction__create_date" AS "Compliance Report Base - Compliance Report__Transac_1a243093",
      "Compliance Report Base - Compliance Report"."Transaction__update_date" AS "Compliance Report Base - Compliance Report__Transac_4fe9fa65",
      "Compliance Report Base - Compliance Report"."Transaction__create_user" AS "Compliance Report Base - Compliance Report__Transac_3d29d1a0",
      "Compliance Report Base - Compliance Report"."Transaction__update_user" AS "Compliance Report Base - Compliance Report__Transac_68e41b56",
      "Compliance Report Base - Compliance Report"."Transaction__effective_date" AS "Compliance Report Base - Compliance Report__Transac_cfe283e1",
      "Compliance Report Base - Compliance Report"."Transaction__effective_status" AS "Compliance Report Base - Compliance Report__Transac_25b92424",
      "Compliance Report Base - Compliance Report"."Transaction__expiration_date" AS "Compliance Report Base - Compliance Report__Transac_117f7033",
      "Compliance Report Base - Compliance Report"."Organization__organization_id" AS "Compliance Report Base - Compliance Report__Organiz_ea2b8583",
      "Compliance Report Base - Compliance Report"."Organization__organization_code" AS "Compliance Report Base - Compliance Report__Organiz_93047002",
      "Compliance Report Base - Compliance Report"."Organization__name" AS "Compliance Report Base - Compliance Report__Organiz_825c76de",
      "Compliance Report Base - Compliance Report"."Organization__operating_name" AS "Compliance Report Base - Compliance Report__Organiz_1e26fe43",
      "Compliance Report Base - Compliance Report"."Organization__email" AS "Compliance Report Base - Compliance Report__Organiz_6f46599a",
      "Compliance Report Base - Compliance Report"."Organization__phone" AS "Compliance Report Base - Compliance Report__Organiz_cc9bb233",
      "Compliance Report Base - Compliance Report"."Organization__edrms_record" AS "Compliance Report Base - Compliance Report__Organiz_f96b3406",
      "Compliance Report Base - Compliance Report"."Organization__total_balance" AS "Compliance Report Base - Compliance Report__Organiz_5b0e3a8e",
      "Compliance Report Base - Compliance Report"."Organization__reserved_balance" AS "Compliance Report Base - Compliance Report__Organiz_002dae56",
      "Compliance Report Base - Compliance Report"."Organization__count_transfers_in_progress" AS "Compliance Report Base - Compliance Report__Organiz_ddd4cd6e",
      "Compliance Report Base - Compliance Report"."Organization__organization_status_id" AS "Compliance Report Base - Compliance Report__Organiz_4ca3989e",
      "Compliance Report Base - Compliance Report"."Organization__organization_type_id" AS "Compliance Report Base - Compliance Report__Organiz_af01dea6",
      "Compliance Report Base - Compliance Report"."Organization__organization_address_id" AS "Compliance Report Base - Compliance Report__Organiz_57f78a9f",
      "Compliance Report Base - Compliance Report"."Organization__organization_attorney_address_id" AS "Compliance Report Base - Compliance Report__Organiz_b438bcc2",
      "Compliance Report Base - Compliance Report"."Organization__create_date" AS "Compliance Report Base - Compliance Report__Organiz_48401463",
      "Compliance Report Base - Compliance Report"."Organization__update_date" AS "Compliance Report Base - Compliance Report__Organiz_1d8dde95",
      "Compliance Report Base - Compliance Report"."Organization__create_user" AS "Compliance Report Base - Compliance Report__Organiz_6f4df550",
      "Compliance Report Base - Compliance Report"."Organization__update_user" AS "Compliance Report Base - Compliance Report__Organiz_3a803fa6",
      "Compliance Report Base - Compliance Report"."Organization__effective_date" AS "Compliance Report Base - Compliance Report__Organiz_c111b484",
      "Compliance Report Base - Compliance Report"."Organization__effective_status" AS "Compliance Report Base - Compliance Report__Organiz_858e103a",
      "Compliance Report Base - Compliance Report"."Organization__expiration_date" AS "Compliance Report Base - Compliance Report__Organiz_2ca916d3",
      "Compliance Report Base - Compliance Report"."Organization__has_early_issuance" AS "Compliance Report Base - Compliance Report__Organiz_23acfb32",
      "Compliance Report Base - Compliance Report"."Organization__records_address" AS "Compliance Report Base - Compliance Report__Organiz_eb230b97",
      "Compliance Report Base - Compliance Report"."Compliance Reports Chained - Compliance Report Grou_1a77e4cb" AS "Compliance Report Base - Compliance Report__Complia_a81d65f5",
      "Compliance Report Base - Compliance Report"."Compliance Reports Chained - Compliance Report Grou_480bb7b1" AS "Compliance Report Base - Compliance Report__Complia_cfae0019"
    FROM
      (
        SELECT
          "public"."allocation_agreement"."group_uuid" AS "group_uuid",
          MAX("public"."allocation_agreement"."version") AS "max"
        FROM
          "public"."allocation_agreement"
       
GROUP BY
          "public"."allocation_agreement"."group_uuid"
       
ORDER BY
          "public"."allocation_agreement"."group_uuid" ASC
      ) AS "source"
     
LEFT JOIN "public"."allocation_agreement" AS "Allocation Agreement - Group UUID" ON (
        "source"."group_uuid" = "Allocation Agreement - Group UUID"."group_uuid"
      )
     
   AND (
        "source"."max" = "Allocation Agreement - Group UUID"."version"
      )
      LEFT JOIN (
        SELECT
          "public"."compliance_report"."compliance_report_id" AS "compliance_report_id",
          "public"."compliance_report"."compliance_period_id" AS "compliance_period_id",
          "public"."compliance_report"."organization_id" AS "organization_id",
          "public"."compliance_report"."current_status_id" AS "current_status_id",
          "public"."compliance_report"."transaction_id" AS "transaction_id",
          "public"."compliance_report"."compliance_report_group_uuid" AS "compliance_report_group_uuid",
          "public"."compliance_report"."legacy_id" AS "legacy_id",
          "public"."compliance_report"."version" AS "version",
          "public"."compliance_report"."supplemental_initiator" AS "supplemental_initiator",
          "public"."compliance_report"."reporting_frequency" AS "reporting_frequency",
          "public"."compliance_report"."nickname" AS "nickname",
          "public"."compliance_report"."supplemental_note" AS "supplemental_note",
          "public"."compliance_report"."create_date" AS "create_date",
          "public"."compliance_report"."update_date" AS "update_date",
          "public"."compliance_report"."create_user" AS "create_user",
          "public"."compliance_report"."update_user" AS "update_user",
          "public"."compliance_report"."assessment_statement" AS "assessment_statement",
          CASE
            WHEN "Compliance Report Summary - Compliance Report"."line_11_fossil_derived_base_fuel_total" > 0 THEN 'Not Met'
            ELSE 'Met'
          END AS "Renewable Requirements",
          CASE
            WHEN "Compliance Report Summary - Compliance Report"."line_21_non_compliance_penalty_payable" > 0 THEN 'Not Met'
            ELSE 'Met'
          END AS "Low Carbon Requirements",
          "Compliance Period"."compliance_period_id" AS "Compliance Period__compliance_period_id",
          "Compliance Period"."description" AS "Compliance Period__description",
          "Compliance Period"."display_order" AS "Compliance Period__display_order",
          "Compliance Period"."create_date" AS "Compliance Period__create_date",
          "Compliance Period"."update_date" AS "Compliance Period__update_date",
          "Compliance Period"."effective_date" AS "Compliance Period__effective_date",
          "Compliance Period"."effective_status" AS "Compliance Period__effective_status",
          "Compliance Period"."expiration_date" AS "Compliance Period__expiration_date",
          "Compliance Report Status - Current Status"."compliance_report_status_id" AS "Compliance Report Status - Current Status__complian_8aca39b7",
          "Compliance Report Status - Current Status"."display_order" AS "Compliance Report Status - Current Status__display_order",
          "Compliance Report Status - Current Status"."status" AS "Compliance Report Status - Current Status__status",
          "Compliance Report Status - Current Status"."create_date" AS "Compliance Report Status - Current Status__create_date",
          "Compliance Report Status - Current Status"."update_date" AS "Compliance Report Status - Current Status__update_date",
          "Compliance Report Status - Current Status"."effective_date" AS "Compliance Report Status - Current Status__effective_date",
          "Compliance Report Status - Current Status"."effective_status" AS "Compliance Report Status - Current Status__effective_status",
          "Compliance Report Status - Current Status"."expiration_date" AS "Compliance Report Status - Current Status__expiration_date",
          "Compliance Report Summary - Compliance Report"."summary_id" AS "Compliance Report Summary - Compliance Report__summary_id",
          "Compliance Report Summary - Compliance Report"."compliance_report_id" AS "Compliance Report Summary - Compliance Report__comp_1db2e1e9",
          "Compliance Report Summary - Compliance Report"."quarter" AS "Compliance Report Summary - Compliance Report__quarter",
          "Compliance Report Summary - Compliance Report"."is_locked" AS "Compliance Report Summary - Compliance Report__is_locked",
          "Compliance Report Summary - Compliance Report"."line_1_fossil_derived_base_fuel_gasoline" AS "Compliance Report Summary - Compliance Report__line_2c0818fb",
          "Compliance Report Summary - Compliance Report"."line_1_fossil_derived_base_fuel_diesel" AS "Compliance Report Summary - Compliance Report__line_2ff66c5b",
          "Compliance Report Summary - Compliance Report"."line_1_fossil_derived_base_fuel_jet_fuel" AS "Compliance Report Summary - Compliance Report__line_1fcf7a18",
          "Compliance Report Summary - Compliance Report"."line_2_eligible_renewable_fuel_supplied_gasoline" AS "Compliance Report Summary - Compliance Report__line_d70f8aef",
          "Compliance Report Summary - Compliance Report"."line_2_eligible_renewable_fuel_supplied_diesel" AS "Compliance Report Summary - Compliance Report__line_2773c83c",
          "Compliance Report Summary - Compliance Report"."line_2_eligible_renewable_fuel_supplied_jet_fuel" AS "Compliance Report Summary - Compliance Report__line_e4c8e80c",
          "Compliance Report Summary - Compliance Report"."line_3_total_tracked_fuel_supplied_gasoline" AS "Compliance Report Summary - Compliance Report__line_9cec896d",
          "Compliance Report Summary - Compliance Report"."line_3_total_tracked_fuel_supplied_diesel" AS "Compliance Report Summary - Compliance Report__line_489bea32",
          "Compliance Report Summary - Compliance Report"."line_3_total_tracked_fuel_supplied_jet_fuel" AS "Compliance Report Summary - Compliance Report__line_af2beb8e",
          "Compliance Report Summary - Compliance Report"."line_4_eligible_renewable_fuel_required_gasoline" AS "Compliance Report Summary - Compliance Report__line_a26a000d",
          "Compliance Report Summary - Compliance Report"."line_4_eligible_renewable_fuel_required_diesel" AS "Compliance Report Summary - Compliance Report__line_0ef43e75",
          "Compliance Report Summary - Compliance Report"."line_4_eligible_renewable_fuel_required_jet_fuel" AS "Compliance Report Summary - Compliance Report__line_91ad62ee",
          "Compliance Report Summary - Compliance Report"."line_5_net_notionally_transferred_gasoline" AS "Compliance Report Summary - Compliance Report__line_b1027537",
          "Compliance Report Summary - Compliance Report"."line_5_net_notionally_transferred_diesel" AS "Compliance Report Summary - Compliance Report__line_38be33f3",
          "Compliance Report Summary - Compliance Report"."line_5_net_notionally_transferred_jet_fuel" AS "Compliance Report Summary - Compliance Report__line_82c517d4",
          "Compliance Report Summary - Compliance Report"."line_6_renewable_fuel_retained_gasoline" AS "Compliance Report Summary - Compliance Report__line_6927f733",
          "Compliance Report Summary - Compliance Report"."line_6_renewable_fuel_retained_diesel" AS "Compliance Report Summary - Compliance Report__line_93d805cb",
          "Compliance Report Summary - Compliance Report"."line_6_renewable_fuel_retained_jet_fuel" AS "Compliance Report Summary - Compliance Report__line_5ae095d0",
          "Compliance Report Summary - Compliance Report"."line_7_previously_retained_gasoline" AS "Compliance Report Summary - Compliance Report__line_157d6973",
          "Compliance Report Summary - Compliance Report"."line_7_previously_retained_diesel" AS "Compliance Report Summary - Compliance Report__line_31fd1f1b",
          "Compliance Report Summary - Compliance Report"."line_7_previously_retained_jet_fuel" AS "Compliance Report Summary - Compliance Report__line_26ba0b90",
          "Compliance Report Summary - Compliance Report"."line_8_obligation_deferred_gasoline" AS "Compliance Report Summary - Compliance Report__line_27419684",
          "Compliance Report Summary - Compliance Report"."line_8_obligation_deferred_diesel" AS "Compliance Report Summary - Compliance Report__line_ac263897",
          "Compliance Report Summary - Compliance Report"."line_8_obligation_deferred_jet_fuel" AS "Compliance Report Summary - Compliance Report__line_1486f467",
          "Compliance Report Summary - Compliance Report"."line_9_obligation_added_gasoline" AS "Compliance Report Summary - Compliance Report__line_c12cb8c0",
          "Compliance Report Summary - Compliance Report"."line_9_obligation_added_diesel" AS "Compliance Report Summary - Compliance Report__line_05eb459f",
          "Compliance Report Summary - Compliance Report"."line_9_obligation_added_jet_fuel" AS "Compliance Report Summary - Compliance Report__line_f2ebda23",
          "Compliance Report Summary - Compliance Report"."line_10_net_renewable_fuel_supplied_gasoline" AS "Compliance Report Summary - Compliance Report__line_1be763e7",
          "Compliance Report Summary - Compliance Report"."line_10_net_renewable_fuel_supplied_diesel" AS "Compliance Report Summary - Compliance Report__line_b72177b0",
          "Compliance Report Summary - Compliance Report"."line_10_net_renewable_fuel_supplied_jet_fuel" AS "Compliance Report Summary - Compliance Report__line_28200104",
          "Compliance Report Summary - Compliance Report"."line_11_non_compliance_penalty_gasoline" AS "Compliance Report Summary - Compliance Report__line_53735f1d",
          "Compliance Report Summary - Compliance Report"."line_11_non_compliance_penalty_diesel" AS "Compliance Report Summary - Compliance Report__line_64a07c80",
          "Compliance Report Summary - Compliance Report"."line_11_non_compliance_penalty_jet_fuel" AS "Compliance Report Summary - Compliance Report__line_60b43dfe",
          "Compliance Report Summary - Compliance Report"."line_12_low_carbon_fuel_required" AS "Compliance Report Summary - Compliance Report__line_da2710ad",
          "Compliance Report Summary - Compliance Report"."line_13_low_carbon_fuel_supplied" AS "Compliance Report Summary - Compliance Report__line_b25fca1c",
          "Compliance Report Summary - Compliance Report"."line_14_low_carbon_fuel_surplus" AS "Compliance Report Summary - Compliance Report__line_4b98033f",
          "Compliance Report Summary - Compliance Report"."line_15_banked_units_used" AS "Compliance Report Summary - Compliance Report__line_1d7d6a31",
          "Compliance Report Summary - Compliance Report"."line_16_banked_units_remaining" AS "Compliance Report Summary - Compliance Report__line_684112bb",
          "Compliance Report Summary - Compliance Report"."line_17_non_banked_units_used" AS "Compliance Report Summary - Compliance Report__line_b1d3ad5e",
          "Compliance Report Summary - Compliance Report"."line_18_units_to_be_banked" AS "Compliance Report Summary - Compliance Report__line_e173956e",
          "Compliance Report Summary - Compliance Report"."line_19_units_to_be_exported" AS "Compliance Report Summary - Compliance Report__line_9a885574",
          "Compliance Report Summary - Compliance Report"."line_20_surplus_deficit_units" AS "Compliance Report Summary - Compliance Report__line_8e71546f",
          "Compliance Report Summary - Compliance Report"."line_21_surplus_deficit_ratio" AS "Compliance Report Summary - Compliance Report__line_00d2728d",
          "Compliance Report Summary - Compliance Report"."line_22_compliance_units_issued" AS "Compliance Report Summary - Compliance Report__line_29d9cb9c",
          "Compliance Report Summary - Compliance Report"."line_11_fossil_derived_base_fuel_gasoline" AS "Compliance Report Summary - Compliance Report__line_d8942234",
          "Compliance Report Summary - Compliance Report"."line_11_fossil_derived_base_fuel_diesel" AS "Compliance Report Summary - Compliance Report__line_125e31fc",
          "Compliance Report Summary - Compliance Report"."line_11_fossil_derived_base_fuel_jet_fuel" AS "Compliance Report Summary - Compliance Report__line_eb5340d7",
          "Compliance Report Summary - Compliance Report"."line_11_fossil_derived_base_fuel_total" AS "Compliance Report Summary - Compliance Report__line_bff5157d",
          "Compliance Report Summary - Compliance Report"."line_21_non_compliance_penalty_payable" AS "Compliance Report Summary - Compliance Report__line_7c9c21b1",
          "Compliance Report Summary - Compliance Report"."total_non_compliance_penalty_payable" AS "Compliance Report Summary - Compliance Report__tota_0e1e6fb3",
          "Compliance Report Summary - Compliance Report"."credits_offset_a" AS "Compliance Report Summary - Compliance Report__cred_0f455db6",
          "Compliance Report Summary - Compliance Report"."credits_offset_b" AS "Compliance Report Summary - Compliance Report__cred_964c0c0c",
          "Compliance Report Summary - Compliance Report"."credits_offset_c" AS "Compliance Report Summary - Compliance Report__cred_e14b3c9a",
          "Compliance Report Summary - Compliance Report"."create_date" AS "Compliance Report Summary - Compliance Report__create_date",
          "Compliance Report Summary - Compliance Report"."update_date" AS "Compliance Report Summary - Compliance Report__update_date",
          "Compliance Report Summary - Compliance Report"."create_user" AS "Compliance Report Summary - Compliance Report__create_user",
          "Compliance Report Summary - Compliance Report"."update_user" AS "Compliance Report Summary - Compliance Report__update_user",
          "Compliance Report Summary - Compliance Report"."early_issuance_credits_q1" AS "Compliance Report Summary - Compliance Report__earl_6d4994a4",
          "Compliance Report Summary - Compliance Report"."early_issuance_credits_q2" AS "Compliance Report Summary - Compliance Report__earl_f440c51e",
          "Compliance Report Summary - Compliance Report"."early_issuance_credits_q3" AS "Compliance Report Summary - Compliance Report__earl_8347f588",
          "Compliance Report Summary - Compliance Report"."early_issuance_credits_q4" AS "Compliance Report Summary - Compliance Report__earl_1d23602b",
          "Transaction"."transaction_id" AS "Transaction__transaction_id",
          "Transaction"."compliance_units" AS "Transaction__compliance_units",
          "Transaction"."organization_id" AS "Transaction__organization_id",
          "Transaction"."transaction_action" AS "Transaction__transaction_action",
          "Transaction"."create_date" AS "Transaction__create_date",
          "Transaction"."update_date" AS "Transaction__update_date",
          "Transaction"."create_user" AS "Transaction__create_user",
          "Transaction"."update_user" AS "Transaction__update_user",
          "Transaction"."effective_date" AS "Transaction__effective_date",
          "Transaction"."effective_status" AS "Transaction__effective_status",
          "Transaction"."expiration_date" AS "Transaction__expiration_date",
          "Organization"."organization_id" AS "Organization__organization_id",
          "Organization"."organization_code" AS "Organization__organization_code",
          "Organization"."name" AS "Organization__name",
          "Organization"."operating_name" AS "Organization__operating_name",
          "Organization"."email" AS "Organization__email",
          "Organization"."phone" AS "Organization__phone",
          "Organization"."edrms_record" AS "Organization__edrms_record",
          "Organization"."total_balance" AS "Organization__total_balance",
          "Organization"."reserved_balance" AS "Organization__reserved_balance",
          "Organization"."count_transfers_in_progress" AS "Organization__count_transfers_in_progress",
          "Organization"."organization_status_id" AS "Organization__organization_status_id",
          "Organization"."organization_type_id" AS "Organization__organization_type_id",
          "Organization"."organization_address_id" AS "Organization__organization_address_id",
          "Organization"."organization_attorney_address_id" AS "Organization__organization_attorney_address_id",
          "Organization"."create_date" AS "Organization__create_date",
          "Organization"."update_date" AS "Organization__update_date",
          "Organization"."create_user" AS "Organization__create_user",
          "Organization"."update_user" AS "Organization__update_user",
          "Organization"."effective_date" AS "Organization__effective_date",
          "Organization"."effective_status" AS "Organization__effective_status",
          "Organization"."expiration_date" AS "Organization__expiration_date",
          "Organization"."has_early_issuance" AS "Organization__has_early_issuance",
          "Organization"."records_address" AS "Organization__records_address",
          "Compliance Reports Chained - Compliance Report Group UUID"."group_uuid" AS "Compliance Reports Chained - Compliance Report Grou_1a77e4cb",
          "Compliance Reports Chained - Compliance Report Group UUID"."max_version" AS "Compliance Reports Chained - Compliance Report Grou_480bb7b1"
        FROM
          "public"."compliance_report"
          INNER JOIN "public"."compliance_period" AS "Compliance Period" ON "public"."compliance_report"."compliance_period_id" = "Compliance Period"."compliance_period_id"
          INNER JOIN "public"."compliance_report_status" AS "Compliance Report Status - Current Status" ON "public"."compliance_report"."current_status_id" = "Compliance Report Status - Current Status"."compliance_report_status_id"
          INNER JOIN "public"."compliance_report_summary" AS "Compliance Report Summary - Compliance Report" ON "public"."compliance_report"."compliance_report_id" = "Compliance Report Summary - Compliance Report"."compliance_report_id"
          LEFT JOIN "public"."transaction" AS "Transaction" ON "public"."compliance_report"."transaction_id" = "Transaction"."transaction_id"
          LEFT JOIN "public"."organization" AS "Organization" ON "public"."compliance_report"."organization_id" = "Organization"."organization_id"
          INNER JOIN (
            SELECT
              compliance_report_group_uuid AS group_uuid,
              max(VERSION) AS max_version
            FROM
              COMPLIANCE_REPORT
            GROUP BY
              COMPLIANCE_REPORT.compliance_report_group_uuid
          ) AS "Compliance Reports Chained - Compliance Report Group UUID" ON (
            "public"."compliance_report"."compliance_report_group_uuid" = "Compliance Reports Chained - Compliance Report Group UUID"."group_uuid"
          )
          AND (
            "public"."compliance_report"."version" = "Compliance Reports Chained - Compliance Report Group UUID"."max_version"
          )
      ) AS "Compliance Report Base - Compliance Report" ON "Allocation Agreement - Group UUID"."compliance_report_id" = "Compliance Report Base - Compliance Report"."compliance_report_id";

-- Grant SELECT privileges to the reporting role
GRANT SELECT ON public.vw_allocation_agreement_base TO basic_lcfs_reporting_role;