# Use the official Python 3.9 slim image
FROM python:3.9-slim

# Set working directory
WORKDIR /app

# Install Python dependencies
# Do this before copying the entire application for better layer caching
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copy the entire application
COPY . .

# Make necessary scripts executable
# Note: If you mount your local directory using docker-compose, 
# ensure these scripts also have execute permissions on your host machine.
# chmod +x ./backend/wait-for-it.sh ./backend/lcfs/prestart.sh
RUN chmod +x wait-for-it.sh lcfs/prestart.sh

# Expose port and set default environment variables
EXPOSE 8000
ENV UVICORN_HOST=0.0.0.0

# Start command
CMD ./wait-for-it.sh db:5432 --timeout=30 -- ./lcfs/prestart.sh && uvicorn main:app --host 0.0.0.0 --port 8000 --reload
