"""UserProfile changes

Revision ID: be5f632879cc
Revises: 4934fc1b9f97
Create Date: 2023-12-20 19:59:32.742527

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "be5f632879cc"
down_revision = "4934fc1b9f97"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "organization",
        "email",
        existing_type=sa.VARCHAR(length=255),
        comment="Organization's email address",
        existing_nullable=True,
    )
    op.alter_column(
        "organization",
        "phone",
        existing_type=sa.VARCHAR(length=50),
        comment="Organization's phone number",
        existing_nullable=True,
    )
    op.alter_column(
        "organization",
        "edrms_record",
        existing_type=sa.VARCHAR(length=100),
        comment="Organization's EDRMS record number",
        existing_nullable=True,
    )
    op.add_column(
        "user_profile",
        sa.Column(
            "first_name", sa.String(length=100), nullable=True, comment="First name"
        ),
    )
    op.add_column(
        "user_profile",
        sa.Column(
            "last_name", sa.String(length=100), nullable=True, comment="Last name"
        ),
    )
    op.add_column(
        "user_profile",
        sa.Column(
            "is_active", sa.Boolean(), nullable=False, comment="Is the user active?"
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user_profile", "is_active")
    op.drop_column("user_profile", "last_name")
    op.drop_column("user_profile", "first_name")
    op.alter_column(
        "organization",
        "edrms_record",
        existing_type=sa.VARCHAR(length=100),
        comment=None,
        existing_comment="Organization's EDRMS record number",
        existing_nullable=True,
    )
    op.alter_column(
        "organization",
        "phone",
        existing_type=sa.VARCHAR(length=50),
        comment=None,
        existing_comment="Organization's phone number",
        existing_nullable=True,
    )
    op.alter_column(
        "organization",
        "email",
        existing_type=sa.VARCHAR(length=255),
        comment=None,
        existing_comment="Organization's email address",
        existing_nullable=True,
    )
    # ### end Alembic commands ###
