"""transfer migration dependancy

Revision ID: 6888110bbcae
Revises: c11dccc64b60
Create Date: 2023-11-14 19:48:07.307525

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "6888110bbcae"
down_revision = "c11dccc64b60"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("issuance", sa.Column("transaction_id", sa.Integer(), nullable=True))
    op.add_column("issuance", sa.Column("comment_id", sa.Integer(), nullable=True))
    op.create_foreign_key(None, "issuance", "transaction", ["transaction_id"], ["id"])
    op.create_foreign_key(None, "issuance", "comment", ["comment_id"], ["id"])
    op.add_column(
        "issuance_history", sa.Column("issuance_id", sa.Integer(), nullable=True)
    )
    op.add_column(
        "issuance_history", sa.Column("transaction_id", sa.Integer(), nullable=True)
    )
    op.add_column(
        "issuance_history", sa.Column("comment_id", sa.Integer(), nullable=True)
    )
    op.create_foreign_key(None, "issuance_history", "issuance", ["issuance_id"], ["id"])
    op.create_foreign_key(None, "issuance_history", "comment", ["comment_id"], ["id"])
    op.create_foreign_key(
        None, "issuance_history", "transaction", ["transaction_id"], ["id"]
    )
    op.add_column("transaction", sa.Column("issuance_id", sa.Integer(), nullable=True))
    op.add_column("transaction", sa.Column("transfer_id", sa.Integer(), nullable=True))
    op.create_foreign_key(None, "transaction", "issuance", ["issuance_id"], ["id"])
    op.create_foreign_key(None, "transaction", "transfer", ["transfer_id"], ["id"])
    op.add_column("transfer", sa.Column("transaction_id", sa.Integer(), nullable=True))
    op.add_column("transfer", sa.Column("comment_id", sa.Integer(), nullable=True))
    op.add_column(
        "transfer", sa.Column("transfer_category", sa.Integer(), nullable=True)
    )
    op.create_foreign_key(None, "transfer", "category", ["transfer_category"], ["id"])
    op.create_foreign_key(None, "transfer", "transaction", ["transaction_id"], ["id"])
    op.create_foreign_key(None, "transfer", "comment", ["comment_id"], ["id"])
    op.add_column(
        "transfer_history", sa.Column("transaction_id", sa.Integer(), nullable=True)
    )
    op.add_column(
        "transfer_history", sa.Column("comment_id", sa.Integer(), nullable=True)
    )
    op.create_foreign_key(
        None, "transfer_history", "transaction", ["transaction_id"], ["id"]
    )
    op.create_foreign_key(None, "transfer_history", "comment", ["comment_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "transfer_history", type_="foreignkey")
    op.drop_constraint(None, "transfer_history", type_="foreignkey")
    op.drop_column("transfer_history", "comment_id")
    op.drop_column("transfer_history", "transaction_id")
    op.drop_constraint(None, "transfer", type_="foreignkey")
    op.drop_constraint(None, "transfer", type_="foreignkey")
    op.drop_constraint(None, "transfer", type_="foreignkey")
    op.drop_column("transfer", "transfer_category")
    op.drop_column("transfer", "comment_id")
    op.drop_column("transfer", "transaction_id")
    op.drop_constraint(None, "transaction", type_="foreignkey")
    op.drop_constraint(None, "transaction", type_="foreignkey")
    op.drop_column("transaction", "transfer_id")
    op.drop_column("transaction", "issuance_id")
    op.drop_constraint(None, "issuance_history", type_="foreignkey")
    op.drop_constraint(None, "issuance_history", type_="foreignkey")
    op.drop_constraint(None, "issuance_history", type_="foreignkey")
    op.drop_column("issuance_history", "comment_id")
    op.drop_column("issuance_history", "transaction_id")
    op.drop_column("issuance_history", "issuance_id")
    op.drop_constraint(None, "issuance", type_="foreignkey")
    op.drop_constraint(None, "issuance", type_="foreignkey")
    op.drop_column("issuance", "comment_id")
    op.drop_column("issuance", "transaction_id")
    # ### end Alembic commands ###
