"""schema update

Revision ID: 9c663ed10c09
Revises: 0b160b552203
Create Date: 2023-12-28 18:07:48.254871

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "9c663ed10c09"
down_revision = "0b160b552203"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "organization",
        "email",
        existing_type=sa.VARCHAR(length=255),
        comment="Organization's email address",
        existing_nullable=True,
    )
    op.alter_column(
        "organization",
        "phone",
        existing_type=sa.VARCHAR(length=50),
        comment="Organization's phone number",
        existing_nullable=True,
    )
    op.alter_column(
        "organization",
        "edrms_record",
        existing_type=sa.VARCHAR(length=100),
        comment="Organization's EDRMS record number",
        existing_nullable=True,
    )
    op.add_column(
        "user_profile",
        sa.Column(
            "first_name", sa.String(length=100), nullable=True, comment="First name"
        ),
    )
    op.add_column(
        "user_profile",
        sa.Column(
            "last_name", sa.String(length=100), nullable=True, comment="Last name"
        ),
    )
    op.alter_column(
        "user_profile",
        "is_active",
        existing_type=sa.BOOLEAN(),
        comment="Is the user active?",
        existing_comment="True if the user is active, otherwise False.",
        existing_nullable=False,
        existing_server_default=sa.text("true"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "user_profile",
        "is_active",
        existing_type=sa.BOOLEAN(),
        comment="True if the user is active, otherwise False.",
        existing_comment="Is the user active?",
        existing_nullable=False,
        existing_server_default=sa.text("true"),
    )
    op.drop_column("user_profile", "last_name")
    op.drop_column("user_profile", "first_name")
    op.alter_column(
        "organization",
        "edrms_record",
        existing_type=sa.VARCHAR(length=100),
        comment=None,
        existing_comment="Organization's EDRMS record number",
        existing_nullable=True,
    )
    op.alter_column(
        "organization",
        "phone",
        existing_type=sa.VARCHAR(length=50),
        comment=None,
        existing_comment="Organization's phone number",
        existing_nullable=True,
    )
    op.alter_column(
        "organization",
        "email",
        existing_type=sa.VARCHAR(length=255),
        comment=None,
        existing_comment="Organization's email address",
        existing_nullable=True,
    )
    # ### end Alembic commands ###
