"""Add UQ to TCI

Revision ID: ab04810d4d7c
Revises: 5fbcb508c1be
Create Date: 2024-12-22 23:46:37.505166

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "ab04810d4d7c"
down_revision = "5fbcb508c1be"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(
        "uq_target_carbon_intensity_compliance_fuel",
        "target_carbon_intensity",
        ["compliance_period_id", "fuel_category_id"],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "uq_target_carbon_intensity_compliance_fuel",
        "target_carbon_intensity",
        type_="unique",
    )
    # ### end Alembic commands ###
