"""Add three comment columns

Revision ID: e181ecb29c9a
Revises: 0ad956decbc4
Create Date: 2024-03-27 12:38:47.214827

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "e181ecb29c9a"
down_revision = "0ad956decbc4"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "transfer",
        sa.Column(
            "from_org_comment",
            sa.String(length=1000),
            nullable=True,
            comment="Comment from the from-organization",
        ),
    )
    op.add_column(
        "transfer",
        sa.Column(
            "to_org_comment",
            sa.String(length=1000),
            nullable=True,
            comment="Comment from the to-organization",
        ),
    )
    op.add_column(
        "transfer",
        sa.Column(
            "gov_comment",
            sa.String(length=1500),
            nullable=True,
            comment="Comment from the government to organizations",
        ),
    )
    op.drop_constraint("transfer_comment_id_fkey", "transfer", type_="foreignkey")
    op.drop_column("transfer", "comment_id")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "transfer",
        sa.Column("comment_id", sa.INTEGER(), autoincrement=False, nullable=True),
    )
    op.create_foreign_key(
        "transfer_comment_id_fkey",
        "transfer",
        "comment",
        ["comment_id"],
        ["comment_id"],
    )
    op.drop_column("transfer", "gov_comment")
    op.drop_column("transfer", "to_org_comment")
    op.drop_column("transfer", "from_org_comment")
    # ### end Alembic commands ###
