"""update other diesel

Revision ID: 59873cafbcd8
Revises: 851e09cf8661
Create Date: 2024-12-20 05:17:40.638826

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "59873cafbcd8"
down_revision = "851e09cf8661"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
        """
        UPDATE fuel_type 
        SET fossil_derived = false, other_uses_fossil_derived = false
        WHERE fuel_type = 'Other diesel'
        """
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
        """
        UPDATE fuel_type 
        SET fossil_derived = true, other_uses_fossil_derived = true 
        WHERE fuel_type = 'Other diesel'
        """
    )
    # ### end Alembic commands ###
