"""fp_facility_location

Revision ID: bb4f823e5aac
Revises: 69834c45d1dd
Create Date: 2024-05-28 00:33:41.793523

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "bb4f823e5aac"
down_revision = "3c61bcf0d14d"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "fuel_code",
        sa.Column(
            "fuel_production_facility_city",
            sa.String(length=1000),
            nullable=True,
            comment="City of the fuel production",
        ),
    )
    op.add_column(
        "fuel_code",
        sa.Column(
            "fuel_production_facility_province_state",
            sa.String(length=1000),
            nullable=True,
            comment="Province or state of the fuel production",
        ),
    )
    op.add_column(
        "fuel_code",
        sa.Column(
            "fuel_production_facility_country",
            sa.String(length=1000),
            nullable=True,
            comment="Country of the fuel production",
        ),
    )
    op.drop_column("fuel_code", "fuel_production_facility_location")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "fuel_code",
        sa.Column(
            "fuel_production_facility_location",
            sa.VARCHAR(length=1000),
            autoincrement=False,
            nullable=False,
            comment="Location of the fuel production",
        ),
    )
    op.drop_column("fuel_code", "fuel_production_facility_country")
    op.drop_column("fuel_code", "fuel_production_facility_province_state")
    op.drop_column("fuel_code", "fuel_production_facility_city")
    # ### end Alembic commands ###
