"""allocation agreement update

Revision ID: 401c9ed94cdb
Revises: 2f1e766ef118
Create Date: 2024-08-19 17:57:56.717567

"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "401c9ed94cdb"
down_revision = "2f1e766ef118"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "allocation_agreement",
        sa.Column(
            "transaction_partner_email",
            sa.String(),
            nullable=False,
            comment="Transaction Partner email",
        ),
    )
    op.add_column(
        "allocation_agreement",
        sa.Column(
            "transaction_parnter_phone",
            sa.String(),
            nullable=False,
            comment="Transaction Partner phone number",
        ),
    )
    op.add_column(
        "allocation_agreement",
        sa.Column(
            "ci_fuel",
            sa.Integer(),
            nullable=False,
            comment="The Carbon intesity of fuel",
        ),
    )
    op.add_column(
        "allocation_agreement",
        sa.Column(
            "units",
            sa.String(),
            nullable=False,
            comment="Units of the fuel quantity. Auto-selected, locked field.",
        ),
    )
    op.drop_column("allocation_agreement", "quantity_not_sold")

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "allocation_agreement",
        sa.Column(
            "quantity_not_sold",
            sa.INTEGER(),
            autoincrement=False,
            nullable=False,
            comment="Quantity of fuel not sold",
        ),
    )
    op.drop_column("allocation_agreement", "units")
    op.drop_column("allocation_agreement", "ci_fuel")
    op.drop_column("allocation_agreement", "transaction_parnter_phone")
    op.drop_column("allocation_agreement", "transaction_partner_email")
    # ### end Alembic commands ###
