"""allocation agreement update

Revision ID: 401c9ed94cdb
Revises: 2f1e766ef118
Create Date: 2024-08-19 17:57:56.717567

"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "401c9ed94cdb"
down_revision = "2f1e766ef118"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "allocation_agreement",
        sa.Column(
            "transaction_partner_email",
            sa.String(),
            nullable=False,
            comment="Transaction Partner email",
        ),
    )
    op.add_column(
        "allocation_agreement",
        sa.Column(
            "transaction_partner_phone",
            sa.String(),
            nullable=False,
            comment="Transaction Partner phone number",
        ),
    )
    op.add_column(
        "allocation_agreement",
        sa.Column(
            "ci_fuel",
            sa.Integer(),
            nullable=False,
            comment="The Carbon intesity of fuel",
        ),
    )
    op.add_column(
        "allocation_agreement",
        sa.Column(
            "units",
            sa.String(),
            nullable=False,
            comment="Units of the fuel quantity. Auto-selected, locked field.",
        ),
    )
    op.drop_column("allocation_agreement", "quantity_not_sold")
    op.add_column(
        "allocation_agreement",
        sa.Column(
            "allocation_transaction_type_id",
            sa.Integer(),
            nullable=False,
            comment="Foreign key to the transaction type",
        ),
    )
    op.drop_constraint(
        "allocation_agreement_transaction_type_id_fkey",
        "allocation_agreement",
        type_="foreignkey",
    )
    op.create_foreign_key(
        None,
        "allocation_agreement",
        "allocation_transaction_type",
        ["allocation_transaction_type_id"],
        ["allocation_transaction_type_id"],
    )
    op.drop_column("allocation_agreement", "transaction_type_id")

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "allocation_agreement",
        sa.Column(
            "transaction_type_id",
            sa.INTEGER(),
            autoincrement=False,
            nullable=False,
            comment="Foreign key to the transaction type",
        ),
    )
    op.drop_constraint(None, "allocation_agreement", type_="foreignkey")
    op.create_foreign_key(
        "allocation_agreement_transaction_type_id_fkey",
        "allocation_agreement",
        "allocation_transaction_type",
        ["transaction_type_id"],
        ["allocation_transaction_type_id"],
    )
    op.drop_column("allocation_agreement", "allocation_transaction_type_id")
    op.add_column(
        "allocation_agreement",
        sa.Column(
            "quantity_not_sold",
            sa.INTEGER(),
            autoincrement=False,
            nullable=False,
            comment="Quantity of fuel not sold",
        ),
    )
    op.drop_column("allocation_agreement", "units")
    op.drop_column("allocation_agreement", "ci_fuel")
    op.drop_column("allocation_agreement", "transaction_partner_phone")
    op.drop_column("allocation_agreement", "transaction_partner_email")
    # ### end Alembic commands ###
