"""Add Default CI to Categories

Revision ID: 851e09cf8661
Revises: 5b374dd97469
Create Date: 2024-12-17 23:58:07.462215

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "851e09cf8661"
down_revision = "5b374dd97469"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "fuel_category",
        sa.Column(
            "default_carbon_intensity",
            sa.Numeric(precision=10, scale=2),
            nullable=True,
            comment="Default carbon intensity of the fuel category",
        ),
    )

    # Populate default values for existing records
    op.execute(
        """
        UPDATE "fuel_category" SET "default_carbon_intensity" = 88.83 WHERE "description" = 'Jet fuel';
        """
    )
    op.execute(
        """
        UPDATE "fuel_category" SET "default_carbon_intensity" = 100.21 WHERE "description" = 'Diesel';
        """
    )
    op.execute(
        """
        UPDATE "fuel_category" SET "default_carbon_intensity" = 93.67 WHERE "description" = 'Gasoline';
        """
    )

    # Now set the column to NOT NULL after populating defaults
    op.alter_column(
        "fuel_category",
        "default_carbon_intensity",
        existing_type=sa.Numeric(precision=10, scale=2),
        nullable=False,
    )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("fuel_category", "default_carbon_intensity")
    # ### end Alembic commands ###
