"""create co-ordinates column for address tables

Revision ID: a22832d8c8d3
Revises: 9c663ed10c09
Create Date: 2024-01-19 01:51:12.380148

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "a22832d8c8d3"
down_revision = "9c663ed10c09"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "organization_address",
        sa.Column("coordinates", postgresql.ARRAY(sa.Float()), nullable=True),
    )
    op.add_column(
        "organization_attorney_address",
        sa.Column("coordinates", postgresql.ARRAY(sa.Float()), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("organization_attorney_address", "coordinates")
    op.drop_column("organization_address", "coordinates")
    # ### end Alembic commands ###
