"""fuel code contact info

Revision ID: 2b64a18af91d
Revises: bb4f823e5aac
Create Date: 2024-06-03 20:34:47.139153

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "2b64a18af91d"
down_revision = "bb4f823e5aac"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "fuel_code",
        sa.Column(
            "contact_name",
            sa.String(length=500),
            nullable=True,
            comment="Contact name",
        ),
    )
    op.add_column(
        "fuel_code",
        sa.Column(
            "contact_email",
            sa.String(length=500),
            nullable=True,
            comment="Contact email",
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("fuel_code", "contact_email")
    op.drop_column("fuel_code", "contact_name")
    # ### end Alembic commands ###
