"""add additional transfer fields

Revision ID: a6ee4089ae80
Revises: 6c9e7dc84aa7
Create Date: 2024-02-07 00:33:36.114144

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "a6ee4089ae80"
down_revision = "6c9e7dc84aa7"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "transfer",
        sa.Column(
            "agreement_date",
            sa.DateTime(),
            nullable=True,
            comment="Agreement date of the transfer",
        ),
    )
    op.add_column(
        "transfer",
        sa.Column("quantity", sa.Integer(), nullable=True, comment="Quantity of units"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("transfer", "quantity")
    op.drop_column("transfer", "agreement_date")
    # ### end Alembic commands ###
