"""Use Numeric for 2 Decimal Columns

Revision ID: a731a32947dc
Revises: 4f25f8811872
Create Date: 2024-10-18 19:46:48.189455

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "a731a32947dc"
down_revision = "4f25f8811872"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "additional_carbon_intensity",
        "intensity",
        existing_type=sa.REAL(),
        type_=sa.Numeric(precision=10, scale=2),
        existing_nullable=False,
    )
    op.alter_column(
        "allocation_agreement",
        "ci_of_fuel",
        existing_type=sa.DOUBLE_PRECISION(precision=53),
        type_=sa.Numeric(precision=10, scale=2),
        existing_comment="The Carbon intesity of fuel",
        existing_nullable=False,
    )
    op.alter_column(
        "custom_fuel_type",
        "energy_density",
        existing_type=sa.REAL(),
        type_=sa.Numeric(precision=10, scale=2),
        existing_comment="Energy density of the fuel",
        existing_nullable=False,
    )
    op.alter_column(
        "energy_density",
        "density",
        existing_type=sa.REAL(),
        type_=sa.Numeric(precision=10, scale=2),
        existing_nullable=False,
    )
    op.alter_column(
        "energy_effectiveness_ratio",
        "ratio",
        existing_type=sa.REAL(),
        type_=sa.Float(precision=3, decimal_return_scale=2),
        existing_comment="Energy effectiveness ratio constant",
        existing_nullable=False,
    )
    op.alter_column(
        "fuel_export",
        "target_ci",
        existing_type=sa.DOUBLE_PRECISION(precision=53),
        type_=sa.Numeric(precision=10, scale=2),
        existing_comment="CI limit for the fuel supply",
        existing_nullable=True,
    )
    op.alter_column(
        "fuel_export",
        "ci_of_fuel",
        existing_type=sa.DOUBLE_PRECISION(precision=53),
        type_=sa.Numeric(precision=10, scale=2),
        existing_comment="CI of fuel for the fuel supply",
        existing_nullable=True,
    )
    op.alter_column(
        "fuel_export",
        "energy_density",
        existing_type=sa.DOUBLE_PRECISION(precision=53),
        type_=sa.Numeric(precision=10, scale=2),
        existing_comment="Energy density of the fuel supplied",
        existing_nullable=True,
    )
    op.alter_column(
        "fuel_export",
        "eer",
        existing_type=sa.DOUBLE_PRECISION(precision=53),
        type_=sa.Numeric(precision=10, scale=2),
        existing_comment="Energy effectiveness ratio of the fuel supplied",
        existing_nullable=True,
    )
    op.alter_column(
        "fuel_export",
        "energy",
        existing_type=sa.DOUBLE_PRECISION(precision=53),
        type_=sa.Numeric(precision=10, scale=2),
        existing_comment="Energy content of the fuel supplied",
        existing_nullable=True,
    )
    op.alter_column(
        "fuel_supply",
        "target_ci",
        existing_type=sa.DOUBLE_PRECISION(precision=53),
        type_=sa.Numeric(precision=10, scale=2),
        existing_comment="Target CI for the fuel supply",
        existing_nullable=True,
    )
    op.alter_column(
        "fuel_supply",
        "ci_of_fuel",
        existing_type=sa.DOUBLE_PRECISION(precision=53),
        type_=sa.Numeric(precision=10, scale=2),
        existing_comment="CI of fuel for the fuel supply",
        existing_nullable=True,
    )
    op.alter_column(
        "fuel_supply",
        "energy_density",
        existing_type=sa.DOUBLE_PRECISION(precision=53),
        type_=sa.Numeric(precision=10, scale=2),
        existing_comment="Energy density of the fuel supplied",
        existing_nullable=True,
    )
    op.alter_column(
        "fuel_supply",
        "eer",
        existing_type=sa.DOUBLE_PRECISION(precision=53),
        type_=sa.Numeric(precision=10, scale=2),
        existing_comment="Energy effectiveness ratio of the fuel supplied",
        existing_nullable=True,
    )

    # First, round the values in the energy column
    op.execute("UPDATE fuel_supply SET energy = ROUND(energy)")
    op.alter_column(
        "fuel_supply",
        "energy",
        existing_type=sa.DOUBLE_PRECISION(precision=53),
        type_=sa.BigInteger(),
        existing_comment="Energy content of the fuel supplied",
        existing_nullable=True,
    )
    op.alter_column(
        "fuel_type",
        "default_carbon_intensity",
        existing_type=sa.REAL(),
        type_=sa.Numeric(precision=10, scale=2),
        existing_comment="Carbon intensities: default & prescribed (gCO2e/MJ)",
        existing_nullable=True,
    )
    op.alter_column(
        "target_carbon_intensity",
        "target_carbon_intensity",
        existing_type=sa.DOUBLE_PRECISION(precision=53),
        type_=sa.Numeric(precision=10, scale=2),
        existing_comment="Target Carbon Intensity (gCO2e/MJ)",
        existing_nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "target_carbon_intensity",
        "target_carbon_intensity",
        existing_type=sa.Numeric(precision=10, scale=2),
        type_=sa.DOUBLE_PRECISION(precision=53),
        existing_comment="Target Carbon Intensity (gCO2e/MJ)",
        existing_nullable=False,
    )
    op.alter_column(
        "fuel_type",
        "default_carbon_intensity",
        existing_type=sa.Numeric(precision=10, scale=2),
        type_=sa.REAL(),
        existing_comment="Carbon intensities: default & prescribed (gCO2e/MJ)",
        existing_nullable=True,
    )
    op.alter_column(
        "fuel_supply",
        "energy",
        existing_type=sa.Integer(),
        type_=sa.DOUBLE_PRECISION(precision=53),
        existing_comment="Energy content of the fuel supplied",
        existing_nullable=True,
    )
    op.alter_column(
        "fuel_supply",
        "eer",
        existing_type=sa.Numeric(precision=10, scale=2),
        type_=sa.DOUBLE_PRECISION(precision=53),
        existing_comment="Energy effectiveness ratio of the fuel supplied",
        existing_nullable=True,
    )
    op.alter_column(
        "fuel_supply",
        "energy_density",
        existing_type=sa.Numeric(precision=10, scale=2),
        type_=sa.DOUBLE_PRECISION(precision=53),
        existing_comment="Energy density of the fuel supplied",
        existing_nullable=True,
    )
    op.alter_column(
        "fuel_supply",
        "ci_of_fuel",
        existing_type=sa.Numeric(precision=10, scale=2),
        type_=sa.DOUBLE_PRECISION(precision=53),
        existing_comment="CI of fuel for the fuel supply",
        existing_nullable=True,
    )
    op.alter_column(
        "fuel_supply",
        "target_ci",
        existing_type=sa.Numeric(precision=10, scale=2),
        type_=sa.DOUBLE_PRECISION(precision=53),
        existing_comment="Target CI for the fuel supply",
        existing_nullable=True,
    )
    op.alter_column(
        "fuel_export",
        "energy",
        existing_type=sa.Numeric(precision=10, scale=2),
        type_=sa.DOUBLE_PRECISION(precision=53),
        existing_comment="Energy content of the fuel supplied",
        existing_nullable=True,
    )
    op.alter_column(
        "fuel_export",
        "eer",
        existing_type=sa.Numeric(precision=10, scale=2),
        type_=sa.DOUBLE_PRECISION(precision=53),
        existing_comment="Energy effectiveness ratio of the fuel supplied",
        existing_nullable=True,
    )
    op.alter_column(
        "fuel_export",
        "energy_density",
        existing_type=sa.Numeric(precision=10, scale=2),
        type_=sa.DOUBLE_PRECISION(precision=53),
        existing_comment="Energy density of the fuel supplied",
        existing_nullable=True,
    )
    op.alter_column(
        "fuel_export",
        "ci_of_fuel",
        existing_type=sa.Numeric(precision=10, scale=2),
        type_=sa.DOUBLE_PRECISION(precision=53),
        existing_comment="CI of fuel for the fuel supply",
        existing_nullable=True,
    )
    op.alter_column(
        "fuel_export",
        "target_ci",
        existing_type=sa.Numeric(precision=10, scale=2),
        type_=sa.DOUBLE_PRECISION(precision=53),
        existing_comment="CI limit for the fuel supply",
        existing_nullable=True,
    )
    op.alter_column(
        "energy_effectiveness_ratio",
        "ratio",
        existing_type=sa.Float(precision=3, decimal_return_scale=2),
        type_=sa.REAL(),
        existing_comment="Energy effectiveness ratio constant",
        existing_nullable=False,
    )
    op.alter_column(
        "energy_density",
        "density",
        existing_type=sa.Numeric(precision=10, scale=2),
        type_=sa.REAL(),
        existing_nullable=False,
    )
    op.drop_constraint(op.f("uq_document_document_id"), "document", type_="unique")
    op.alter_column(
        "custom_fuel_type",
        "energy_density",
        existing_type=sa.Numeric(precision=10, scale=2),
        type_=sa.REAL(),
        existing_comment="Energy density of the fuel",
        existing_nullable=False,
    )
    op.alter_column(
        "allocation_agreement",
        "ci_of_fuel",
        existing_type=sa.Numeric(precision=10, scale=2),
        type_=sa.DOUBLE_PRECISION(precision=53),
        existing_comment="The Carbon intesity of fuel",
        existing_nullable=False,
    )
    op.drop_constraint(
        op.f("uq_admin_adjustment_history_admin_adjustment_history_id"),
        "admin_adjustment_history",
        type_="unique",
    )
    op.drop_constraint(
        op.f("uq_admin_adjustment_admin_adjustment_id"),
        "admin_adjustment",
        type_="unique",
    )
    op.alter_column(
        "additional_carbon_intensity",
        "intensity",
        existing_type=sa.Numeric(precision=10, scale=2),
        type_=sa.REAL(),
        existing_nullable=False,
    )
    # ### end Alembic commands ###
