"""Finaly supply equipment model fix

Revision ID: d5e905d517ff
Revises: b29b8130f17e
Create Date: 2024-06-25 07:14:45.175747

"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "d5e905d517ff"
down_revision = "b29b8130f17e"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "final_supply_intended_use_association",
        sa.Column("final_supply_equipment_id", sa.Integer(), nullable=False),
        sa.Column("end_use_type_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["end_use_type_id"],
            ["end_use_type.end_use_type_id"],
        ),
        sa.ForeignKeyConstraint(
            ["final_supply_equipment_id"],
            ["final_supply_equipment.final_supply_equipment_id"],
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("final_supply_equipment_id", "end_use_type_id"),
    )
    op.drop_index(
        "ix_final_supply_equipment_intended_use_id", table_name="final_supply_equipment"
    )
    op.drop_constraint(
        "final_supply_equipment_intended_use_id_fkey",
        "final_supply_equipment",
        type_="foreignkey",
    )
    op.drop_column("final_supply_equipment", "intended_use_id")
    op.drop_index(
        "ix_target_carbon_intensity_compliance_period_id",
        table_name="target_carbon_intensity",
    )
    op.drop_index(
        "ix_target_carbon_intensity_fuel_category_id",
        table_name="target_carbon_intensity",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        "ix_target_carbon_intensity_fuel_category_id",
        "target_carbon_intensity",
        ["fuel_category_id"],
        unique=False,
    )
    op.create_index(
        "ix_target_carbon_intensity_compliance_period_id",
        "target_carbon_intensity",
        ["compliance_period_id"],
        unique=False,
    )
    op.add_column(
        "final_supply_equipment",
        sa.Column(
            "intended_use_id",
            sa.INTEGER(),
            autoincrement=False,
            nullable=False,
            comment="The foreign key referencing the end use type to represent intended use.",
        ),
    )
    op.create_foreign_key(
        "final_supply_equipment_intended_use_id_fkey",
        "final_supply_equipment",
        "end_use_type",
        ["intended_use_id"],
        ["end_use_type_id"],
    )
    op.create_index(
        "ix_final_supply_equipment_intended_use_id",
        "final_supply_equipment",
        ["intended_use_id"],
        unique=False,
    )
    op.drop_table("final_supply_intended_use_association")
    # ### end Alembic commands ###
