"""Add Versioning to Other Uses

Revision ID: 654858661ae7
Revises: b659816d0a86
Create Date: 2024-11-13 00:39:22.594912

"""

import uuid

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "654858661ae7"
down_revision = "b659816d0a86"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "other_uses",
        sa.Column(
            "group_uuid",
            sa.String(length=36),
            nullable=True,
            comment="UUID that groups all versions of a record series",
        ),
    )
    op.add_column(
        "other_uses",
        sa.Column(
            "version",
            sa.Integer(),
            nullable=False,
            server_default="0",
            comment="Version number of the record",
        ),
    )
    op.add_column(
        "other_uses",
        sa.Column(
            "user_type",
            postgresql.ENUM(
                "SUPPLIER", "GOVERNMENT", name="usertypeenum", create_type=False
            ),
            nullable=False,
            server_default=sa.text("'SUPPLIER'"),
            comment="Indicates whether the record was created/modified by a supplier or government user",
        ),
    )
    op.add_column(
        "other_uses",
        sa.Column(
            "action_type",
            postgresql.ENUM(
                "CREATE", "UPDATE", "DELETE", name="actiontypeenum", create_type=False
            ),
            server_default=sa.text("'CREATE'"),
            nullable=True,
            comment="Action type for this record",
        ),
    )

    #Update existing records with generated UUIDs
    connection = op.get_bind()

    # Update other_uses table
    fuel_exports = connection.execute(
        sa.text("SELECT other_uses_id FROM other_uses WHERE group_uuid IS NULL")
    ).fetchall()
    for export in fuel_exports:
        export_id = export[0]
        connection.execute(
            sa.text(
                "UPDATE other_uses SET group_uuid = :uuid WHERE other_uses_id = :export_id"
            ),
            {"uuid": str(uuid.uuid4()), "export_id": export_id},
        )

    #Alter the column to be non-nullable
    op.alter_column(
        "other_uses",
        "group_uuid",
        existing_type=sa.String(length=36),
        nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("other_uses", "action_type")
    op.drop_column("other_uses", "user_type")
    op.drop_column("other_uses", "version")
    op.drop_column("other_uses", "group_uuid")
    # ### end Alembic commands ###
