"""add price_per_unit column to transfer and transfer_history table.

Revision ID: 23ea1a75213c
Revises: 9c663ed10c09
Create Date: 2024-01-23 05:55:58.715360

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "23ea1a75213c"
down_revision = "9c663ed10c09"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "transfer",
        sa.Column(
            "price_per_unit",
            sa.NUMERIC(),
            autoincrement=False,
            nullable=True,
            comment="The fair market value of any consideration, in Canadian dollars, per validated credit being transferred.",
        ),
    )
    op.add_column(
        "transfer_history",
        sa.Column(
            "price_per_unit",
            sa.NUMERIC(),
            autoincrement=False,
            nullable=True,
            comment="The fair market value of any consideration, in Canadian dollars, per validated credit being transferred.",
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("transfer", "price_per_unit")
    op.drop_column("transfer_history", "price_per_unit")
    # ### end Alembic commands ###
