"""initial migration

Revision ID: b2b46ce7d6bc
Revises: 
Create Date: 2024-04-03 14:02:38.930909

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "b2b46ce7d6bc"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    sa.Enum(
        "Draft",
        "Deleted",
        "Sent",
        "Submitted",
        "Recommended",
        "Recorded",
        "Refused",
        "Declined",
        "Rescinded",
        name="transfer_type_enum",
    ).create(op.get_bind())
    sa.Enum("Record", "Refuse", name="transfer_recommendation_enum").create(
        op.get_bind()
    )
    sa.Enum(
        "Draft",
        "Recommended",
        "Approved",
        "Deleted",
        name="initiative_agreement_type_enum",
    ).create(op.get_bind())
    sa.Enum(
        "Draft", "Recommended", "Approved", "Deleted", name="admin_adjustment_type_enum"
    ).create(op.get_bind())
    sa.Enum(
        "CREDIT_TRANSFER_CREATED",
        "CREDIT_TRANSFER_SIGNED_1OF2",
        "CREDIT_TRANSFER_SIGNED_2OF2",
        "CREDIT_TRANSFER_PROPOSAL_REFUSED",
        "CREDIT_TRANSFER_PROPOSAL_ACCEPTED",
        "CREDIT_TRANSFER_RECOMMENDED_FOR_APPROVAL",
        "CREDIT_TRANSFER_RECOMMENDED_FOR_DECLINATION",
        "CREDIT_TRANSFER_DECLINED",
        "CREDIT_TRANSFER_APPROVED",
        "CREDIT_TRANSFER_RESCINDED",
        "CREDIT_TRANSFER_COMMENT",
        "CREDIT_TRANSFER_INTERNAL_COMMENT",
        "PVR_CREATED",
        "PVR_RECOMMENDED_FOR_APPROVAL",
        "PVR_RESCINDED",
        "PVR_PULLED_BACK",
        "PVR_DECLINED",
        "PVR_APPROVED",
        "PVR_COMMENT",
        "PVR_INTERNAL_COMMENT",
        "PVR_RETURNED_TO_ANALYST",
        "DOCUMENT_PENDING_SUBMISSION",
        "DOCUMENT_SUBMITTED",
        "DOCUMENT_SCAN_FAILED",
        "DOCUMENT_RECEIVED",
        "DOCUMENT_ARCHIVED",
        "COMPLIANCE_REPORT_DRAFT",
        "COMPLIANCE_REPORT_SUBMITTED",
        "COMPLIANCE_REPORT_RECOMMENDED_FOR_ACCEPTANCE_ANALYST",
        "COMPLIANCE_REPORT_RECOMMENDED_FOR_REJECTION_ANALYST",
        "COMPLIANCE_REPORT_RECOMMENDED_FOR_ACCEPTANCE_MANAGER",
        "COMPLIANCE_REPORT_RECOMMENDED_FOR_REJECTION_MANAGER",
        "COMPLIANCE_REPORT_ACCEPTED",
        "COMPLIANCE_REPORT_REJECTED",
        "COMPLIANCE_REPORT_REQUESTED_SUPPLEMENTAL",
        "EXCLUSION_REPORT_DRAFT",
        "EXCLUSION_REPORT_SUBMITTED",
        "EXCLUSION_REPORT_RECOMMENDED_FOR_ACCEPTANCE_ANALYST",
        "EXCLUSION_REPORT_RECOMMENDED_FOR_REJECTION_ANALYST",
        "EXCLUSION_REPORT_RECOMMENDED_FOR_ACCEPTANCE_MANAGER",
        "EXCLUSION_REPORT_RECOMMENDED_FOR_REJECTION_MANAGER",
        "EXCLUSION_REPORT_ACCEPTED",
        "EXCLUSION_REPORT_REJECTED",
        "EXCLUSION_REPORT_REQUESTED_SUPPLEMENTAL",
        name="notification_type_enum",
    ).create(op.get_bind())
    sa.Enum("EMAIL", "IN_APP", name="channel_enum").create(op.get_bind())
    sa.Enum("Director", "Analyst", name="audience_scope").create(op.get_bind())
    sa.Enum(
        "Adjustment", "Reserved", "Released", name="transaction_action_enum"
    ).create(op.get_bind())
    sa.Enum(
        "GOVERNMENT",
        "ADMINISTRATOR",
        "ANALYST",
        "COMPLIANCE_MANAGER",
        "DIRECTOR",
        "SUPPLIER",
        "MANAGE_USERS",
        "TRANSFER",
        "COMPLIANCE_REPORTING",
        "SIGNING_AUTHORITY",
        "READ_ONLY",
        name="role_enum",
    ).create(op.get_bind())
    sa.Enum(
        "Unregistered", "Registered", "Suspended", "Canceled", name="org_status_enum"
    ).create(op.get_bind())
    sa.Enum(
        "fuel_supplier",
        "electricity_supplier",
        "broker",
        "utilities",
        name="org_type_enum",
    ).create(op.get_bind())
    op.create_table(
        "admin_adjustment_status",
        sa.Column(
            "admin_adjustment_status_id",
            sa.Integer(),
            autoincrement=True,
            nullable=False,
        ),
        sa.Column(
            "status",
            postgresql.ENUM(
                "Draft",
                "Recommended",
                "Approved",
                "Deleted",
                name="admin_adjustment_type_enum",
                create_type=False,
            ),
            nullable=True,
            comment="Admin Adjustment Status",
        ),
        sa.Column(
            "create_date",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
            comment="Date and time (UTC) when the physical record was created in the database.",
        ),
        sa.Column(
            "update_date",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
            comment="Date and time (UTC) when the physical record was updated in the database. It will be the same as the create_date until the record is first updated after creation.",
        ),
        sa.Column(
            "create_user",
            sa.String(),
            nullable=True,
            comment="The user who created this record in the database.",
        ),
        sa.Column(
            "update_user",
            sa.String(),
            nullable=True,
            comment="The user who last updated this record in the database.",
        ),
        sa.Column(
            "display_order",
            sa.Integer(),
            nullable=True,
            comment="Relative rank in display sorting order",
        ),
        sa.PrimaryKeyConstraint("admin_adjustment_status_id"),
        comment="Represents a Admin Adjustment Status",
    )
    op.create_table(
        "comment",
        sa.Column(
            "comment_id",
            sa.Integer(),
            autoincrement=True,
            nullable=False,
            comment="Unique identifier for comment",
        ),
        sa.Column("comment", sa.String(length=500), nullable=True, comment="Comment"),
        sa.Column(
            "create_date",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
            comment="Date and time (UTC) when the physical record was created in the database.",
        ),
        sa.Column(
            "update_date",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
            comment="Date and time (UTC) when the physical record was updated in the database. It will be the same as the create_date until the record is first updated after creation.",
        ),
        sa.Column(
            "create_user",
            sa.String(),
            nullable=True,
            comment="The user who created this record in the database.",
        ),
        sa.Column(
            "update_user",
            sa.String(),
            nullable=True,
            comment="The user who last updated this record in the database.",
        ),
        sa.Column(
            "effective_date",
            sa.Date(),
            nullable=True,
            comment="The calendar date the value became valid.",
        ),
        sa.Column(
            "expiration_date",
            sa.Date(),
            nullable=True,
            comment="The calendar date the value is no longer valid.",
        ),
        sa.PrimaryKeyConstraint("comment_id"),
        sa.UniqueConstraint("comment_id"),
        comment="Comment for transaction",
    )
    op.create_table(
        "initiative_agreement_status",
        sa.Column(
            "initiative_agreement_status_id",
            sa.Integer(),
            autoincrement=True,
            nullable=False,
        ),
        sa.Column(
            "status",
            postgresql.ENUM(
                "Draft",
                "Recommended",
                "Approved",
                "Deleted",
                name="initiative_agreement_type_enum",
                create_type=False,
            ),
            nullable=True,
            comment="Initiative Agreement Status",
        ),
        sa.Column(
            "create_date",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
            comment="Date and time (UTC) when the physical record was created in the database.",
        ),
        sa.Column(
            "update_date",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
            comment="Date and time (UTC) when the physical record was updated in the database. It will be the same as the create_date until the record is first updated after creation.",
        ),
        sa.Column(
            "create_user",
            sa.String(),
            nullable=True,
            comment="The user who created this record in the database.",
        ),
        sa.Column(
            "update_user",
            sa.String(),
            nullable=True,
            comment="The user who last updated this record in the database.",
        ),
        sa.Column(
            "display_order",
            sa.Integer(),
            nullable=True,
            comment="Relative rank in display sorting order",
        ),
        sa.PrimaryKeyConstraint("initiative_agreement_status_id"),
        comment="Represents a InitiativeAgreement Status",
    )
    op.create_table(
        "internal_comment",
        sa.Column(
            "internal_comment_id",
            sa.Integer(),
            autoincrement=True,
            nullable=False,
            comment="Primary key, unique identifier for each internal comment.",
        ),
        sa.Column("comment", sa.Text(), nullable=True, comment="Text of the comment."),
        sa.Column(
            "audience_scope",
            postgresql.ENUM(
                "Director", "Analyst", name="audience_scope", create_type=False
            ),
            nullable=False,
            comment="Defines the audience scope for the comment, e.g., Director, Analyst.",
        ),
        sa.Column(
            "create_date",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
            comment="Date and time (UTC) when the physical record was created in the database.",
        ),
        sa.Column(
            "update_date",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
            comment="Date and time (UTC) when the physical record was updated in the database. It will be the same as the create_date until the record is first updated after creation.",
        ),
        sa.Column(
            "create_user",
            sa.String(),
            nullable=True,
            comment="The user who created this record in the database.",
        ),
        sa.Column(
            "update_user",
            sa.String(),
            nullable=True,
            comment="The user who last updated this record in the database.",
        ),
        sa.PrimaryKeyConstraint("internal_comment_id"),
        sa.UniqueConstraint("internal_comment_id"),
        comment="Stores internal comments with scope and related metadata.",
    )
    op.create_table(
        "notification_channel",
        sa.Column(
            "notification_channel_id", sa.Integer(), autoincrement=True, nullable=False
        ),
        sa.Column(
            "channel_name",
            postgresql.ENUM("EMAIL", "IN_APP", name="channel_enum", create_type=False),
            nullable=False,
        ),
        sa.Column("enabled", sa.Boolean(), nullable=True),
        sa.Column("subscribe_by_default", sa.Boolean(), nullable=True),
        sa.Column(
            "create_date",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
            comment="Date and time (UTC) when the physical record was created in the database.",
        ),
        sa.Column(
            "update_date",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
            comment="Date and time (UTC) when the physical record was updated in the database. It will be the same as the create_date until the record is first updated after creation.",
        ),
        sa.Column(
            "create_user",
            sa.String(),
            nullable=True,
            comment="The user who created this record in the database.",
        ),
        sa.Column(
            "update_user",
            sa.String(),
            nullable=True,
            comment="The user who last updated this record in the database.",
        ),
        sa.PrimaryKeyConstraint("notification_channel_id"),
        comment="Tracks the state and defaults for communication channels",
    )
    op.create_table(
        "notification_type",
        sa.Column(
            "notification_type_id", sa.Integer(), autoincrement=True, nullable=False
        ),
        sa.Column(
            "name",
            postgresql.ENUM(
                "CREDIT_TRANSFER_CREATED",
                "CREDIT_TRANSFER_SIGNED_1OF2",
                "CREDIT_TRANSFER_SIGNED_2OF2",
                "CREDIT_TRANSFER_PROPOSAL_REFUSED",
                "CREDIT_TRANSFER_PROPOSAL_ACCEPTED",
                "CREDIT_TRANSFER_RECOMMENDED_FOR_APPROVAL",
                "CREDIT_TRANSFER_RECOMMENDED_FOR_DECLINATION",
                "CREDIT_TRANSFER_DECLINED",
                "CREDIT_TRANSFER_APPROVED",
                "CREDIT_TRANSFER_RESCINDED",
                "CREDIT_TRANSFER_COMMENT",
                "CREDIT_TRANSFER_INTERNAL_COMMENT",
                "PVR_CREATED",
                "PVR_RECOMMENDED_FOR_APPROVAL",
                "PVR_RESCINDED",
                "PVR_PULLED_BACK",
                "PVR_DECLINED",
                "PVR_APPROVED",
                "PVR_COMMENT",
                "PVR_INTERNAL_COMMENT",
                "PVR_RETURNED_TO_ANALYST",
                "DOCUMENT_PENDING_SUBMISSION",
                "DOCUMENT_SUBMITTED",
                "DOCUMENT_SCAN_FAILED",
                "DOCUMENT_RECEIVED",
                "DOCUMENT_ARCHIVED",
                "COMPLIANCE_REPORT_DRAFT",
                "COMPLIANCE_REPORT_SUBMITTED",
                "COMPLIANCE_REPORT_RECOMMENDED_FOR_ACCEPTANCE_ANALYST",
                "COMPLIANCE_REPORT_RECOMMENDED_FOR_REJECTION_ANALYST",
                "COMPLIANCE_REPORT_RECOMMENDED_FOR_ACCEPTANCE_MANAGER",
                "COMPLIANCE_REPORT_RECOMMENDED_FOR_REJECTION_MANAGER",
                "COMPLIANCE_REPORT_ACCEPTED",
                "COMPLIANCE_REPORT_REJECTED",
                "COMPLIANCE_REPORT_REQUESTED_SUPPLEMENTAL",
                "EXCLUSION_REPORT_DRAFT",
                "EXCLUSION_REPORT_SUBMITTED",
                "EXCLUSION_REPORT_RECOMMENDED_FOR_ACCEPTANCE_ANALYST",
                "EXCLUSION_REPORT_RECOMMENDED_FOR_REJECTION_ANALYST",
                "EXCLUSION_REPORT_RECOMMENDED_FOR_ACCEPTANCE_MANAGER",
                "EXCLUSION_REPORT_RECOMMENDED_FOR_REJECTION_MANAGER",
                "EXCLUSION_REPORT_ACCEPTED",
                "EXCLUSION_REPORT_REJECTED",
                "EXCLUSION_REPORT_REQUESTED_SUPPLEMENTAL",
                name="notification_type_enum",
                create_type=False,
            ),
            nullable=False,
        ),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("email_content", sa.Text(), nullable=True),
        sa.Column(
            "create_date",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
            comment="Date and time (UTC) when the physical record was created in the database.",
        ),
        sa.Column(
            "update_date",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
            comment="Date and time (UTC) when the physical record was updated in the database. It will be the same as the create_date until the record is first updated after creation.",
        ),
        sa.Column(
            "create_user",
            sa.String(),
            nullable=True,
            comment="The user who created this record in the database.",
        ),
        sa.Column(
            "update_user",
            sa.String(),
            nullable=True,
            comment="The user who last updated this record in the database.",
        ),
        sa.PrimaryKeyConstraint("notification_type_id"),
        comment="Represents a Notification type",
    )
    op.create_table(
        "organization_address",
        sa.Column(
            "organization_address_id", sa.Integer(), autoincrement=True, nullable=False
        ),
        sa.Column(
            "name", sa.String(length=500), nullable=True, comment="Organization name"
        ),
        sa.Column("street_address", sa.String(length=500), nullable=True),
        sa.Column("address_other", sa.String(length=100), nullable=True),
        sa.Column("city", sa.String(length=100), nullable=True),
        sa.Column("province_state", sa.String(length=50), nullable=True),
        sa.Column("country", sa.String(length=100), nullable=True),
        sa.Column("postalCode_zipCode", sa.String(length=10), nullable=True),
        sa.Column(
            "create_date",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
            comment="Date and time (UTC) when the physical record was created in the database.",
        ),
        sa.Column(
            "update_date",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
            comment="Date and time (UTC) when the physical record was updated in the database. It will be the same as the create_date until the record is first updated after creation.",
        ),
        sa.Column(
            "create_user",
            sa.String(),
            nullable=True,
            comment="The user who created this record in the database.",
        ),
        sa.Column(
            "update_user",
            sa.String(),
            nullable=True,
            comment="The user who last updated this record in the database.",
        ),
        sa.Column(
            "effective_date",
            sa.Date(),
            nullable=True,
            comment="The calendar date the value became valid.",
        ),
        sa.Column(
            "expiration_date",
            sa.Date(),
            nullable=True,
            comment="The calendar date the value is no longer valid.",
        ),
        sa.PrimaryKeyConstraint("organization_address_id"),
        comment="Represents an organization's address.",
    )
    op.create_table(
        "organization_attorney_address",
        sa.Column(
            "organization_attorney_address_id",
            sa.Integer(),
            autoincrement=True,
            nullable=False,
        ),
        sa.Column(
            "name",
            sa.String(length=500),
            nullable=True,
            comment="Attorney's Organization name",
        ),
        sa.Column("street_address", sa.String(length=500), nullable=True),
        sa.Column("address_other", sa.String(length=100), nullable=True),
        sa.Column("city", sa.String(length=100), nullable=True),
        sa.Column("province_state", sa.String(length=50), nullable=True),
        sa.Column("country", sa.String(length=100), nullable=True),
        sa.Column("postalCode_zipCode", sa.String(length=10), nullable=True),
        sa.Column(
            "create_date",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
            comment="Date and time (UTC) when the physical record was created in the database.",
        ),
        sa.Column(
            "update_date",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
            comment="Date and time (UTC) when the physical record was updated in the database. It will be the same as the create_date until the record is first updated after creation.",
        ),
        sa.Column(
            "create_user",
            sa.String(),
            nullable=True,
            comment="The user who created this record in the database.",
        ),
        sa.Column(
            "update_user",
            sa.String(),
            nullable=True,
            comment="The user who last updated this record in the database.",
        ),
        sa.Column(
            "effective_date",
            sa.Date(),
            nullable=True,
            comment="The calendar date the value became valid.",
        ),
        sa.Column(
            "expiration_date",
            sa.Date(),
            nullable=True,
            comment="The calendar date the value is no longer valid.",
        ),
        sa.PrimaryKeyConstraint("organization_attorney_address_id"),
        comment="Represents an organization attorney's address.",
    )
    op.create_table(
        "organization_status",
        sa.Column(
            "organization_status_id",
            sa.Integer(),
            autoincrement=True,
            nullable=False,
            comment="Unique identifier for the organization",
        ),
        sa.Column(
            "status",
            postgresql.ENUM(
                "Unregistered",
                "Registered",
                "Suspended",
                "Canceled",
                name="org_status_enum",
                create_type=False,
            ),
            nullable=True,
            comment="Organization's status",
        ),
        sa.Column(
            "description",
            sa.String(length=500),
            nullable=True,
            comment="Organization description",
        ),
        sa.Column(
            "create_date",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
            comment="Date and time (UTC) when the physical record was created in the database.",
        ),
        sa.Column(
            "update_date",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
            comment="Date and time (UTC) when the physical record was updated in the database. It will be the same as the create_date until the record is first updated after creation.",
        ),
        sa.Column(
            "create_user",
            sa.String(),
            nullable=True,
            comment="The user who created this record in the database.",
        ),
        sa.Column(
            "update_user",
            sa.String(),
            nullable=True,
            comment="The user who last updated this record in the database.",
        ),
        sa.Column(
            "display_order",
            sa.Integer(),
            nullable=True,
            comment="Relative rank in display sorting order",
        ),
        sa.PrimaryKeyConstraint("organization_status_id"),
        comment="Contains list of organization type",
    )
    op.create_table(
        "organization_type",
        sa.Column(
            "organization_type_id",
            sa.Integer(),
            autoincrement=True,
            nullable=False,
            comment="Unique identifier for the organization_type",
        ),
        sa.Column(
            "org_type",
            postgresql.ENUM(
                "fuel_supplier",
                "electricity_supplier",
                "broker",
                "utilities",
                name="org_type_enum",
                create_type=False,
            ),
            nullable=True,
            comment="Organization's Types",
        ),
        sa.Column(
            "description",
            sa.String(length=500),
            nullable=True,
            comment="Organization Types",
        ),
        sa.Column(
            "create_date",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
            comment="Date and time (UTC) when the physical record was created in the database.",
        ),
        sa.Column(
            "update_date",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
            comment="Date and time (UTC) when the physical record was updated in the database. It will be the same as the create_date until the record is first updated after creation.",
        ),
        sa.Column(
            "create_user",
            sa.String(),
            nullable=True,
            comment="The user who created this record in the database.",
        ),
        sa.Column(
            "update_user",
            sa.String(),
            nullable=True,
            comment="The user who last updated this record in the database.",
        ),
        sa.Column(
            "display_order",
            sa.Integer(),
            nullable=True,
            comment="Relative rank in display sorting order",
        ),
        sa.PrimaryKeyConstraint("organization_type_id"),
        comment="Represents a Organization types",
    )
    op.create_table(
        "role",
        sa.Column("role_id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column(
            "name",
            postgresql.ENUM(
                "GOVERNMENT",
                "ADMINISTRATOR",
                "ANALYST",
                "COMPLIANCE_MANAGER",
                "DIRECTOR",
                "SUPPLIER",
                "MANAGE_USERS",
                "TRANSFER",
                "COMPLIANCE_REPORTING",
                "SIGNING_AUTHORITY",
                "READ_ONLY",
                name="role_enum",
                create_type=False,
            ),
            nullable=False,
            comment="Role code. Natural key. Used internally. eg Admin, GovUser, GovDirector, etc",
        ),
        sa.Column(
            "description",
            sa.String(length=1000),
            nullable=True,
            comment="Descriptive text explaining this role. This is what's shown to the user.",
        ),
        sa.Column(
            "is_government_role",
            sa.Boolean(),
            nullable=True,
            comment="Flag. True if this is a government role (eg. Analyst, Administrator)",
        ),
        sa.Column(
            "display_order",
            sa.Integer(),
            nullable=True,
            comment="Relative rank in display sorting order",
        ),
        sa.Column(
            "create_date",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
            comment="Date and time (UTC) when the physical record was created in the database.",
        ),
        sa.Column(
            "update_date",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
            comment="Date and time (UTC) when the physical record was updated in the database. It will be the same as the create_date until the record is first updated after creation.",
        ),
        sa.Column(
            "create_user",
            sa.String(),
            nullable=True,
            comment="The user who created this record in the database.",
        ),
        sa.Column(
            "update_user",
            sa.String(),
            nullable=True,
            comment="The user who last updated this record in the database.",
        ),
        sa.PrimaryKeyConstraint("role_id"),
        sa.UniqueConstraint("name"),
        sa.UniqueConstraint("name"),
        comment="To hold all the available roles and  their descriptions.",
    )
    op.create_table(
        "transfer_category",
        sa.Column(
            "transfer_category_id",
            sa.Integer(),
            autoincrement=True,
            nullable=False,
            comment="Unique identifier for the transfer category",
        ),
        sa.Column(
            "category",
            sa.String(length=500),
            nullable=True,
            comment="Transfer category",
        ),
        sa.Column(
            "create_date",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
            comment="Date and time (UTC) when the physical record was created in the database.",
        ),
        sa.Column(
            "update_date",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
            comment="Date and time (UTC) when the physical record was updated in the database. It will be the same as the create_date until the record is first updated after creation.",
        ),
        sa.Column(
            "create_user",
            sa.String(),
            nullable=True,
            comment="The user who created this record in the database.",
        ),
        sa.Column(
            "update_user",
            sa.String(),
            nullable=True,
            comment="The user who last updated this record in the database.",
        ),
        sa.Column(
            "effective_date",
            sa.Date(),
            nullable=True,
            comment="The calendar date the value became valid.",
        ),
        sa.Column(
            "expiration_date",
            sa.Date(),
            nullable=True,
            comment="The calendar date the value is no longer valid.",
        ),
        sa.PrimaryKeyConstraint("transfer_category_id"),
        sa.UniqueConstraint("transfer_category_id"),
        comment="Transfer Category",
    )
    op.create_table(
        "transfer_status",
        sa.Column(
            "transfer_status_id", sa.Integer(), autoincrement=True, nullable=False
        ),
        sa.Column(
            "status",
            postgresql.ENUM(
                "Draft",
                "Deleted",
                "Sent",
                "Submitted",
                "Recommended",
                "Recorded",
                "Refused",
                "Declined",
                "Rescinded",
                name="transfer_type_enum",
                create_type=False,
            ),
            nullable=True,
            comment="Transfer Status",
        ),
        sa.Column(
            "create_date",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
            comment="Date and time (UTC) when the physical record was created in the database.",
        ),
        sa.Column(
            "update_date",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
            comment="Date and time (UTC) when the physical record was updated in the database. It will be the same as the create_date until the record is first updated after creation.",
        ),
        sa.Column(
            "create_user",
            sa.String(),
            nullable=True,
            comment="The user who created this record in the database.",
        ),
        sa.Column(
            "update_user",
            sa.String(),
            nullable=True,
            comment="The user who last updated this record in the database.",
        ),
        sa.Column(
            "display_order",
            sa.Integer(),
            nullable=True,
            comment="Relative rank in display sorting order",
        ),
        sa.PrimaryKeyConstraint("transfer_status_id"),
        comment="Represents a Transfer Status",
    )
    op.create_table(
        "user_login_history",
        sa.Column("user_login_history_id", sa.Integer(), nullable=False),
        sa.Column(
            "keycloak_email",
            sa.String(),
            nullable=False,
            comment="Keycloak email address to associate on first login.",
        ),
        sa.Column(
            "external_username",
            sa.String(length=150),
            nullable=True,
            comment="BCeID or IDIR username",
        ),
        sa.Column(
            "keycloak_user_id",
            sa.String(length=150),
            nullable=True,
            comment="This is the unique id returned from Keycloak and is the main mapping key between the LCFS user and the Keycloak user. The identity provider type will be appended as a suffix after an @ symbol. For ex. asdf1234@bceidbasic or asdf1234@idir",
        ),
        sa.Column(
            "is_login_successful",
            sa.Boolean(),
            nullable=True,
            comment="True if this login attempt was successful, false on failure.",
        ),
        sa.Column(
            "login_error_message",
            sa.String(length=500),
            nullable=True,
            comment="Error text on unsuccessful login attempt.",
        ),
        sa.Column(
            "create_date",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
            comment="Date and time (UTC) when the physical record was created in the database.",
        ),
        sa.Column(
            "update_date",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
            comment="Date and time (UTC) when the physical record was updated in the database. It will be the same as the create_date until the record is first updated after creation.",
        ),
        sa.PrimaryKeyConstraint("user_login_history_id"),
        comment="Keeps track of all user login attempts",
    )
    op.create_table(
        "organization",
        sa.Column(
            "organization_id",
            sa.Integer(),
            autoincrement=True,
            nullable=False,
            comment="Unique identifier for the organization",
        ),
        sa.Column(
            "name",
            sa.String(length=500),
            nullable=True,
            comment="Organization's legal name",
        ),
        sa.Column(
            "operating_name",
            sa.String(length=500),
            nullable=True,
            comment="Organization's Operating name",
        ),
        sa.Column(
            "email",
            sa.String(length=255),
            nullable=True,
            comment="Organization's email address",
        ),
        sa.Column(
            "phone",
            sa.String(length=50),
            nullable=True,
            comment="Organization's phone number",
        ),
        sa.Column(
            "edrms_record",
            sa.String(length=100),
            nullable=True,
            comment="Organization's EDRMS record number",
        ),
        sa.Column("organization_status_id", sa.Integer(), nullable=True),
        sa.Column(
            "organization_type_id",
            sa.Integer(),
            nullable=True,
            comment="Organization's type",
        ),
        sa.Column("organization_address_id", sa.Integer(), nullable=True),
        sa.Column("organization_attorney_address_id", sa.Integer(), nullable=True),
        sa.Column(
            "create_date",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
            comment="Date and time (UTC) when the physical record was created in the database.",
        ),
        sa.Column(
            "update_date",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
            comment="Date and time (UTC) when the physical record was updated in the database. It will be the same as the create_date until the record is first updated after creation.",
        ),
        sa.Column(
            "create_user",
            sa.String(),
            nullable=True,
            comment="The user who created this record in the database.",
        ),
        sa.Column(
            "update_user",
            sa.String(),
            nullable=True,
            comment="The user who last updated this record in the database.",
        ),
        sa.Column(
            "effective_date",
            sa.Date(),
            nullable=True,
            comment="The calendar date the value became valid.",
        ),
        sa.Column(
            "expiration_date",
            sa.Date(),
            nullable=True,
            comment="The calendar date the value is no longer valid.",
        ),
        sa.ForeignKeyConstraint(
            ["organization_address_id"],
            ["organization_address.organization_address_id"],
        ),
        sa.ForeignKeyConstraint(
            ["organization_attorney_address_id"],
            ["organization_attorney_address.organization_attorney_address_id"],
        ),
        sa.ForeignKeyConstraint(
            ["organization_status_id"],
            ["organization_status.organization_status_id"],
        ),
        sa.ForeignKeyConstraint(
            ["organization_type_id"],
            ["organization_type.organization_type_id"],
        ),
        sa.PrimaryKeyConstraint("organization_id"),
        comment="Contains a list of all of the recognized Part 3 fuel suppliers, both past and present, as well as an entry for the government which is also considered an organization.",
    )
    op.create_table(
        "transaction",
        sa.Column(
            "transaction_id",
            sa.Integer(),
            autoincrement=True,
            nullable=False,
            comment="Unique identifier for the transactions",
        ),
        sa.Column(
            "compliance_units",
            sa.BigInteger(),
            nullable=True,
            comment="Compliance Units",
        ),
        sa.Column("organization_id", sa.Integer(), nullable=True),
        sa.Column(
            "transaction_action",
            postgresql.ENUM(
                "Adjustment",
                "Reserved",
                "Released",
                name="transaction_action_enum",
                create_type=False,
            ),
            nullable=True,
            comment="Action type for the transaction, e.g., Adjustment, Reserved, or Released.",
        ),
        sa.Column(
            "create_date",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
            comment="Date and time (UTC) when the physical record was created in the database.",
        ),
        sa.Column(
            "update_date",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
            comment="Date and time (UTC) when the physical record was updated in the database. It will be the same as the create_date until the record is first updated after creation.",
        ),
        sa.Column(
            "create_user",
            sa.String(),
            nullable=True,
            comment="The user who created this record in the database.",
        ),
        sa.Column(
            "update_user",
            sa.String(),
            nullable=True,
            comment="The user who last updated this record in the database.",
        ),
        sa.Column(
            "effective_date",
            sa.Date(),
            nullable=True,
            comment="The calendar date the value became valid.",
        ),
        sa.Column(
            "expiration_date",
            sa.Date(),
            nullable=True,
            comment="The calendar date the value is no longer valid.",
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organization.organization_id"],
        ),
        sa.PrimaryKeyConstraint("transaction_id"),
        sa.UniqueConstraint("transaction_id"),
        comment="Contains a list of all of the government to organization and Organization to Organization transaction.",
    )
    op.create_table(
        "user_profile",
        sa.Column("user_profile_id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column(
            "keycloak_user_id",
            sa.String(length=150),
            nullable=True,
            comment="Unique id returned from Keycloak",
        ),
        sa.Column(
            "keycloak_email",
            sa.String(length=255),
            nullable=True,
            comment="keycloak email address",
        ),
        sa.Column(
            "keycloak_username",
            sa.String(length=150),
            nullable=False,
            comment="keycloak Username",
        ),
        sa.Column(
            "email",
            sa.String(length=255),
            nullable=True,
            comment="Primary email address",
        ),
        sa.Column(
            "title", sa.String(length=100), nullable=True, comment="Professional Title"
        ),
        sa.Column(
            "phone", sa.String(length=50), nullable=True, comment="Primary phone number"
        ),
        sa.Column(
            "mobile_phone",
            sa.String(length=50),
            nullable=True,
            comment="Mobile phone number",
        ),
        sa.Column(
            "first_name", sa.String(length=100), nullable=True, comment="First name"
        ),
        sa.Column(
            "last_name", sa.String(length=100), nullable=True, comment="Last name"
        ),
        sa.Column(
            "is_active", sa.Boolean(), nullable=False, comment="Is the user active?"
        ),
        sa.Column("organization_id", sa.Integer(), nullable=True),
        sa.Column(
            "create_date",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
            comment="Date and time (UTC) when the physical record was created in the database.",
        ),
        sa.Column(
            "update_date",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
            comment="Date and time (UTC) when the physical record was updated in the database. It will be the same as the create_date until the record is first updated after creation.",
        ),
        sa.Column(
            "create_user",
            sa.String(),
            nullable=True,
            comment="The user who created this record in the database.",
        ),
        sa.Column(
            "update_user",
            sa.String(),
            nullable=True,
            comment="The user who last updated this record in the database.",
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organization.organization_id"],
        ),
        sa.PrimaryKeyConstraint("user_profile_id"),
        sa.UniqueConstraint("keycloak_username"),
        sa.UniqueConstraint("keycloak_username"),
        comment="Users who may access the application",
    )
    op.create_table(
        "admin_adjustment",
        sa.Column(
            "admin_adjustment_id",
            sa.Integer(),
            autoincrement=True,
            nullable=False,
            comment="Unique identifier for the admin_adjustment",
        ),
        sa.Column(
            "compliance_units",
            sa.BigInteger(),
            nullable=True,
            comment="Compliance Units",
        ),
        sa.Column(
            "transaction_effective_date",
            sa.DateTime(),
            nullable=True,
            comment="Transaction effective date",
        ),
        sa.Column("to_organization_id", sa.Integer(), nullable=True),
        sa.Column("transaction_id", sa.Integer(), nullable=True),
        sa.Column("comment_id", sa.Integer(), nullable=True),
        sa.Column("current_status_id", sa.Integer(), nullable=True),
        sa.Column(
            "create_date",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
            comment="Date and time (UTC) when the physical record was created in the database.",
        ),
        sa.Column(
            "update_date",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
            comment="Date and time (UTC) when the physical record was updated in the database. It will be the same as the create_date until the record is first updated after creation.",
        ),
        sa.Column(
            "create_user",
            sa.String(),
            nullable=True,
            comment="The user who created this record in the database.",
        ),
        sa.Column(
            "update_user",
            sa.String(),
            nullable=True,
            comment="The user who last updated this record in the database.",
        ),
        sa.Column(
            "effective_date",
            sa.Date(),
            nullable=True,
            comment="The calendar date the value became valid.",
        ),
        sa.Column(
            "expiration_date",
            sa.Date(),
            nullable=True,
            comment="The calendar date the value is no longer valid.",
        ),
        sa.ForeignKeyConstraint(
            ["comment_id"],
            ["comment.comment_id"],
        ),
        sa.ForeignKeyConstraint(
            ["current_status_id"],
            ["admin_adjustment_status.admin_adjustment_status_id"],
        ),
        sa.ForeignKeyConstraint(
            ["to_organization_id"],
            ["organization.organization_id"],
        ),
        sa.ForeignKeyConstraint(
            ["transaction_id"],
            ["transaction.transaction_id"],
        ),
        sa.PrimaryKeyConstraint("admin_adjustment_id"),
        sa.UniqueConstraint("admin_adjustment_id"),
        comment="Goverment to organization compliance units admin_adjustment",
    )
    op.create_table(
        "initiative_agreement",
        sa.Column(
            "initiative_agreement_id",
            sa.Integer(),
            autoincrement=True,
            nullable=False,
            comment="Unique identifier for the initiative_agreement",
        ),
        sa.Column(
            "compliance_units",
            sa.BigInteger(),
            nullable=True,
            comment="Compliance Units",
        ),
        sa.Column(
            "transaction_effective_date",
            sa.DateTime(),
            nullable=True,
            comment="Transaction effective date",
        ),
        sa.Column("to_organization_id", sa.Integer(), nullable=True),
        sa.Column("transaction_id", sa.Integer(), nullable=True),
        sa.Column("comment_id", sa.Integer(), nullable=True),
        sa.Column("current_status_id", sa.Integer(), nullable=True),
        sa.Column(
            "create_date",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
            comment="Date and time (UTC) when the physical record was created in the database.",
        ),
        sa.Column(
            "update_date",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
            comment="Date and time (UTC) when the physical record was updated in the database. It will be the same as the create_date until the record is first updated after creation.",
        ),
        sa.Column(
            "create_user",
            sa.String(),
            nullable=True,
            comment="The user who created this record in the database.",
        ),
        sa.Column(
            "update_user",
            sa.String(),
            nullable=True,
            comment="The user who last updated this record in the database.",
        ),
        sa.Column(
            "effective_date",
            sa.Date(),
            nullable=True,
            comment="The calendar date the value became valid.",
        ),
        sa.Column(
            "expiration_date",
            sa.Date(),
            nullable=True,
            comment="The calendar date the value is no longer valid.",
        ),
        sa.ForeignKeyConstraint(
            ["comment_id"],
            ["comment.comment_id"],
        ),
        sa.ForeignKeyConstraint(
            ["current_status_id"],
            ["initiative_agreement_status.initiative_agreement_status_id"],
        ),
        sa.ForeignKeyConstraint(
            ["to_organization_id"],
            ["organization.organization_id"],
        ),
        sa.ForeignKeyConstraint(
            ["transaction_id"],
            ["transaction.transaction_id"],
        ),
        sa.PrimaryKeyConstraint("initiative_agreement_id"),
        sa.UniqueConstraint("initiative_agreement_id"),
        comment="Goverment to organization compliance units initiative agreement",
    )
    op.create_table(
        "notification_channel_subscription",
        sa.Column(
            "notification_channel_subscription_id",
            sa.Integer(),
            autoincrement=True,
            nullable=False,
        ),
        sa.Column("is_enabled", sa.Boolean(), nullable=True),
        sa.Column("user_profile_id", sa.Integer(), nullable=True),
        sa.Column("notification_type_id", sa.Integer(), nullable=True),
        sa.Column("notification_channel_id", sa.Integer(), nullable=True),
        sa.Column(
            "create_date",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
            comment="Date and time (UTC) when the physical record was created in the database.",
        ),
        sa.Column(
            "update_date",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
            comment="Date and time (UTC) when the physical record was updated in the database. It will be the same as the create_date until the record is first updated after creation.",
        ),
        sa.Column(
            "create_user",
            sa.String(),
            nullable=True,
            comment="The user who created this record in the database.",
        ),
        sa.Column(
            "update_user",
            sa.String(),
            nullable=True,
            comment="The user who last updated this record in the database.",
        ),
        sa.ForeignKeyConstraint(
            ["notification_channel_id"],
            ["notification_channel.notification_channel_id"],
        ),
        sa.ForeignKeyConstraint(
            ["notification_type_id"],
            ["notification_type.notification_type_id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_profile_id"],
            ["user_profile.user_profile_id"],
        ),
        sa.PrimaryKeyConstraint("notification_channel_subscription_id"),
        comment="Represents a user's subscription to notification events",
    )
    op.create_table(
        "notification_message",
        sa.Column(
            "notification_message_id", sa.Integer(), autoincrement=True, nullable=False
        ),
        sa.Column("is_read", sa.Boolean(), nullable=True),
        sa.Column("is_warning", sa.Boolean(), nullable=True),
        sa.Column("is_error", sa.Boolean(), nullable=True),
        sa.Column("is_archived", sa.Boolean(), nullable=True),
        sa.Column("related_organization_id", sa.Integer(), nullable=True),
        sa.Column("origin_user_profile_id", sa.Integer(), nullable=True),
        sa.Column("related_user_profile_id", sa.Integer(), nullable=True),
        sa.Column("notification_type_id", sa.Integer(), nullable=True),
        sa.Column(
            "create_date",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
            comment="Date and time (UTC) when the physical record was created in the database.",
        ),
        sa.Column(
            "update_date",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
            comment="Date and time (UTC) when the physical record was updated in the database. It will be the same as the create_date until the record is first updated after creation.",
        ),
        sa.Column(
            "create_user",
            sa.String(),
            nullable=True,
            comment="The user who created this record in the database.",
        ),
        sa.Column(
            "update_user",
            sa.String(),
            nullable=True,
            comment="The user who last updated this record in the database.",
        ),
        sa.ForeignKeyConstraint(
            ["notification_type_id"],
            ["notification_type.notification_type_id"],
        ),
        sa.ForeignKeyConstraint(
            ["origin_user_profile_id"],
            ["user_profile.user_profile_id"],
        ),
        sa.ForeignKeyConstraint(
            ["related_organization_id"],
            ["organization.organization_id"],
        ),
        sa.ForeignKeyConstraint(
            ["related_user_profile_id"],
            ["user_profile.user_profile_id"],
        ),
        sa.PrimaryKeyConstraint("notification_message_id"),
        comment="Represents a notification message sent to an application user",
    )
    op.create_table(
        "transfer",
        sa.Column(
            "transfer_id",
            sa.Integer(),
            autoincrement=True,
            nullable=False,
            comment="Unique identifier for the org to org transfer record",
        ),
        sa.Column("from_organization_id", sa.Integer(), nullable=True),
        sa.Column("to_organization_id", sa.Integer(), nullable=True),
        sa.Column("from_transaction_id", sa.Integer(), nullable=True),
        sa.Column("to_transaction_id", sa.Integer(), nullable=True),
        sa.Column(
            "agreement_date",
            sa.DateTime(),
            nullable=True,
            comment="Agreement date of the transfer",
        ),
        sa.Column(
            "transaction_effective_date",
            sa.DateTime(),
            nullable=True,
            comment="transaction effective date",
        ),
        sa.Column(
            "price_per_unit", sa.Integer(), nullable=True, comment="Price per unit"
        ),
        sa.Column("quantity", sa.Integer(), nullable=True, comment="Quantity of units"),
        sa.Column(
            "from_org_comment",
            sa.String(length=1000),
            nullable=True,
            comment="Comment from the from-organization",
        ),
        sa.Column(
            "to_org_comment",
            sa.String(length=1000),
            nullable=True,
            comment="Comment from the to-organization",
        ),
        sa.Column(
            "gov_comment",
            sa.String(length=1500),
            nullable=True,
            comment="Comment from the government to organizations",
        ),
        sa.Column("transfer_category_id", sa.Integer(), nullable=True),
        sa.Column("current_status_id", sa.Integer(), nullable=True),
        sa.Column(
            "recommendation",
            postgresql.ENUM(
                "Record",
                "Refuse",
                name="transfer_recommendation_enum",
                create_type=False,
            ),
            nullable=True,
            comment="Analyst recommendation for the transfer.",
        ),
        sa.Column(
            "create_date",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
            comment="Date and time (UTC) when the physical record was created in the database.",
        ),
        sa.Column(
            "update_date",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
            comment="Date and time (UTC) when the physical record was updated in the database. It will be the same as the create_date until the record is first updated after creation.",
        ),
        sa.Column(
            "create_user",
            sa.String(),
            nullable=True,
            comment="The user who created this record in the database.",
        ),
        sa.Column(
            "update_user",
            sa.String(),
            nullable=True,
            comment="The user who last updated this record in the database.",
        ),
        sa.Column(
            "effective_date",
            sa.Date(),
            nullable=True,
            comment="The calendar date the value became valid.",
        ),
        sa.Column(
            "expiration_date",
            sa.Date(),
            nullable=True,
            comment="The calendar date the value is no longer valid.",
        ),
        sa.ForeignKeyConstraint(
            ["current_status_id"],
            ["transfer_status.transfer_status_id"],
        ),
        sa.ForeignKeyConstraint(
            ["from_organization_id"],
            ["organization.organization_id"],
        ),
        sa.ForeignKeyConstraint(
            ["from_transaction_id"],
            ["transaction.transaction_id"],
        ),
        sa.ForeignKeyConstraint(
            ["to_organization_id"],
            ["organization.organization_id"],
        ),
        sa.ForeignKeyConstraint(
            ["to_transaction_id"],
            ["transaction.transaction_id"],
        ),
        sa.ForeignKeyConstraint(
            ["transfer_category_id"],
            ["transfer_category.transfer_category_id"],
        ),
        sa.PrimaryKeyConstraint("transfer_id"),
        sa.UniqueConstraint("transfer_id"),
        comment="Records of tranfer from Organization to Organization",
    )
    op.create_table(
        "user_role",
        sa.Column(
            "user_role_id",
            sa.Integer(),
            autoincrement=True,
            nullable=False,
            comment="Unique ID for the user role",
        ),
        sa.Column(
            "user_profile_id",
            sa.Integer(),
            nullable=True,
            comment="Foreign key to user_profile",
        ),
        sa.Column(
            "role_id", sa.Integer(), nullable=True, comment="Foreign key to role"
        ),
        sa.Column(
            "create_date",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
            comment="Date and time (UTC) when the physical record was created in the database.",
        ),
        sa.Column(
            "update_date",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
            comment="Date and time (UTC) when the physical record was updated in the database. It will be the same as the create_date until the record is first updated after creation.",
        ),
        sa.Column(
            "create_user",
            sa.String(),
            nullable=True,
            comment="The user who created this record in the database.",
        ),
        sa.Column(
            "update_user",
            sa.String(),
            nullable=True,
            comment="The user who last updated this record in the database.",
        ),
        sa.ForeignKeyConstraint(
            ["role_id"],
            ["role.role_id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_profile_id"],
            ["user_profile.user_profile_id"],
        ),
        sa.PrimaryKeyConstraint("user_role_id"),
        sa.UniqueConstraint(
            "user_profile_id", "role_id", name="user_role_unique_constraint"
        ),
        comment="Contains the user and role relationships",
    )
    op.create_table(
        "admin_adjustment_history",
        sa.Column(
            "admin_adjustment_history_id",
            sa.Integer(),
            autoincrement=True,
            nullable=False,
            comment="Unique identifier for the admin_adjustment history record",
        ),
        sa.Column("admin_adjustment_id", sa.Integer(), nullable=True),
        sa.Column("admin_adjustment_status_id", sa.Integer(), nullable=True),
        sa.Column(
            "create_date",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
            comment="Date and time (UTC) when the physical record was created in the database.",
        ),
        sa.Column(
            "update_date",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
            comment="Date and time (UTC) when the physical record was updated in the database. It will be the same as the create_date until the record is first updated after creation.",
        ),
        sa.Column(
            "create_user",
            sa.String(),
            nullable=True,
            comment="The user who created this record in the database.",
        ),
        sa.Column(
            "update_user",
            sa.String(),
            nullable=True,
            comment="The user who last updated this record in the database.",
        ),
        sa.Column(
            "effective_date",
            sa.Date(),
            nullable=True,
            comment="The calendar date the value became valid.",
        ),
        sa.Column(
            "expiration_date",
            sa.Date(),
            nullable=True,
            comment="The calendar date the value is no longer valid.",
        ),
        sa.ForeignKeyConstraint(
            ["admin_adjustment_id"],
            ["admin_adjustment.admin_adjustment_id"],
        ),
        sa.ForeignKeyConstraint(
            ["admin_adjustment_status_id"],
            ["admin_adjustment_status.admin_adjustment_status_id"],
        ),
        sa.PrimaryKeyConstraint("admin_adjustment_history_id"),
        sa.UniqueConstraint("admin_adjustment_history_id"),
        comment="History record for admin_adjustment status change.",
    )
    op.create_table(
        "initiative_agreement_history",
        sa.Column(
            "initiative_agreement_history_id",
            sa.Integer(),
            autoincrement=True,
            nullable=False,
            comment="Unique identifier for the initiative agreement history record",
        ),
        sa.Column("initiative_agreement_id", sa.Integer(), nullable=True),
        sa.Column("initiative_agreement_status_id", sa.Integer(), nullable=True),
        sa.Column(
            "create_date",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
            comment="Date and time (UTC) when the physical record was created in the database.",
        ),
        sa.Column(
            "update_date",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
            comment="Date and time (UTC) when the physical record was updated in the database. It will be the same as the create_date until the record is first updated after creation.",
        ),
        sa.Column(
            "create_user",
            sa.String(),
            nullable=True,
            comment="The user who created this record in the database.",
        ),
        sa.Column(
            "update_user",
            sa.String(),
            nullable=True,
            comment="The user who last updated this record in the database.",
        ),
        sa.Column(
            "effective_date",
            sa.Date(),
            nullable=True,
            comment="The calendar date the value became valid.",
        ),
        sa.Column(
            "expiration_date",
            sa.Date(),
            nullable=True,
            comment="The calendar date the value is no longer valid.",
        ),
        sa.ForeignKeyConstraint(
            ["initiative_agreement_id"],
            ["initiative_agreement.initiative_agreement_id"],
        ),
        sa.ForeignKeyConstraint(
            ["initiative_agreement_status_id"],
            ["initiative_agreement_status.initiative_agreement_status_id"],
        ),
        sa.PrimaryKeyConstraint("initiative_agreement_history_id"),
        sa.UniqueConstraint("initiative_agreement_history_id"),
        comment="History record for initiative agreement status change.",
    )
    op.create_table(
        "initiative_agreement_internal_comment",
        sa.Column(
            "initiative_agreement_id",
            sa.Integer(),
            nullable=False,
            comment="Foreign key to initiative_agreement, part of the composite primary key.",
        ),
        sa.Column(
            "internal_comment_id",
            sa.Integer(),
            nullable=False,
            comment="Foreign key to internal_comment, part of the composite primary key.",
        ),
        sa.Column(
            "create_date",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
            comment="Date and time (UTC) when the physical record was created in the database.",
        ),
        sa.Column(
            "update_date",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
            comment="Date and time (UTC) when the physical record was updated in the database. It will be the same as the create_date until the record is first updated after creation.",
        ),
        sa.ForeignKeyConstraint(
            ["initiative_agreement_id"],
            ["initiative_agreement.initiative_agreement_id"],
        ),
        sa.ForeignKeyConstraint(
            ["internal_comment_id"],
            ["internal_comment.internal_comment_id"],
        ),
        sa.PrimaryKeyConstraint("initiative_agreement_id", "internal_comment_id"),
        comment="Associates internal comments with initiative agreements.",
    )
    op.create_table(
        "transfer_history",
        sa.Column(
            "transfer_history_id",
            sa.Integer(),
            autoincrement=True,
            nullable=False,
            comment="Unique identifier for the transfer history record",
        ),
        sa.Column("transfer_id", sa.Integer(), nullable=True),
        sa.Column("transfer_status_id", sa.Integer(), nullable=True),
        sa.Column(
            "user_profile_id",
            sa.Integer(),
            nullable=True,
            comment="Foreign key to user_profile",
        ),
        sa.Column(
            "create_date",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
            comment="Date and time (UTC) when the physical record was created in the database.",
        ),
        sa.Column(
            "update_date",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
            comment="Date and time (UTC) when the physical record was updated in the database. It will be the same as the create_date until the record is first updated after creation.",
        ),
        sa.Column(
            "create_user",
            sa.String(),
            nullable=True,
            comment="The user who created this record in the database.",
        ),
        sa.Column(
            "update_user",
            sa.String(),
            nullable=True,
            comment="The user who last updated this record in the database.",
        ),
        sa.Column(
            "effective_date",
            sa.Date(),
            nullable=True,
            comment="The calendar date the value became valid.",
        ),
        sa.Column(
            "expiration_date",
            sa.Date(),
            nullable=True,
            comment="The calendar date the value is no longer valid.",
        ),
        sa.ForeignKeyConstraint(
            ["transfer_id"],
            ["transfer.transfer_id"],
        ),
        sa.ForeignKeyConstraint(
            ["transfer_status_id"],
            ["transfer_status.transfer_status_id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_profile_id"],
            ["user_profile.user_profile_id"],
        ),
        sa.PrimaryKeyConstraint("transfer_history_id"),
        comment="Records the status changes of a transfer.",
    )
    op.create_table(
        "transfer_internal_comment",
        sa.Column(
            "transfer_id",
            sa.Integer(),
            nullable=False,
            comment="Foreign key to transfer, part of the composite primary key.",
        ),
        sa.Column(
            "internal_comment_id",
            sa.Integer(),
            nullable=False,
            comment="Foreign key to internal_comment, part of the composite primary key.",
        ),
        sa.Column(
            "create_date",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
            comment="Date and time (UTC) when the physical record was created in the database.",
        ),
        sa.Column(
            "update_date",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
            comment="Date and time (UTC) when the physical record was updated in the database. It will be the same as the create_date until the record is first updated after creation.",
        ),
        sa.ForeignKeyConstraint(
            ["internal_comment_id"],
            ["internal_comment.internal_comment_id"],
        ),
        sa.ForeignKeyConstraint(
            ["transfer_id"],
            ["transfer.transfer_id"],
        ),
        sa.PrimaryKeyConstraint("transfer_id", "internal_comment_id"),
        comment="Associates internal comments with transfers.",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("transfer_internal_comment")
    op.drop_table("transfer_history")
    op.drop_table("initiative_agreement_internal_comment")
    op.drop_table("initiative_agreement_history")
    op.drop_table("admin_adjustment_history")
    op.drop_table("user_role")
    op.drop_table("transfer")
    op.drop_table("notification_message")
    op.drop_table("notification_channel_subscription")
    op.drop_table("initiative_agreement")
    op.drop_table("admin_adjustment")
    op.drop_table("user_profile")
    op.drop_table("transaction")
    op.drop_table("organization")
    op.drop_table("user_login_history")
    op.drop_table("transfer_status")
    op.drop_table("transfer_category")
    op.drop_table("role")
    op.drop_table("organization_type")
    op.drop_table("organization_status")
    op.drop_table("organization_attorney_address")
    op.drop_table("organization_address")
    op.drop_table("notification_type")
    op.drop_table("notification_channel")
    op.drop_table("internal_comment")
    op.drop_table("initiative_agreement_status")
    op.drop_table("comment")
    op.drop_table("admin_adjustment_status")
    sa.Enum(
        "fuel_supplier",
        "electricity_supplier",
        "broker",
        "utilities",
        name="org_type_enum",
    ).drop(op.get_bind())
    sa.Enum(
        "Unregistered", "Registered", "Suspended", "Canceled", name="org_status_enum"
    ).drop(op.get_bind())
    sa.Enum(
        "GOVERNMENT",
        "ADMINISTRATOR",
        "ANALYST",
        "COMPLIANCE_MANAGER",
        "DIRECTOR",
        "SUPPLIER",
        "MANAGE_USERS",
        "TRANSFER",
        "COMPLIANCE_REPORTING",
        "SIGNING_AUTHORITY",
        "READ_ONLY",
        name="role_enum",
    ).drop(op.get_bind())
    sa.Enum("Adjustment", "Reserved", "Released", name="transaction_action_enum").drop(
        op.get_bind()
    )
    sa.Enum("Director", "Analyst", name="audience_scope").drop(op.get_bind())
    sa.Enum("EMAIL", "IN_APP", name="channel_enum").drop(op.get_bind())
    sa.Enum(
        "CREDIT_TRANSFER_CREATED",
        "CREDIT_TRANSFER_SIGNED_1OF2",
        "CREDIT_TRANSFER_SIGNED_2OF2",
        "CREDIT_TRANSFER_PROPOSAL_REFUSED",
        "CREDIT_TRANSFER_PROPOSAL_ACCEPTED",
        "CREDIT_TRANSFER_RECOMMENDED_FOR_APPROVAL",
        "CREDIT_TRANSFER_RECOMMENDED_FOR_DECLINATION",
        "CREDIT_TRANSFER_DECLINED",
        "CREDIT_TRANSFER_APPROVED",
        "CREDIT_TRANSFER_RESCINDED",
        "CREDIT_TRANSFER_COMMENT",
        "CREDIT_TRANSFER_INTERNAL_COMMENT",
        "PVR_CREATED",
        "PVR_RECOMMENDED_FOR_APPROVAL",
        "PVR_RESCINDED",
        "PVR_PULLED_BACK",
        "PVR_DECLINED",
        "PVR_APPROVED",
        "PVR_COMMENT",
        "PVR_INTERNAL_COMMENT",
        "PVR_RETURNED_TO_ANALYST",
        "DOCUMENT_PENDING_SUBMISSION",
        "DOCUMENT_SUBMITTED",
        "DOCUMENT_SCAN_FAILED",
        "DOCUMENT_RECEIVED",
        "DOCUMENT_ARCHIVED",
        "COMPLIANCE_REPORT_DRAFT",
        "COMPLIANCE_REPORT_SUBMITTED",
        "COMPLIANCE_REPORT_RECOMMENDED_FOR_ACCEPTANCE_ANALYST",
        "COMPLIANCE_REPORT_RECOMMENDED_FOR_REJECTION_ANALYST",
        "COMPLIANCE_REPORT_RECOMMENDED_FOR_ACCEPTANCE_MANAGER",
        "COMPLIANCE_REPORT_RECOMMENDED_FOR_REJECTION_MANAGER",
        "COMPLIANCE_REPORT_ACCEPTED",
        "COMPLIANCE_REPORT_REJECTED",
        "COMPLIANCE_REPORT_REQUESTED_SUPPLEMENTAL",
        "EXCLUSION_REPORT_DRAFT",
        "EXCLUSION_REPORT_SUBMITTED",
        "EXCLUSION_REPORT_RECOMMENDED_FOR_ACCEPTANCE_ANALYST",
        "EXCLUSION_REPORT_RECOMMENDED_FOR_REJECTION_ANALYST",
        "EXCLUSION_REPORT_RECOMMENDED_FOR_ACCEPTANCE_MANAGER",
        "EXCLUSION_REPORT_RECOMMENDED_FOR_REJECTION_MANAGER",
        "EXCLUSION_REPORT_ACCEPTED",
        "EXCLUSION_REPORT_REJECTED",
        "EXCLUSION_REPORT_REQUESTED_SUPPLEMENTAL",
        name="notification_type_enum",
    ).drop(op.get_bind())
    sa.Enum(
        "Draft", "Recommended", "Approved", "Deleted", name="admin_adjustment_type_enum"
    ).drop(op.get_bind())
    sa.Enum(
        "Draft",
        "Recommended",
        "Approved",
        "Deleted",
        name="initiative_agreement_type_enum",
    ).drop(op.get_bind())
    sa.Enum("Record", "Refuse", name="transfer_recommendation_enum").drop(op.get_bind())
    sa.Enum(
        "Draft",
        "Deleted",
        "Sent",
        "Submitted",
        "Recommended",
        "Recorded",
        "Refused",
        "Declined",
        "Rescinded",
        name="transfer_type_enum",
    ).drop(op.get_bind())
    # ### end Alembic commands ###
