"""Fuel code base view

Revision ID: fcba2790c890
Revises: a1b2c3d4e5f6
Create Date: 2025-06-24 12:02:17.315932

"""

from lcfs.db.dependencies import (
    execute_sql_sections,
    find_and_read_sql_file,
    parse_sql_sections,
)
from alembic_postgresql_enum import TableReference

revision = "fcba2790c890"
down_revision = "a1b2c3d4e5f6"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    """Recreate the v_compliance_report view from metabase.sql"""
    try:
        # Read the metabase.sql file
        content = find_and_read_sql_file(sqlFile="metabase.sql")
        sections = parse_sql_sections(content)

        # Execute only the "Fuel Code Base View" section
        execute_sql_sections(sections, ["Fuel Code Base View"])

    except Exception as e:
        print(f"Error recreating v_compliance_report view: {e}")


def downgrade() -> None:
    pass
