"""Link documents to AA and IA

Revision ID: 775db18a959a
Revises: e50534b604f2
Create Date: 2025-02-07 01:01:12.679938

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "775db18a959a"
down_revision = "e50534b604f2"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "admin_adjustment_document_association",
        sa.Column("admin_adjustment_id", sa.Integer(), nullable=False),
        sa.Column("document_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["admin_adjustment_id"],
            ["admin_adjustment.admin_adjustment_id"],
            name=op.f(
                "fk_admin_adjustment_document_association_admin_adjustment_id_admin_adjustment"
            ),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["document_id"],
            ["document.document_id"],
            name=op.f("fk_admin_adjustment_document_association_document_id_document"),
        ),
        sa.PrimaryKeyConstraint(
            "admin_adjustment_id",
            "document_id",
            name=op.f("pk_admin_adjustment_document_association"),
        ),
    )
    op.create_table(
        "initiative_agreement_document_association",
        sa.Column("initiative_agreement_id", sa.Integer(), nullable=False),
        sa.Column("document_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["document_id"],
            ["document.document_id"],
            name=op.f(
                "fk_initiative_agreement_document_association_document_id_document"
            ),
        ),
        sa.ForeignKeyConstraint(
            ["initiative_agreement_id"],
            ["initiative_agreement.initiative_agreement_id"],
            name=op.f(
                "fk_initiative_agreement_document_association_initiative_agreement_id_initiative_agreement"
            ),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint(
            "initiative_agreement_id",
            "document_id",
            name=op.f("pk_initiative_agreement_document_association"),
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("initiative_agreement_document_association")
    op.drop_table("admin_adjustment_document_association")
    # ### end Alembic commands ###
