"""Add Transaction trigger for CR

Revision ID: 66b4ae533e8d
Revises: 7f7b03241d7f
Create Date: 2025-01-27 19:01:02.908162

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "66b4ae533e8d"
down_revision = "7f7b03241d7f"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Triggers for mv_transaction_aggregate
    op.execute(
        """
        CREATE TRIGGER refresh_transaction_view_after_compliance_report
        AFTER INSERT OR UPDATE OR DELETE ON compliance_report
        FOR EACH STATEMENT EXECUTE FUNCTION refresh_transaction_aggregate();
        """
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    pass
