"""Add display names to history tables.

Revision ID: c306137b57ab
Revises: 98d79870df6b
Create Date: 2025-01-20 16:23:50.597769

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "c306137b57ab"
down_revision = "98d79870df6b"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "admin_adjustment_history",
        sa.Column(
            "display_name",
            sa.String(length=255),
            nullable=True,
            comment="Display name for the admin_adjustment history record",
        ),
    )
    op.add_column(
        "compliance_report_history",
        sa.Column(
            "display_name",
            sa.String(length=255),
            nullable=True,
            comment="Display name for the compliance report history",
        ),
    )
    op.add_column(
        "initiative_agreement_history",
        sa.Column(
            "display_name",
            sa.String(length=255),
            nullable=True,
            comment="Display name for the initiative agreement history record",
        ),
    )
    op.add_column(
        "transfer_history",
        sa.Column(
            "display_name",
            sa.String(length=255),
            nullable=True,
            comment="Display name for the transfer history record",
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("transfer_history", "display_name")
    op.drop_column("initiative_agreement_history", "display_name")
    op.drop_column("compliance_report_history", "display_name")
    op.drop_column("admin_adjustment_history", "display_name")
    # ### end Alembic commands ###
