"""Add TFRS Summary Columns

Revision ID: 98d79870df6b
Revises: 998929392c8b
Create Date: 2025-01-16 20:01:34.038941

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "98d79870df6b"
down_revision = "998929392c8b"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "compliance_report_summary",
        sa.Column("credits_offset_a", sa.Integer(), nullable=True),
    )
    op.add_column(
        "compliance_report_summary",
        sa.Column("credits_offset_b", sa.Integer(), nullable=True),
    )
    op.add_column(
        "compliance_report_summary",
        sa.Column("credits_offset_c", sa.Integer(), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("compliance_report_summary", "credits_offset_c")
    op.drop_column("compliance_report_summary", "credits_offset_b")
    op.drop_column("compliance_report_summary", "credits_offset_a")
    # ### end Alembic commands ###
