"""Add Beta Tester role

Revision ID: 5c3de27f158b
Revises: 54d55e878dad
Create Date: 2025-04-17 23:46:58.106919

"""

from alembic import op
from alembic_postgresql_enum import TableReference

# revision identifiers, used by Alembic.
revision = "5c3de27f158b"
down_revision = "54d55e878dad"
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.sync_enum_values(
        "public",
        "role_enum",
        [
            "GOVERNMENT",
            "ADMINISTRATOR",
            "ANALYST",
            "COMPLIANCE_MANAGER",
            "DIRECTOR",
            "SUPPLIER",
            "MANAGE_USERS",
            "TRANSFER",
            "COMPLIANCE_REPORTING",
            "SIGNING_AUTHORITY",
            "READ_ONLY",
            "BETA_TESTER",
        ],
        [TableReference(table_schema="public", table_name="role", column_name="name")],
        enum_values_to_rename=[],
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.sync_enum_values(
        "public",
        "role_enum",
        [
            "GOVERNMENT",
            "ADMINISTRATOR",
            "ANALYST",
            "COMPLIANCE_MANAGER",
            "DIRECTOR",
            "SUPPLIER",
            "MANAGE_USERS",
            "TRANSFER",
            "COMPLIANCE_REPORTING",
            "SIGNING_AUTHORITY",
            "READ_ONLY",
        ],
        [TableReference(table_schema="public", table_name="role", column_name="name")],
        enum_values_to_rename=[],
    )
