"""Add Organization Address Snapshot

Revision ID: c96f06a5b761
Revises: 9785f4cfa370
Create Date: 2025-01-21 18:17:10.292471

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "c96f06a5b761"
down_revision = "9785f4cfa370"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "compliance_report_organization_snapshot",
        sa.Column(
            "organization_snapshot_id",
            sa.Integer(),
            autoincrement=True,
            nullable=False,
            comment="Unique identifier for the organization",
        ),
        sa.Column("compliance_report_id", sa.Integer(), nullable=True),
        sa.Column(
            "name",
            sa.String(length=500),
            nullable=True,
            comment="Organization's legal name",
        ),
        sa.Column(
            "operating_name",
            sa.String(length=500),
            nullable=True,
            comment="Organization's Operating name",
        ),
        sa.Column(
            "email",
            sa.String(length=255),
            nullable=True,
            comment="Organization's email address",
        ),
        sa.Column(
            "phone",
            sa.String(length=50),
            nullable=True,
            comment="Organization's phone number",
        ),
        sa.Column(
            "bc_address",
            sa.String(length=500),
            nullable=True,
            comment="Organization's address in BC",
        ),
        sa.Column(
            "service_address",
            sa.String(length=500),
            nullable=True,
            comment="Organization's address for Postal Service",
        ),
        sa.Column(
            "is_edited",
            sa.Boolean(),
            nullable=False,
            comment="Organization's address for Postal Service",
        ),
        sa.Column(
            "create_date",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
            comment="Date and time (UTC) when the physical record was created in the database.",
        ),
        sa.Column(
            "update_date",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
            comment="Date and time (UTC) when the physical record was updated in the database. It will be the same as the create_date until the record is first updated after creation.",
        ),
        sa.Column(
            "create_user",
            sa.String(),
            nullable=True,
            comment="The user who created this record in the database.",
        ),
        sa.Column(
            "update_user",
            sa.String(),
            nullable=True,
            comment="The user who last updated this record in the database.",
        ),
        sa.ForeignKeyConstraint(
            ["compliance_report_id"],
            ["compliance_report.compliance_report_id"],
            name=op.f(
                "fk_compliance_report_organization_snapshot_compliance_report_id_compliance_report"
            ),
        ),
        sa.PrimaryKeyConstraint(
            "organization_snapshot_id",
            name=op.f("pk_compliance_report_organization_snapshot"),
        ),
        comment="Contains organization snapshots that are attached to each compliance report for audit purposes.",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("compliance_report_organization_snapshot")
    # ### end Alembic commands ###
