"""Add renewable to Fuel Types

Revision ID: 0576833c005d
Revises: ec826b9226df
Create Date: 2025-01-22 00:04:37.043142

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "0576833c005d"
down_revision = "ec826b9226df"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "fuel_type",
        sa.Column(
            "renewable",
            sa.Boolean(),
            server_default=sa.text("FALSE"),
            nullable=False,
            comment="Indicates whether the fuel should be categorized as renewable",
        ),
    )

    # Update specific fuel types to set renewable = TRUE
    op.execute(
        """
        UPDATE fuel_type
        SET renewable = TRUE
        WHERE fuel_type IN (
          'Renewable gasoline',
          'Ethanol',
          'Renewable naphtha',
          'Biodiesel',
          'HDRD',
          'Other diesel fuel',
          'Alternative jet fuel',
          'Other'
        )
        """
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("fuel_type", "renewable")
    # ### end Alembic commands ###
