"""Add 5 Decimals for TCI/Credits

Revision ID: 16e4ebc2d6a5
Revises: 9e1da9e38f20
Create Date: 2025-02-24 21:52:20.156769

"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy import text
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "16e4ebc2d6a5"
down_revision = "9e1da9e38f20"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "fuel_export",
        "compliance_units",
        existing_type=sa.INTEGER(),
        type_=sa.Numeric(precision=13, scale=5),
        existing_comment="Compliance units for the fuel supply",
        existing_nullable=True,
    )
    op.alter_column(
        "fuel_export",
        "target_ci",
        existing_type=sa.NUMERIC(precision=10, scale=2),
        type_=sa.Numeric(precision=13, scale=5),
        existing_comment="CI limit for the fuel supply",
        existing_nullable=True,
    )
    op.alter_column(
        "fuel_supply",
        "compliance_units",
        existing_type=sa.INTEGER(),
        type_=sa.Numeric(precision=13, scale=5),
        existing_comment="Compliance units",
        existing_nullable=True,
    )
    op.alter_column(
        "fuel_supply",
        "target_ci",
        existing_type=sa.NUMERIC(precision=10, scale=2),
        type_=sa.Numeric(precision=13, scale=5),
        existing_comment="Target Carbon Intensity",
        existing_nullable=True,
    )
    op.alter_column(
        "target_carbon_intensity",
        "target_carbon_intensity",
        existing_type=sa.NUMERIC(precision=10, scale=2),
        type_=sa.Numeric(precision=13, scale=5),
        existing_comment="Target Carbon Intensity (gCO2e/MJ)",
        existing_nullable=False,
    )

    # Insert Updated Values

    conn = op.get_bind()

    statements = [
        # -- DIESEL (fuel_category_id = 1)
        """
        UPDATE target_carbon_intensity
        SET target_carbon_intensity = 79.27920,
            reduction_target_percentage = 16.0,
            update_date = NOW()
        WHERE compliance_period_id = 15
          AND fuel_category_id = 1;
        """,
        """
        UPDATE target_carbon_intensity
        SET target_carbon_intensity = 77.10846,
            reduction_target_percentage = 18.3,
            update_date = NOW()
        WHERE compliance_period_id = 16
          AND fuel_category_id = 1;
        """,
        """
        UPDATE target_carbon_intensity
        SET target_carbon_intensity = 74.93772,
            reduction_target_percentage = 20.6,
            update_date = NOW()
        WHERE compliance_period_id = 17
          AND fuel_category_id = 1;
        """,
        """
        UPDATE target_carbon_intensity
        SET target_carbon_intensity = 72.67260,
            reduction_target_percentage = 23.0,
            update_date = NOW()
        WHERE compliance_period_id = 18
          AND fuel_category_id = 1;
        """,
        """
        UPDATE target_carbon_intensity
        SET target_carbon_intensity = 70.50186,
            reduction_target_percentage = 25.3,
            update_date = NOW()
        WHERE compliance_period_id = 19
          AND fuel_category_id = 1;
        """,
        """
        UPDATE target_carbon_intensity
        SET target_carbon_intensity = 68.23674,
            reduction_target_percentage = 27.7,
            update_date = NOW()
        WHERE compliance_period_id = 20
          AND fuel_category_id = 1;
        """,
        """
        UPDATE target_carbon_intensity
        SET target_carbon_intensity = 66.06600,
            reduction_target_percentage = 30.0,
            update_date = NOW()
        WHERE compliance_period_id = 21
          AND fuel_category_id = 1;
        """,
        # -- GASOLINE (fuel_category_id = 2)
        """
        UPDATE target_carbon_intensity
        SET target_carbon_intensity = 78.68280,
            reduction_target_percentage = 16.0,
            update_date = NOW()
        WHERE compliance_period_id = 15
          AND fuel_category_id = 2;
        """,
        """
        UPDATE target_carbon_intensity
        SET target_carbon_intensity = 76.52839,
            reduction_target_percentage = 18.3,
            update_date = NOW()
        WHERE compliance_period_id = 16
          AND fuel_category_id = 2;
        """,
        """
        UPDATE target_carbon_intensity
        SET target_carbon_intensity = 74.37398,
            reduction_target_percentage = 20.6,
            update_date = NOW()
        WHERE compliance_period_id = 17
          AND fuel_category_id = 2;
        """,
        """
        UPDATE target_carbon_intensity
        SET target_carbon_intensity = 72.12590,
            reduction_target_percentage = 23.0,
            update_date = NOW()
        WHERE compliance_period_id = 18
          AND fuel_category_id = 2;
        """,
        """
        UPDATE target_carbon_intensity
        SET target_carbon_intensity = 69.97149,
            reduction_target_percentage = 25.3,
            update_date = NOW()
        WHERE compliance_period_id = 19
          AND fuel_category_id = 2;
        """,
        """
        UPDATE target_carbon_intensity
        SET target_carbon_intensity = 67.72341,
            reduction_target_percentage = 27.7,
            update_date = NOW()
        WHERE compliance_period_id = 20
          AND fuel_category_id = 2;
        """,
        """
        UPDATE target_carbon_intensity
        SET target_carbon_intensity = 65.56900,
            reduction_target_percentage = 30.0,
            update_date = NOW()
        WHERE compliance_period_id = 21
          AND fuel_category_id = 2;
        """,
        # -- JET FUEL (fuel_category_id = 3)
        """
        UPDATE target_carbon_intensity
        SET target_carbon_intensity = 88.83000,
            reduction_target_percentage = 0.00,
            update_date = NOW()
        WHERE compliance_period_id = 15
          AND fuel_category_id = 3;
        """,
        """
        UPDATE target_carbon_intensity
        SET target_carbon_intensity = 88.83000,
            reduction_target_percentage = 0.00,
            update_date = NOW()
        WHERE compliance_period_id = 16
          AND fuel_category_id = 3;
        """,
        """
        UPDATE target_carbon_intensity
        SET target_carbon_intensity = 87.05340,
            reduction_target_percentage = 2.00,
            update_date = NOW()
        WHERE compliance_period_id = 17
          AND fuel_category_id = 3;
        """,
        """
        UPDATE target_carbon_intensity
        SET target_carbon_intensity = 85.27680,
            reduction_target_percentage = 4.00,
            update_date = NOW()
        WHERE compliance_period_id = 18
          AND fuel_category_id = 3;
        """,
        """
        UPDATE target_carbon_intensity
        SET target_carbon_intensity = 83.50020,
            reduction_target_percentage = 6.00,
            update_date = NOW()
        WHERE compliance_period_id = 19
          AND fuel_category_id = 3;
        """,
        """
        UPDATE target_carbon_intensity
        SET target_carbon_intensity = 81.72360,
            reduction_target_percentage = 8.00,
            update_date = NOW()
        WHERE compliance_period_id = 20
          AND fuel_category_id = 3;
        """,
        """
        UPDATE target_carbon_intensity
        SET target_carbon_intensity = 79.94700,
            reduction_target_percentage = 10.00,
            update_date = NOW()
        WHERE compliance_period_id = 21
          AND fuel_category_id = 3;
        """,
    ]

    # Execute each statement
    for stmt in statements:
        conn.execute(text(stmt))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "target_carbon_intensity",
        "target_carbon_intensity",
        existing_type=sa.Numeric(precision=13, scale=5),
        type_=sa.NUMERIC(precision=10, scale=2),
        existing_comment="Target Carbon Intensity (gCO2e/MJ)",
        existing_nullable=False,
    )
    op.alter_column(
        "fuel_supply",
        "target_ci",
        existing_type=sa.Numeric(precision=13, scale=5),
        type_=sa.NUMERIC(precision=10, scale=2),
        existing_comment="Target Carbon Intensity",
        existing_nullable=True,
    )
    op.alter_column(
        "fuel_supply",
        "compliance_units",
        existing_type=sa.Numeric(precision=13, scale=5),
        type_=sa.INTEGER(),
        existing_comment="Compliance units",
        existing_nullable=True,
    )
    op.alter_column(
        "fuel_export",
        "target_ci",
        existing_type=sa.Numeric(precision=13, scale=5),
        type_=sa.NUMERIC(precision=10, scale=2),
        existing_comment="CI limit for the fuel supply",
        existing_nullable=True,
    )
    op.alter_column(
        "fuel_export",
        "compliance_units",
        existing_type=sa.Numeric(precision=13, scale=5),
        type_=sa.INTEGER(),
        existing_comment="Compliance units for the fuel supply",
        existing_nullable=True,
    )
    # ### end Alembic commands ###
