---
kind: Template
apiVersion: template.openshift.io/v1
metadata:
  name: celery-bc
  creationTimestamp:
parameters:
  - name: VERSION
    displayName:
    description: image tag name for output
    required: true
  - name: GIT_URL
    displayName:
    description: tfrs repo
    required: true
  - name: GIT_REF
    displayName:
    description: tfrs repo ref
    required: true
objects:
  - apiVersion: image.openshift.io/v1
    kind: ImageStream
    metadata:
      annotations:
        description: Keeps track of changes in the celery image
      labels:
        shared: "true"
      creationTimestamp: null
      name: lcfs-celery
    spec:
      lookupPolicy:
        local: false
  - apiVersion: build.openshift.io/v1
    kind: BuildConfig
    metadata:
      name: lcfs-celery-${VERSION}
      creationTimestamp:
      annotations:
        description: Defines how to build the backend image in docker
    spec:
      output:
        to:
          kind: ImageStreamTag
          name: lcfs-celery:${VERSION}
      resources:
        requests:
          cpu: 50m
          memory: 800Mi
      source:
        contextDir: backend
        git:
          uri: ${GIT_URL}
          ref: ${GIT_REF}
        type: Git
      strategy:
        dockerStrategy:
          dockerfilePath: ./Dockerfile-celery.openshift
          pullSecret:
            name: artifacts-pull-default-gyszor
          forcePull: true
          noCache: true
        type: Docker
      triggers: []
