export const notificationTypes = {
  // BCEID
  BCEID__CR__DIRECTOR_ASSESSMENT: 'BCEID__CR__DIRECTOR_ASSESSMENT',
  BCEID__IA__DIRECTOR_APPROVAL: 'BCEID__IA__DIRECTOR_APPROVAL',
  BCEID__TR__DIRECTOR_DECISION: 'BCEID__TR__DIRECTOR_DECISION',
  BCEID__TR__PARTNER_ACTIONS: 'BCEID__TR__PARTNER_ACTIONS',

  // IDIR ANALYST
  IDIR_A__CR__DIRECTOR_DECISION: 'IDIR_A__CR__DIRECTOR_DECISION',
  IDIR_A__CR__MANAGER_RECOMMENDATION: 'IDIR_A__CR__MANAGER_RECOMMENDATION',
  IDIR_A__CR__SUBMITTED_FOR_REVIEW: 'IDIR_A__CR__SUBMITTED_FOR_REVIEW',
  IDIR_A__IA__RETURNED_TO_ANALYST: 'IDIR_A__IA__RETURNED_TO_ANALYST',
  IDIR_A__TR__DIRECTOR_RECORDED: 'IDIR_A__TR__DIRECTOR_RECORDED',
  IDIR_A__TR__RESCINDED_ACTION: 'IDIR_A__TR__RESCINDED_ACTION',
  IDIR_A__TR__SUBMITTED_FOR_REVIEW: 'IDIR_A__TR__SUBMITTED_FOR_REVIEW',

  // IDIR COMPLIANCE_MANAGER
  IDIR_CM__CR__ANALYST_RECOMMENDATION: 'IDIR_CM__CR__ANALYST_RECOMMENDATION',
  IDIR_CM__CR__DIRECTOR_ASSESSMENT: 'IDIR_CM__CR__DIRECTOR_ASSESSMENT',
  IDIR_CM__CR__SUBMITTED_FOR_REVIEW: 'IDIR_CM__CR__SUBMITTED_FOR_REVIEW',

  // IDIR DIRECTOR
  IDIR_D__CR__MANAGER_RECOMMENDATION: 'IDIR_D__CR__MANAGER_RECOMMENDATION',
  IDIR_D__IA__ANALYST_RECOMMENDATION: 'IDIR_D__IA__ANALYST_RECOMMENDATION',
  IDIR_D__TR__ANALYST_RECOMMENDATION: 'IDIR_D__TR__ANALYST_RECOMMENDATION'
}

export const notificationChannels = {
  EMAIL: 'EMAIL',
  IN_APP: 'IN_APP'
}
