export const notificationTypes = {
  // BCEID
  BCEID__COMPLIANCE_REPORT__DIRECTOR_ASSESSMENT:
    'BCEID__COMPLIANCE_REPORT__DIRECTOR_ASSESSMENT',
  BCEID__INITIATIVE_AGREEMENT__DIRECTOR_APPROVAL:
    'BCEID__INITIATIVE_AGREEMENT__DIRECTOR_APPROVAL',
  BCEID__TRANSFER__DIRECTOR_DECISION: 'BCEID__TRANSFER__DIRECTOR_DECISION',
  BCEID__TRANSFER__PARTNER_ACTIONS: 'BCEID__TRANSFER__PARTNER_ACTIONS',
  BCEID__CREDIT_MARKET__CREDITS_LISTED_FOR_SALE:
    'BCEID__CREDIT_MARKET__CREDITS_LISTED_FOR_SALE',
  BCEID__GOVERNMENT_NOTIFICATION: 'BCEID__GOVERNMENT_NOTIFICATION',

  // IDIR ANALYST
  IDIR_ANALYST__COMPLIANCE_REPORT__DIRECTOR_DECISION:
    'IDIR_ANALYST__COMPLIANCE_REPORT__DIRECTOR_DECISION',
  IDIR_ANALYST__COMPLIANCE_REPORT__MANAGER_RECOMMENDATION:
    'IDIR_ANALYST__COMPLIANCE_REPORT__MANAGER_RECOMMENDATION',
  IDIR_ANALYST__COMPLIANCE_REPORT__SUBMITTED_FOR_REVIEW:
    'IDIR_ANALYST__COMPLIANCE_REPORT__SUBMITTED_FOR_REVIEW',
  IDIR_ANALYST__INITIATIVE_AGREEMENT__RETURNED_TO_ANALYST:
    'IDIR_ANALYST__INITIATIVE_AGREEMENT__RETURNED_TO_ANALYST',
  IDIR_ANALYST__TRANSFER__DIRECTOR_RECORDED:
    'IDIR_ANALYST__TRANSFER__DIRECTOR_RECORDED',
  IDIR_ANALYST__TRANSFER__RESCINDED_ACTION:
    'IDIR_ANALYST__TRANSFER__RESCINDED_ACTION',
  IDIR_ANALYST__TRANSFER__SUBMITTED_FOR_REVIEW:
    'IDIR_ANALYST__TRANSFER__SUBMITTED_FOR_REVIEW',
  IDIR_ANALYST__FUEL_CODE__DIRECTOR_RETURNED:
    'IDIR_ANALYST__FUEL_CODE__DIRECTOR_RETURNED',
  IDIR_ANALYST__FUEL_CODE__DIRECTOR_APPROVAL:
    'IDIR_ANALYST__FUEL_CODE__DIRECTOR_APPROVAL',
  IDIR_ANALYST__GOVERNMENT_NOTIFICATION:
    'IDIR_ANALYST__GOVERNMENT_NOTIFICATION',

  // IDIR COMPLIANCE_MANAGER
  IDIR_COMPLIANCE_MANAGER__GOVERNMENT_NOTIFICATION:
    'IDIR_COMPLIANCE_MANAGER__GOVERNMENT_NOTIFICATION',
  IDIR_COMPLIANCE_MANAGER__COMPLIANCE_REPORT__ANALYST_RECOMMENDATION:
    'IDIR_COMPLIANCE_MANAGER__COMPLIANCE_REPORT__ANALYST_RECOMMENDATION',
  IDIR_COMPLIANCE_MANAGER__COMPLIANCE_REPORT__DIRECTOR_ASSESSMENT:
    'IDIR_COMPLIANCE_MANAGER__COMPLIANCE_REPORT__DIRECTOR_ASSESSMENT',
  IDIR_COMPLIANCE_MANAGER__COMPLIANCE_REPORT__SUBMITTED_FOR_REVIEW:
    'IDIR_COMPLIANCE_MANAGER__COMPLIANCE_REPORT__SUBMITTED_FOR_REVIEW',

  // IDIR DIRECTOR
  IDIR_DIRECTOR__COMPLIANCE_REPORT__MANAGER_RECOMMENDATION:
    'IDIR_DIRECTOR__COMPLIANCE_REPORT__MANAGER_RECOMMENDATION',
  IDIR_DIRECTOR__INITIATIVE_AGREEMENT__ANALYST_RECOMMENDATION:
    'IDIR_DIRECTOR__INITIATIVE_AGREEMENT__ANALYST_RECOMMENDATION',
  IDIR_DIRECTOR__TRANSFER__ANALYST_RECOMMENDATION:
    'IDIR_DIRECTOR__TRANSFER__ANALYST_RECOMMENDATION',
  IDIR_DIRECTOR__FUEL_CODE__ANALYST_RECOMMENDATION:
    'IDIR_DIRECTOR__FUEL_CODE__ANALYST_RECOMMENDATION',
  IDIR_DIRECTOR__GOVERNMENT_NOTIFICATION:
    'IDIR_DIRECTOR__GOVERNMENT_NOTIFICATION'
}

export const notificationChannels = {
  EMAIL: 'EMAIL',
  IN_APP: 'IN_APP'
}
