import structlog
from datetime import datetime
from sqlalchemy import select, func
from lcfs.db.models.fuel.FuelCode import FuelCode

logger = structlog.get_logger(__name__)


async def seed_test_fuel_codes(session):
    """
    Seeds the comprehensive fuel codes from actual test database into the database,
    if they do not already exist.

    Args:
        session: The database session for committing the new records.
    """

    # Define the fuel codes based on actual test database data
    fuel_codes_to_seed = [
        {
            "fuel_code_id": 1,
            "fuel_suffix": "100.0",
            "company": "Government of British Columbia",
            "carbon_intensity": 93.67,
            "effective_date": datetime(2024, 4, 1),
            "expiration_date": datetime(2027, 3, 31),
            "fuel_type_id": 1,
            "fuel_status_id": 2,  # Approved
            "prefix_id": 1,
            "contact_name": "John Doe",
            "contact_email": "john.doe@lcfs.com",
            "edrms": "edrms",
            "last_updated": datetime(2024, 4, 1),
            "application_date": datetime(2024, 3, 1),
            "feedstock": "Feedstock",
            "feedstock_location": "123 main street",
            "feedstock_misc": "misc data",
            "fuel_production_facility_city": "Vancouver",
            "fuel_production_facility_province_state": "British Columbia",
            "fuel_production_facility_country": "Canada",
            "former_company": "ABC Company",
            "notes": "notes",
        },
        {
            "fuel_code_id": 2,
            "fuel_suffix": "101.0",
            "company": "Government of British Columbia",
            "carbon_intensity": 94.71,
            "effective_date": datetime(2024, 4, 1),
            "expiration_date": datetime(2027, 3, 31),
            "fuel_type_id": 2,
            "fuel_status_id": 2,  # Approved
            "prefix_id": 1,
            "contact_name": "John Doe",
            "contact_email": "john.doe@lcfs.com",
            "edrms": "edrms",
            "last_updated": datetime(2024, 4, 1),
            "application_date": datetime(2024, 3, 1),
            "feedstock": "Feedstock",
            "feedstock_location": "123 main street",
            "feedstock_misc": "misc data",
            "fuel_production_facility_city": "Vancouver",
            "fuel_production_facility_province_state": "British Columbia",
            "fuel_production_facility_country": "Canada",
            "former_company": "ABC Company",
            "notes": "notes",
        },
        {
            "fuel_code_id": 3,
            "fuel_suffix": "102.0",
            "company": "Government of British Columbia",
            "carbon_intensity": 87.49,
            "effective_date": datetime(2024, 4, 1),
            "expiration_date": datetime(2027, 3, 31),
            "fuel_type_id": 4,
            "fuel_status_id": 2,  # Approved
            "prefix_id": 1,
            "contact_name": "John Doe",
            "contact_email": "john.doe@lcfs.com",
            "edrms": "edrms",
            "last_updated": datetime(2024, 4, 1),
            "application_date": datetime(2024, 3, 1),
            "feedstock": "Feedstock",
            "feedstock_location": "123 main street",
            "feedstock_misc": "misc data",
            "fuel_production_facility_city": "Vancouver",
            "fuel_production_facility_province_state": "British Columbia",
            "fuel_production_facility_country": "Canada",
            "former_company": "ABC Company",
            "notes": "notes",
        },
        {
            "fuel_code_id": 4,
            "fuel_suffix": "103.0",
            "company": "Government of British Columbia",
            "carbon_intensity": 88.83,
            "effective_date": datetime(2024, 4, 1),
            "expiration_date": datetime(2027, 3, 31),
            "fuel_type_id": 11,
            "fuel_status_id": 2,  # Approved
            "prefix_id": 1,
            "contact_name": "John Doe",
            "contact_email": "john.doe@lcfs.com",
            "edrms": "edrms",
            "last_updated": datetime(2024, 4, 1),
            "application_date": datetime(2024, 3, 1),
            "feedstock": "Feedstock",
            "feedstock_location": "123 main street",
            "feedstock_misc": "misc data",
            "fuel_production_facility_city": "Vancouver",
            "fuel_production_facility_province_state": "British Columbia",
            "fuel_production_facility_country": "Canada",
            "former_company": "ABC Company",
            "notes": "notes",
        },
        {
            "fuel_code_id": 5,
            "fuel_suffix": "104.0",
            "company": "Government of British Columbia",
            "carbon_intensity": 85.70,
            "effective_date": datetime(2024, 4, 1),
            "expiration_date": datetime(2027, 3, 31),
            "fuel_type_id": 14,
            "fuel_status_id": 2,  # Approved
            "prefix_id": 1,
            "contact_name": "John Doe",
            "contact_email": "john.doe@lcfs.com",
            "edrms": "edrms",
            "last_updated": datetime(2024, 4, 1),
            "application_date": datetime(2024, 3, 1),
            "feedstock": "Feedstock",
            "feedstock_location": "123 main street",
            "feedstock_misc": "misc data",
            "fuel_production_facility_city": "Vancouver",
            "fuel_production_facility_province_state": "British Columbia",
            "fuel_production_facility_country": "Canada",
            "former_company": "ABC Company",
            "notes": "notes",
        },
        {
            "fuel_code_id": 6,
            "fuel_suffix": "105.0",
            "company": "Government of British Columbia",
            "carbon_intensity": 88.83,
            "effective_date": datetime(2024, 4, 1),
            "expiration_date": datetime(2027, 3, 31),
            "fuel_type_id": 15,
            "fuel_status_id": 2,  # Approved
            "prefix_id": 1,
            "contact_name": "John Doe",
            "contact_email": "john.doe@lcfs.com",
            "edrms": "edrms",
            "last_updated": datetime(2024, 4, 1),
            "application_date": datetime(2024, 3, 1),
            "feedstock": "Feedstock",
            "feedstock_location": "123 main street",
            "feedstock_misc": "misc data",
            "fuel_production_facility_city": "Vancouver",
            "fuel_production_facility_province_state": "British Columbia",
            "fuel_production_facility_country": "Canada",
            "former_company": "ABC Company",
            "notes": "notes",
        },
        {
            "fuel_code_id": 7,
            "fuel_suffix": "266.2",
            "company": "FortisBC Energy Inc.",
            "carbon_intensity": 20.41,
            "effective_date": datetime(2024, 1, 2),
            "expiration_date": datetime(2026, 12, 31),
            "fuel_type_id": 2,
            "fuel_status_id": 2,  # Approved
            "prefix_id": 1,
            "contact_name": "John Doe",
            "contact_email": "john.doe@lcfs.com",
            "edrms": "edrms",
            "last_updated": datetime(2024, 1, 1),
            "application_date": datetime(2023, 12, 1),
            "feedstock": "Feedstock",
            "feedstock_location": "123 main street",
            "feedstock_misc": "misc data",
            "fuel_production_facility_city": "Vancouver",
            "fuel_production_facility_province_state": "British Columbia",
            "fuel_production_facility_country": "Canada",
            "former_company": "ABC Company",
            "notes": "notes",
        },
        {
            "fuel_code_id": 8,
            "fuel_suffix": "274.2",
            "company": "Paseo Cargill Energy",
            "carbon_intensity": -15.03,
            "effective_date": datetime(2024, 1, 25),
            "expiration_date": datetime(2027, 1, 24),
            "fuel_type_id": 1,
            "fuel_status_id": 2,  # Approved
            "prefix_id": 1,
            "contact_name": "John Doe",
            "contact_email": "john.doe@lcfs.com",
            "edrms": "edrms",
            "last_updated": datetime(2024, 1, 20),
            "application_date": datetime(2023, 12, 20),
            "feedstock": "Feedstock",
            "feedstock_location": "123 main street",
            "feedstock_misc": "misc data",
            "fuel_production_facility_city": "Vancouver",
            "fuel_production_facility_province_state": "British Columbia",
            "fuel_production_facility_country": "Canada",
            "former_company": "ABC Company",
            "notes": "notes",
        },
        {
            "fuel_code_id": 9,
            "fuel_suffix": "286.2",
            "company": "Bonanza Bioenergy",
            "carbon_intensity": 35.17,
            "effective_date": datetime(2023, 8, 1),
            "expiration_date": datetime(2026, 7, 31),
            "fuel_type_id": 4,
            "fuel_status_id": 2,  # Approved
            "prefix_id": 1,
            "contact_name": "John Doe",
            "contact_email": "john.doe@lcfs.com",
            "edrms": "edrms",
            "last_updated": datetime(2023, 7, 25),
            "application_date": datetime(2023, 6, 25),
            "feedstock": "Feedstock",
            "feedstock_location": "123 main street",
            "feedstock_misc": "misc data",
            "fuel_production_facility_city": "Vancouver",
            "fuel_production_facility_province_state": "British Columbia",
            "fuel_production_facility_country": "Canada",
            "former_company": "ABC Company",
            "notes": "notes",
        },
        {
            "fuel_code_id": 10,
            "fuel_suffix": "304.1",
            "company": "Shell Canada Products",
            "carbon_intensity": 15.80,
            "effective_date": datetime(2024, 5, 1),
            "expiration_date": datetime(2027, 4, 30),
            "fuel_type_id": 5,
            "fuel_status_id": 1,  # Draft
            "prefix_id": 1,
            "contact_name": "John Doe",
            "contact_email": "john.doe@lcfs.com",
            "edrms": "edrms",
            "last_updated": datetime(2024, 4, 25),
            "application_date": datetime(2024, 3, 25),
            "feedstock": "Feedstock",
            "feedstock_location": "123 main street",
            "feedstock_misc": "misc data",
            "fuel_production_facility_city": "Vancouver",
            "fuel_production_facility_province_state": "British Columbia",
            "fuel_production_facility_country": "Canada",
            "former_company": "ABC Company",
            "notes": "notes",
        },
        {
            "fuel_code_id": 11,
            "fuel_suffix": "317.2",
            "company": "REG Geismar, LLC",
            "carbon_intensity": 17.36,
            "effective_date": datetime(2024, 7, 1),
            "expiration_date": datetime(2027, 6, 30),
            "fuel_type_id": 5,
            "fuel_status_id": 2,  # Approved
            "prefix_id": 1,
            "contact_name": "John Doe",
            "contact_email": "john.doe@lcfs.com",
            "edrms": "edrms",
            "last_updated": datetime(2024, 6, 25),
            "application_date": datetime(2024, 5, 25),
            "feedstock": "Feedstock",
            "feedstock_location": "123 main street",
            "feedstock_misc": "misc data",
            "fuel_production_facility_city": "Vancouver",
            "fuel_production_facility_province_state": "British Columbia",
            "fuel_production_facility_country": "Canada",
            "former_company": "ABC Company",
            "notes": "notes",
        },
        {
            "fuel_code_id": 12,
            "fuel_suffix": "355.1",
            "company": "Parkland Fuel Corporation",
            "carbon_intensity": 22.50,
            "effective_date": datetime(2024, 3, 15),
            "expiration_date": datetime(2027, 3, 14),
            "fuel_type_id": 1,
            "fuel_status_id": 1,  # Draft
            "prefix_id": 1,
            "contact_name": "John Doe",
            "contact_email": "john.doe@lcfs.com",
            "edrms": "edrms",
            "last_updated": datetime(2024, 3, 10),
            "application_date": datetime(2024, 2, 10),
            "feedstock": "Feedstock",
            "feedstock_location": "123 main street",
            "feedstock_misc": "misc data",
            "fuel_production_facility_city": "Vancouver",
            "fuel_production_facility_province_state": "British Columbia",
            "fuel_production_facility_country": "Canada",
            "former_company": "ABC Company",
            "notes": "notes",
        },
        {
            "fuel_code_id": 13,
            "fuel_suffix": "356.1",
            "company": "Imperial Oil Limited",
            "carbon_intensity": 18.75,
            "effective_date": datetime(2024, 6, 1),
            "expiration_date": datetime(2027, 5, 31),
            "fuel_type_id": 2,
            "fuel_status_id": 1,  # Draft
            "prefix_id": 1,
            "contact_name": "John Doe",
            "contact_email": "john.doe@lcfs.com",
            "edrms": "edrms",
            "last_updated": datetime(2024, 5, 25),
            "application_date": datetime(2024, 4, 25),
            "feedstock": "Feedstock",
            "feedstock_location": "123 main street",
            "feedstock_misc": "misc data",
            "fuel_production_facility_city": "Vancouver",
            "fuel_production_facility_province_state": "British Columbia",
            "fuel_production_facility_country": "Canada",
            "former_company": "ABC Company",
            "notes": "notes",
        },
        {
            "fuel_code_id": 14,
            "fuel_suffix": "361.1",
            "company": "Suncor Energy Inc.",
            "carbon_intensity": 25.00,
            "effective_date": datetime(2024, 2, 1),
            "expiration_date": datetime(2027, 1, 31),
            "fuel_type_id": 4,
            "fuel_status_id": 2,  # Approved
            "prefix_id": 1,
            "contact_name": "John Doe",
            "contact_email": "john.doe@lcfs.com",
            "edrms": "edrms",
            "last_updated": datetime(2024, 1, 25),
            "application_date": datetime(2023, 12, 25),
            "feedstock": "Feedstock",
            "feedstock_location": "123 main street",
            "feedstock_misc": "misc data",
            "fuel_production_facility_city": "Vancouver",
            "fuel_production_facility_province_state": "British Columbia",
            "fuel_production_facility_country": "Canada",
            "former_company": "ABC Company",
            "notes": "notes",
        },
        {
            "fuel_code_id": 15,
            "fuel_suffix": "362.1",
            "company": "ADM Agri-Industries Company",
            "carbon_intensity": -1.00,
            "effective_date": datetime(2024, 1, 1),
            "expiration_date": datetime(2026, 12, 31),
            "fuel_type_id": 1,
            "fuel_status_id": 2,  # Approved
            "prefix_id": 1,
            "contact_name": "John Doe",
            "contact_email": "john.doe@lcfs.com",
            "edrms": "edrms",
            "last_updated": datetime(2023, 12, 20),
            "application_date": datetime(2023, 11, 15),
            "feedstock": "Feedstock",
            "feedstock_location": "123 main street",
            "feedstock_misc": "misc data",
            "fuel_production_facility_city": "Vancouver",
            "fuel_production_facility_province_state": "British Columbia",
            "fuel_production_facility_country": "Canada",
            "former_company": "ABC Company",
            "notes": "notes",
        },
        {
            "fuel_code_id": 16,
            "fuel_suffix": "405.1",
            "company": "Diamond Green Diesel LLC",
            "carbon_intensity": 20.37,
            "effective_date": datetime(2023, 10, 27),
            "expiration_date": datetime(2024, 10, 26),
            "fuel_type_id": 15,
            "fuel_status_id": 2,  # Approved
            "prefix_id": 1,
            "contact_name": "John Doe",
            "contact_email": "john.doe@lcfs.com",
            "edrms": "edrms",
            "last_updated": datetime(2023, 10, 20),
            "application_date": datetime(2023, 9, 20),
            "feedstock": "Feedstock",
            "feedstock_location": "123 main street",
            "feedstock_misc": "misc data",
            "fuel_production_facility_city": "Vancouver",
            "fuel_production_facility_province_state": "British Columbia",
            "fuel_production_facility_country": "Canada",
            "former_company": "ABC Company",
            "notes": "notes",
        },
        {
            "fuel_code_id": 17,
            "fuel_suffix": "423.1",
            "company": "Tidewater Renewables Ltd.",
            "carbon_intensity": 15.47,
            "effective_date": datetime(2024, 7, 1),
            "expiration_date": datetime(2025, 6, 30),
            "fuel_type_id": 5,
            "fuel_status_id": 2,  # Approved
            "prefix_id": 1,
            "contact_name": "John Doe",
            "contact_email": "john.doe@lcfs.com",
            "edrms": "edrms",
            "last_updated": datetime(2024, 6, 25),
            "application_date": datetime(2024, 5, 25),
            "feedstock": "Feedstock",
            "feedstock_location": "123 main street",
            "feedstock_misc": "misc data",
            "fuel_production_facility_city": "Vancouver",
            "fuel_production_facility_province_state": "British Columbia",
            "fuel_production_facility_country": "Canada",
            "former_company": "ABC Company",
            "notes": "notes",
        },
        {
            "fuel_code_id": 18,
            "fuel_suffix": "568.0",
            "company": "Montana Renewables LLC",
            "carbon_intensity": 40.37,
            "effective_date": datetime(2024, 3, 1),
            "expiration_date": datetime(2025, 2, 28),
            "fuel_type_id": 11,
            "fuel_status_id": 2,  # Approved
            "prefix_id": 1,
            "contact_name": "John Doe",
            "contact_email": "john.doe@lcfs.com",
            "edrms": "edrms",
            "last_updated": datetime(2024, 2, 25),
            "application_date": datetime(2024, 1, 25),
            "feedstock": "Feedstock",
            "feedstock_location": "123 main street",
            "feedstock_misc": "misc data",
            "fuel_production_facility_city": "Vancouver",
            "fuel_production_facility_province_state": "British Columbia",
            "fuel_production_facility_country": "Canada",
            "former_company": "ABC Company",
            "notes": "notes",
        },
        {
            "fuel_code_id": 19,
            "fuel_suffix": "595.0",
            "company": "Parkland Refining (BC)",
            "carbon_intensity": -9.52,
            "effective_date": datetime(2024, 1, 1),
            "expiration_date": datetime(2025, 6, 30),
            "fuel_type_id": 14,
            "fuel_status_id": 2,  # Approved
            "prefix_id": 1,
            "contact_name": "John Doe",
            "contact_email": "john.doe@lcfs.com",
            "edrms": "edrms",
            "last_updated": datetime(2023, 12, 20),
            "application_date": datetime(2023, 11, 15),
            "feedstock": "Feedstock",
            "feedstock_location": "123 main street",
            "feedstock_misc": "misc data",
            "fuel_production_facility_city": "Vancouver",
            "fuel_production_facility_province_state": "British Columbia",
            "fuel_production_facility_country": "Canada",
            "former_company": "ABC Company",
            "notes": "notes",
        },
    ]

    for fuel_code_data in fuel_codes_to_seed:
        # Check if the fuel code already exists
        existing_fuel_code = await session.execute(
            select(FuelCode).where(
                FuelCode.fuel_code_id == fuel_code_data["fuel_code_id"]
            )
        )
        if existing_fuel_code.scalar():
            logger.info(
                f"Fuel code with ID {fuel_code_data['fuel_code_id']} already exists, skipping."
            )
            continue

        # Create and add the new fuel code
        fuel_code = FuelCode(**fuel_code_data)
        session.add(fuel_code)

    await session.flush()
    logger.info(f"Seeded {len(fuel_codes_to_seed)} fuel codes.")
