import structlog
from sqlalchemy import select
from lcfs.db.models.user.UserProfile import UserProfile

logger = structlog.get_logger(__name__)


async def seed_test_user_profiles(session):
    """
    Seeds the user profiles into the database with comprehensive test data,
    if they do not already exist.

    Args:
        session: The database session for committing the new records.
    """

    # Define the user profiles to seed based on actual test database
    user_profiles_to_seed = [
        # Government users (2-6)
        {
            "user_profile_id": 2,
            "keycloak_email": "hamed.valiollahibayeki@gov.bc.ca",
            "keycloak_username": "HVALIOLL",
            "email": "hamed.valiollahibayeki@gov.bc.ca",
            "title": "Developer",
            "phone": "1234567890",
            "mobile_phone": "1234567890",
            "organization_id": None,
            "is_active": True,
            "first_name": "Hamed",
            "last_name": "Bayeki",
        },
        {
            "user_profile_id": 3,
            "keycloak_email": "kevin.hashimoto@gov.bc.ca",
            "keycloak_username": "KHASHIMO",
            "email": "kevin.hashimoto@gov.bc.ca",
            "title": "Developer",
            "phone": "1234567890",
            "mobile_phone": "1234567890",
            "organization_id": None,
            "is_active": True,
            "first_name": "Kevin",
            "last_name": "Hashimoto",
        },
        {
            "user_profile_id": 4,
            "keycloak_email": "prashanth.venkateshappa@gov.bc.ca",
            "keycloak_username": "PVENKATE",
            "email": "prashanth.venkateshappa@gov.bc.ca",
            "title": "Developer",
            "phone": "1234567890",
            "mobile_phone": "1234567890",
            "organization_id": None,
            "is_active": True,
            "first_name": "Prashanth",
            "last_name": "V",
        },
        {
            "user_profile_id": 5,
            "keycloak_email": "justin.lepitzki@gov.bc.ca",
            "keycloak_username": "JLEPITZ",
            "email": "justin.lepitzki@gov.bc.ca",
            "title": "Admin",
            "phone": "1234567890",
            "mobile_phone": "1234567890",
            "organization_id": None,
            "is_active": True,
            "first_name": "Justin",
            "last_name": "Lepitzki",
        },
        {
            "user_profile_id": 6,
            "keycloak_email": "lindsy.grunert@gov.bc.ca",
            "keycloak_username": "LGRUNERT",
            "email": "lindsy.grunert@gov.bc.ca",
            "title": "Admin",
            "phone": "1234567890",
            "mobile_phone": "1234567890",
            "organization_id": None,
            "is_active": True,
            "first_name": "Lindsy",
            "last_name": "Grunert",
        },
        # Organization users (7-16)
        {
            "user_profile_id": 7,
            "keycloak_email": "tfrs@gov.bc.ca",
            "keycloak_username": "tfs1",
            "email": "tfrs@gov.bc.ca",
            "title": "Supplier - Liquid",
            "phone": "(604) 567-8976",
            "mobile_phone": "1112223333",
            "organization_id": 1,
            "is_active": True,
            "first_name": "Jane",
            "last_name": "Doe",
        },
        {
            "user_profile_id": 8,
            "keycloak_email": "tfrs@gov.bc.ca",
            "keycloak_username": "tfs2",
            "email": "tfrs@gov.bc.ca",
            "title": "Allocator Rep - Fleet",
            "phone": "(778) 896-1198",
            "mobile_phone": "2223334444",
            "organization_id": 2,
            "is_active": True,
            "first_name": "John",
            "last_name": "Smith",
        },
        {
            "user_profile_id": 9,
            "keycloak_email": "tfrs@gov.bc.ca",
            "keycloak_username": "tfs3",
            "email": "tfrs@gov.bc.ca",
            "title": "Supplier - Biofuel",
            "phone": "(250) 765-9901",
            "mobile_phone": "3334445555",
            "organization_id": 3,
            "is_active": True,
            "first_name": "Alice",
            "last_name": "Woo",
        },
        {
            "user_profile_id": 10,
            "keycloak_email": "tfrs@gov.bc.ca",
            "keycloak_username": "tfs4",
            "email": "tfrs@gov.bc.ca",
            "title": "Supplier - Electricity, Liquid Fuel, Exporter",
            "phone": "(250) 555-1122",
            "mobile_phone": "4445556666",
            "organization_id": 4,
            "is_active": True,
            "first_name": "Bob",
            "last_name": "Lee",
        },
        {
            "user_profile_id": 11,
            "keycloak_email": "tfrs@gov.bc.ca",
            "keycloak_username": "tfs5",
            "email": "tfrs@gov.bc.ca",
            "title": "Analyst",
            "phone": "6667778888",
            "mobile_phone": "6667778888",
            "organization_id": 5,
            "is_active": True,
            "first_name": "David",
            "last_name": "Clark",
        },
        {
            "user_profile_id": 12,
            "keycloak_email": "tfrs@gov.bc.ca",
            "keycloak_username": "tfs6",
            "email": "tfrs@gov.bc.ca",
            "title": "Analyst",
            "phone": "8889990000",
            "mobile_phone": "8889990000",
            "organization_id": 6,
            "is_active": True,
            "first_name": "Frank",
            "last_name": "Wilson",
        },
        {
            "user_profile_id": 13,
            "keycloak_email": "tfrs@gov.bc.ca",
            "keycloak_username": "tfs7",
            "email": "tfrs@gov.bc.ca",
            "title": "Analyst",
            "phone": "0001112222",
            "mobile_phone": "0001112222",
            "organization_id": 7,
            "is_active": True,
            "first_name": "Bill",
            "last_name": "Teller",
        },
        {
            "user_profile_id": 14,
            "keycloak_email": "tfrs@gov.bc.ca",
            "keycloak_username": "tfs8",
            "email": "tfrs@gov.bc.ca",
            "title": "Analyst",
            "phone": "2223334445",
            "mobile_phone": "2223334445",
            "organization_id": 8,
            "is_active": True,
            "first_name": "James",
            "last_name": "Bell",
        },
        {
            "user_profile_id": 15,
            "keycloak_email": "tfrs@gov.bc.ca",
            "keycloak_username": "tfs9",
            "email": "tfrs@gov.bc.ca",
            "title": "Analyst",
            "phone": "4445556667",
            "mobile_phone": "4445556667",
            "organization_id": 9,
            "is_active": True,
            "first_name": "Leo",
            "last_name": "Martin",
        },
        {
            "user_profile_id": 16,
            "keycloak_email": "tfrs@gov.bc.ca",
            "keycloak_username": "tfs10",
            "email": "tfrs@gov.bc.ca",
            "title": "Analyst",
            "phone": "6667778889",
            "mobile_phone": "6667778889",
            "organization_id": 10,
            "is_active": True,
            "first_name": "Noah",
            "last_name": "Thomas",
        },
        # Government users (17-22)
        {
            "user_profile_id": 17,
            "keycloak_email": "kailee.douglas@gov.bc.ca",
            "keycloak_username": "KADOUGLA",
            "email": "kailee.douglas@gov.bc.ca",
            "title": "Admin",
            "phone": "1234567890",
            "mobile_phone": "1234567890",
            "organization_id": None,
            "is_active": True,
            "first_name": "Kailee",
            "last_name": "Douglas",
        },
        {
            "user_profile_id": 18,
            "keycloak_email": "alasdair.ring@gov.bc.ca",
            "keycloak_username": "AIRING",
            "email": "alasdair.ring@gov.bc.ca",
            "title": "Product Owner",
            "phone": "1234567890",
            "mobile_phone": "1234567890",
            "organization_id": None,
            "is_active": True,
            "first_name": "Al",
            "last_name": "Ring",
        },
        {
            "user_profile_id": 19,
            "keycloak_email": "rebekah.ford@gov.bc.ca",
            "keycloak_username": "RRFORD",
            "email": "rebekah.ford@gov.bc.ca",
            "title": "Scrum Master",
            "phone": "1234567890",
            "mobile_phone": "1234567890",
            "organization_id": None,
            "is_active": True,
            "first_name": "Rebekah",
            "last_name": "Ford",
        },
        {
            "user_profile_id": 20,
            "keycloak_email": "stuart.galloway@gov.bc.ca",
            "keycloak_username": "SGALLOWA",
            "email": "stuart.galloway@gov.bc.ca",
            "title": "Sr. UX Practitioner",
            "phone": "1234567890",
            "mobile_phone": "1234567890",
            "organization_id": None,
            "is_active": True,
            "first_name": "Stuart",
            "last_name": "Galloway",
        },
        {
            "user_profile_id": 21,
            "keycloak_email": "lcfstest@gov.bc.ca",
            "keycloak_username": "lcfstest",
            "email": "lcfstest@gov.bc.ca",
            "title": "Test Account",
            "phone": "1234567890",
            "mobile_phone": "1234567890",
            "organization_id": None,
            "is_active": True,
            "first_name": "LCFS_IDIR",
            "last_name": "TESTER",
        },
        {
            "user_profile_id": 22,
            "keycloak_email": "jackie.duys@gov.bc.ca",
            "keycloak_username": "jduys",
            "email": "jackie.duys@gov.bc.ca",
            "title": "Senior Service Designer",
            "phone": "1234567890",
            "mobile_phone": "1234567890",
            "organization_id": None,
            "is_active": True,
            "first_name": "Jackie",
            "last_name": "Duys",
        },
        # Government test users (23-54)
        {
            "user_profile_id": 23,
            "keycloak_email": "Alexander.LePage@gov.bc.ca",
            "keycloak_username": "ALEPAGE",
            "email": "Alexander.LePage@gov.bc.ca",
            "title": "Test User",
            "phone": "1234567890",
            "mobile_phone": "1234567890",
            "organization_id": None,
            "is_active": True,
            "first_name": "Alexander",
            "last_name": "LePage",
        },
        {
            "user_profile_id": 24,
            "keycloak_email": "arthur.wong@gov.bc.ca",
            "keycloak_username": "Artwong",
            "email": "arthur.wong@gov.bc.ca",
            "title": "Test User",
            "phone": "1234567890",
            "mobile_phone": "1234567890",
            "organization_id": None,
            "is_active": True,
            "first_name": "Arthur",
            "last_name": "Wong",
        },
        {
            "user_profile_id": 25,
            "keycloak_email": "Behzad.Bahtooi@gov.bc.ca",
            "keycloak_username": "BBAHTOOI",
            "email": "Behzad.Bahtooi@gov.bc.ca",
            "title": "Test User",
            "phone": "1234567890",
            "mobile_phone": "1234567890",
            "organization_id": None,
            "is_active": True,
            "first_name": "Behzad",
            "last_name": "Bahtooi",
        },
        {
            "user_profile_id": 26,
            "keycloak_email": "binaipal.gill@gov.bc.ca",
            "keycloak_username": "BINGILL",
            "email": "binaipal.gill@gov.bc.ca",
            "title": "Test User",
            "phone": "1234567890",
            "mobile_phone": "1234567890",
            "organization_id": None,
            "is_active": True,
            "first_name": "Binaipal",
            "last_name": "Gill",
        },
        {
            "user_profile_id": 27,
            "keycloak_email": "brodie.nicholls@gov.bc.ca",
            "keycloak_username": "BNICHOLL",
            "email": "brodie.nicholls@gov.bc.ca",
            "title": "Test User",
            "phone": "1234567890",
            "mobile_phone": "1234567890",
            "organization_id": None,
            "is_active": True,
            "first_name": "Brodie",
            "last_name": "Nicholls",
        },
        {
            "user_profile_id": 28,
            "keycloak_email": "christine.laycock@gov.bc.ca",
            "keycloak_username": "CLAYCOCK",
            "email": "christine.laycock@gov.bc.ca",
            "title": "Test User",
            "phone": "1234567890",
            "mobile_phone": "1234567890",
            "organization_id": None,
            "is_active": True,
            "first_name": "Christine",
            "last_name": "Laycock",
        },
        {
            "user_profile_id": 29,
            "keycloak_email": "Dianne.McGuire@gov.bc.ca",
            "keycloak_username": "Dmcguire",
            "email": "Dianne.McGuire@gov.bc.ca",
            "title": "Test User",
            "phone": "1234567890",
            "mobile_phone": "1234567890",
            "organization_id": None,
            "is_active": True,
            "first_name": "Dianne",
            "last_name": "McGuire",
        },
        {
            "user_profile_id": 30,
            "keycloak_email": "David.Zhang@gov.bc.ca",
            "keycloak_username": "DZHANG",
            "email": "David.Zhang@gov.bc.ca",
            "title": "Test User",
            "phone": "1234567890",
            "mobile_phone": "1234567890",
            "organization_id": None,
            "is_active": True,
            "first_name": "David",
            "last_name": "Zhang",
        },
        {
            "user_profile_id": 31,
            "keycloak_email": "Graham.Wheating@gov.bc.ca",
            "keycloak_username": "Gwheatin",
            "email": "Graham.Wheating@gov.bc.ca",
            "title": "Test User",
            "phone": "1234567890",
            "mobile_phone": "1234567890",
            "organization_id": None,
            "is_active": True,
            "first_name": "Graham",
            "last_name": "Wheating",
        },
        {
            "user_profile_id": 32,
            "keycloak_email": "Haris.Ishaq@gov.bc.ca",
            "keycloak_username": "HISHAQ",
            "email": "Haris.Ishaq@gov.bc.ca",
            "title": "Test User",
            "phone": "1234567890",
            "mobile_phone": "1234567890",
            "organization_id": None,
            "is_active": True,
            "first_name": "Haris",
            "last_name": "Ishaq",
        },
        {
            "user_profile_id": 33,
            "keycloak_email": "Harpaul.Padda@gov.bc.ca",
            "keycloak_username": "HPADDA",
            "email": "Harpaul.Padda@gov.bc.ca",
            "title": "Test User",
            "phone": "1234567890",
            "mobile_phone": "1234567890",
            "organization_id": None,
            "is_active": True,
            "first_name": "Harpaul",
            "last_name": "Padda",
        },
        {
            "user_profile_id": 34,
            "keycloak_email": "james.thomas@gov.bc.ca",
            "keycloak_username": "JAMTHOMA",
            "email": "james.thomas@gov.bc.ca",
            "title": "Test User",
            "phone": "1234567890",
            "mobile_phone": "1234567890",
            "organization_id": None,
            "is_active": True,
            "first_name": "James",
            "last_name": "Thomas",
        },
        {
            "user_profile_id": 35,
            "keycloak_email": "Jennifer.Kroll@gov.bc.ca",
            "keycloak_username": "Jskroll",
            "email": "Jennifer.Kroll@gov.bc.ca",
            "title": "Test User",
            "phone": "1234567890",
            "mobile_phone": "1234567890",
            "organization_id": None,
            "is_active": True,
            "first_name": "Jennifer",
            "last_name": "Kroll",
        },
        {
            "user_profile_id": 36,
            "keycloak_email": "Joel.Zushman@gov.bc.ca",
            "keycloak_username": "Jzushman",
            "email": "Joel.Zushman@gov.bc.ca",
            "title": "Test User",
            "phone": "1234567890",
            "mobile_phone": "1234567890",
            "organization_id": None,
            "is_active": True,
            "first_name": "Joel",
            "last_name": "Zushman",
        },
        {
            "user_profile_id": 37,
            "keycloak_email": "kenneth.chan@gov.bc.ca",
            "keycloak_username": "KENCHAN",
            "email": "kenneth.chan@gov.bc.ca",
            "title": "Test User",
            "phone": "1234567890",
            "mobile_phone": "1234567890",
            "organization_id": None,
            "is_active": True,
            "first_name": "Kenneth",
            "last_name": "Chan",
        },
        {
            "user_profile_id": 38,
            "keycloak_email": "Mahon.Lamont@gov.bc.ca",
            "keycloak_username": "MLAMONT",
            "email": "Mahon.Lamont@gov.bc.ca",
            "title": "Test User",
            "phone": "1234567890",
            "mobile_phone": "1234567890",
            "organization_id": None,
            "is_active": True,
            "first_name": "Mahon",
            "last_name": "Lamont",
        },
        {
            "user_profile_id": 39,
            "keycloak_email": "molly.hackett@gov.bc.ca",
            "keycloak_username": "MHACKETT",
            "email": "molly.hackett@gov.bc.ca",
            "title": "Test User",
            "phone": "1234567890",
            "mobile_phone": "1234567890",
            "organization_id": None,
            "is_active": True,
            "first_name": "Molly",
            "last_name": "Hackett",
        },
        {
            "user_profile_id": 40,
            "keycloak_email": "nicole.anderson@gov.bc.ca",
            "keycloak_username": "Nkanders",
            "email": "nicole.anderson@gov.bc.ca",
            "title": "Test User",
            "phone": "1234567890",
            "mobile_phone": "1234567890",
            "organization_id": None,
            "is_active": True,
            "first_name": "Nicole",
            "last_name": "Anderson",
        },
        {
            "user_profile_id": 41,
            "keycloak_email": "Oloruntobi.Muniru@gov.bc.ca",
            "keycloak_username": "Omuniru",
            "email": "Oloruntobi.Muniru@gov.bc.ca",
            "title": "Test User",
            "phone": "1234567890",
            "mobile_phone": "1234567890",
            "organization_id": None,
            "is_active": True,
            "first_name": "Oloruntobi",
            "last_name": "Muniru",
        },
        {
            "user_profile_id": 42,
            "keycloak_email": "quentin.mowat-amiet@gov.bc.ca",
            "keycloak_username": "QMOWATAM",
            "email": "quentin.mowat-amiet@gov.bc.ca",
            "title": "Test User",
            "phone": "1234567890",
            "mobile_phone": "1234567890",
            "organization_id": None,
            "is_active": True,
            "first_name": "Quentin",
            "last_name": "Mowat-Amiet",
        },
        {
            "user_profile_id": 43,
            "keycloak_email": "suraj.chopra@gov.bc.ca",
            "keycloak_username": "SCHOPRA",
            "email": "suraj.chopra@gov.bc.ca",
            "title": "Test User",
            "phone": "1234567890",
            "mobile_phone": "1234567890",
            "organization_id": None,
            "is_active": True,
            "first_name": "Raj",
            "last_name": "Chopra",
        },
        {
            "user_profile_id": 44,
            "keycloak_email": "Samantha.Horan@gov.bc.ca",
            "keycloak_username": "Shoran",
            "email": "Samantha.Horan@gov.bc.ca",
            "title": "Test User",
            "phone": "1234567890",
            "mobile_phone": "1234567890",
            "organization_id": None,
            "is_active": True,
            "first_name": "Samantha",
            "last_name": "Horan",
        },
        {
            "user_profile_id": 45,
            "keycloak_email": "samuel.leroux@gov.bc.ca",
            "keycloak_username": "SLEROUX",
            "email": "samuel.leroux@gov.bc.ca",
            "title": "Test User",
            "phone": "1234567890",
            "mobile_phone": "1234567890",
            "organization_id": None,
            "is_active": True,
            "first_name": "Samuel",
            "last_name": "LeRoux",
        },
        {
            "user_profile_id": 46,
            "keycloak_email": "sarah.anderson@gov.bc.ca",
            "keycloak_username": "SMAnders",
            "email": "sarah.anderson@gov.bc.ca",
            "title": "Test User",
            "phone": "1234567890",
            "mobile_phone": "1234567890",
            "organization_id": None,
            "is_active": True,
            "first_name": "Sarah",
            "last_name": "Anderson",
        },
        {
            "user_profile_id": 47,
            "keycloak_email": "shamas.uideen@gov.bc.ca",
            "keycloak_username": "SUIDEEN",
            "email": "shamas.uideen@gov.bc.ca",
            "title": "Test User",
            "phone": "1234567890",
            "mobile_phone": "1234567890",
            "organization_id": None,
            "is_active": True,
            "first_name": "Shamas",
            "last_name": "UI Deen",
        },
        {
            "user_profile_id": 48,
            "keycloak_email": "shannon.payne@gov.bc.ca",
            "keycloak_username": "Shpayne",
            "email": "shannon.payne@gov.bc.ca",
            "title": "Test User",
            "phone": "1234567890",
            "mobile_phone": "1234567890",
            "organization_id": None,
            "is_active": True,
            "first_name": "Shannon",
            "last_name": "Payne",
        },
        {
            "user_profile_id": 49,
            "keycloak_email": "shelby.fondrick@gov.bc.ca",
            "keycloak_username": "SFONDRIC",
            "email": "shelby.fondrick@gov.bc.ca",
            "title": "Test User",
            "phone": "1234567890",
            "mobile_phone": "1234567890",
            "organization_id": None,
            "is_active": True,
            "first_name": "Shelby",
            "last_name": "Fondrick",
        },
        {
            "user_profile_id": 50,
            "keycloak_email": "Steven.SE.Lee@gov.bc.ca",
            "keycloak_username": "Sselee",
            "email": "Steven.SE.Lee@gov.bc.ca",
            "title": "Test User",
            "phone": "1234567890",
            "mobile_phone": "1234567890",
            "organization_id": None,
            "is_active": True,
            "first_name": "Steven",
            "last_name": "SE Lee",
        },
        {
            "user_profile_id": 51,
            "keycloak_email": "Tapiwa.Nyabadza@gov.bc.ca",
            "keycloak_username": "TNYABADZ",
            "email": "Tapiwa.Nyabadza@gov.bc.ca",
            "title": "Test User",
            "phone": "1234567890",
            "mobile_phone": "1234567890",
            "organization_id": None,
            "is_active": True,
            "first_name": "Tapiwa",
            "last_name": "Nyabadza",
        },
        {
            "user_profile_id": 52,
            "keycloak_email": "tristen.mccartney@gov.bc.ca",
            "keycloak_username": "TMCCARTN",
            "email": "tristen.mccartney@gov.bc.ca",
            "title": "Test User",
            "phone": "1234567890",
            "mobile_phone": "1234567890",
            "organization_id": None,
            "is_active": True,
            "first_name": "Tristen",
            "last_name": "McCartney",
        },
        {
            "user_profile_id": 53,
            "keycloak_email": "victoria.gagnon@gov.bc.ca",
            "keycloak_username": "Vgagnon",
            "email": "victoria.gagnon@gov.bc.ca",
            "title": "Test User",
            "phone": "1234567890",
            "mobile_phone": "1234567890",
            "organization_id": None,
            "is_active": True,
            "first_name": "Victoria",
            "last_name": "Gagnon",
        },
        {
            "user_profile_id": 54,
            "keycloak_email": "wesley.hawley@gov.bc.ca",
            "keycloak_username": "WHAWLEY",
            "email": "wesley.hawley@gov.bc.ca",
            "title": "Test User",
            "phone": "1234567890",
            "mobile_phone": "1234567890",
            "organization_id": None,
            "is_active": True,
            "first_name": "Wesley",
            "last_name": "Hawley",
        },
        # Government users (55-82)
        {
            "user_profile_id": 55,
            "keycloak_email": "alex.zorkin@gov.bc.ca",
            "keycloak_username": "ALZORKIN",
            "email": "alex.zorkin@gov.bc.ca",
            "title": "Lead Developer",
            "phone": "1234567890",
            "mobile_phone": "1234567890",
            "organization_id": None,
            "is_active": True,
            "first_name": "Alex",
            "last_name": "Zorkin",
        },
        {
            "user_profile_id": 56,
            "keycloak_email": "cindy.sonne@gov.bc.ca",
            "keycloak_username": "CISONNE",
            "email": "cindy.sonne@gov.bc.ca",
            "title": "",
            "phone": "",
            "mobile_phone": "",
            "organization_id": None,
            "is_active": True,
            "first_name": "Cindy",
            "last_name": "Sonne",
        },
        {
            "user_profile_id": 57,
            "keycloak_email": "jasmine.zhang@gov.bc.ca",
            "keycloak_username": "JASZHANG",
            "email": "jasmine.zhang@gov.bc.ca",
            "title": "",
            "phone": "",
            "mobile_phone": "",
            "organization_id": None,
            "is_active": True,
            "first_name": "Jasmine",
            "last_name": "Zhang",
        },
        {
            "user_profile_id": 58,
            "keycloak_email": "kuan.fan@gov.bc.ca",
            "keycloak_username": "kfan",
            "email": "Kuan.Fan@gov.bc.ca",
            "title": "",
            "phone": "",
            "mobile_phone": "",
            "organization_id": None,
            "is_active": True,
            "first_name": "Kuan",
            "last_name": "Fan",
        },
        {
            "user_profile_id": 59,
            "keycloak_email": "Sean.LeRoy@gov.bc.ca",
            "keycloak_username": "seleroy",
            "email": "Sean.LeRoy@gov.bc.ca",
            "title": "",
            "phone": "",
            "mobile_phone": "",
            "organization_id": None,
            "is_active": True,
            "first_name": "Sean",
            "last_name": "LeRoy",
        },
        {
            "user_profile_id": 60,
            "keycloak_email": "alisa.holtz@gov.bc.ca",
            "keycloak_username": "AHOLTZ",
            "email": "Alisa.Holtz@gov.bc.ca",
            "title": "",
            "phone": "",
            "mobile_phone": "",
            "organization_id": None,
            "is_active": True,
            "first_name": "Alisa",
            "last_name": "Holtz",
        },
        {
            "user_profile_id": 61,
            "keycloak_email": "Amy.C.Teucher@gov.bc.ca",
            "keycloak_username": "acteuche",
            "email": "Amy.C.Teucher@gov.bc.ca",
            "title": "",
            "phone": "",
            "mobile_phone": "",
            "organization_id": None,
            "is_active": True,
            "first_name": "Amy",
            "last_name": "Teucher",
        },
        {
            "user_profile_id": 62,
            "keycloak_email": "Anna.Ringsred@gov.bc.ca",
            "keycloak_username": "ARINGSRE",
            "email": "Anna.Ringsred@gov.bc.ca",
            "title": "",
            "phone": "",
            "mobile_phone": "",
            "organization_id": None,
            "is_active": True,
            "first_name": "Anna",
            "last_name": "Ringsred",
        },
        {
            "user_profile_id": 63,
            "keycloak_email": "Caitlin.Moran@gov.bc.ca",
            "keycloak_username": "cmoran",
            "email": "Caitlin.Moran@gov.bc.ca",
            "title": "",
            "phone": "",
            "mobile_phone": "",
            "organization_id": None,
            "is_active": True,
            "first_name": "Caitlin",
            "last_name": "Moran",
        },
        {
            "user_profile_id": 64,
            "keycloak_email": "victor.rizov@gov.bc.ca",
            "keycloak_username": "VRIZOV",
            "email": "victor.rizov@gov.bc.ca",
            "title": "",
            "phone": "",
            "mobile_phone": "",
            "organization_id": None,
            "is_active": True,
            "first_name": "Victor",
            "last_name": "Rizov",
        },
        {
            "user_profile_id": 65,
            "keycloak_email": "cindy.sonne@gov.bc.ca",
            "keycloak_username": "CINSONNE",
            "email": "cindy.sonne@gov.bc.ca",
            "title": "",
            "phone": "",
            "mobile_phone": "",
            "organization_id": None,
            "is_active": True,
            "first_name": "Cindy",
            "last_name": "Sonne",
        },
        {
            "user_profile_id": 66,
            "keycloak_email": "debbie.oyebanji@gov.bc.ca",
            "keycloak_username": "DOYEBANJ",
            "email": "debbie.oyebanji@gov.bc.ca",
            "title": "",
            "phone": "",
            "mobile_phone": "",
            "organization_id": None,
            "is_active": True,
            "first_name": "Debbie",
            "last_name": "Oyebanji",
        },
        {
            "user_profile_id": 67,
            "keycloak_email": "Devon.Willey-Pichette@gov.bc.ca",
            "keycloak_username": "DWILLEYP",
            "email": "Devon.Willey-Pichette@gov.bc.ca",
            "title": "",
            "phone": "",
            "mobile_phone": "",
            "organization_id": None,
            "is_active": True,
            "first_name": "Devon",
            "last_name": "Willey-Pichette",
        },
        {
            "user_profile_id": 68,
            "keycloak_email": "Richard.Tan@gov.bc.ca",
            "keycloak_username": "FIXME1",
            "email": "Richard.Tan@gov.bc.ca",
            "title": "",
            "phone": "",
            "mobile_phone": "",
            "organization_id": None,
            "is_active": True,
            "first_name": "Richard",
            "last_name": "Tan",
        },
        {
            "user_profile_id": 69,
            "keycloak_email": "Michael.Rensing@gov.bc.ca",
            "keycloak_username": "FIXME2",
            "email": "Michael.Rensing@gov.bc.ca",
            "title": "",
            "phone": "",
            "mobile_phone": "",
            "organization_id": None,
            "is_active": True,
            "first_name": "Michael",
            "last_name": "Rensing",
        },
        {
            "user_profile_id": 70,
            "keycloak_email": "Dan.Green@gov.bc.ca",
            "keycloak_username": "FIXME5",
            "email": "Dan.Green@gov.bc.ca",
            "title": "",
            "phone": "",
            "mobile_phone": "",
            "organization_id": None,
            "is_active": True,
            "first_name": "Daniel",
            "last_name": "Green",
        },
        {
            "user_profile_id": 71,
            "keycloak_email": "jasmin.gabriel@gov.bc.ca",
            "keycloak_username": "JGABRIEL",
            "email": "jasmin.gabriel@gov.bc.ca",
            "title": "",
            "phone": "",
            "mobile_phone": "",
            "organization_id": None,
            "is_active": True,
            "first_name": "Jasmin",
            "last_name": "Gabriel",
        },
        {
            "user_profile_id": 72,
            "keycloak_email": "jordan.kummerfield@gov.bc.ca",
            "keycloak_username": "JKUMMERF",
            "email": "Jordan.Kummerfield@gov.bc.ca",
            "title": "",
            "phone": "",
            "mobile_phone": "",
            "organization_id": None,
            "is_active": True,
            "first_name": "Jordan",
            "last_name": "Kummerfield",
        },
        {
            "user_profile_id": 73,
            "keycloak_email": "mehdi.bagheri@gov.bc.ca",
            "keycloak_username": "MEBAGHER",
            "email": "mehdi.bagheri@gov.bc.ca",
            "title": "",
            "phone": "",
            "mobile_phone": "",
            "organization_id": None,
            "is_active": True,
            "first_name": "Mehdi",
            "last_name": "Bagheri",
        },
        {
            "user_profile_id": 74,
            "keycloak_email": "Magdalena.Gronowska@gov.bc.ca",
            "keycloak_username": "mgronows",
            "email": "Magdalena.Gronowska@gov.bc.ca",
            "title": "",
            "phone": "",
            "mobile_phone": "",
            "organization_id": None,
            "is_active": True,
            "first_name": "Magdalena",
            "last_name": "Gronowska",
        },
        {
            "user_profile_id": 75,
            "keycloak_email": "nick.clark@gov.bc.ca",
            "keycloak_username": "nclark",
            "email": "nick.clark@gov.bc.ca",
            "title": "",
            "phone": "",
            "mobile_phone": "",
            "organization_id": None,
            "is_active": True,
            "first_name": "Nick",
            "last_name": "Clark",
        },
        {
            "user_profile_id": 76,
            "keycloak_email": "pravallikha.samuthirarajan@gov.bc.ca",
            "keycloak_username": "PSAMUTHI",
            "email": "pravallikha.samuthirarajan@gov.bc.ca",
            "title": "",
            "phone": "",
            "mobile_phone": "",
            "organization_id": None,
            "is_active": True,
            "first_name": "Pravallikha",
            "last_name": "Samuthirarajan",
        },
        {
            "user_profile_id": 77,
            "keycloak_email": "Ryan.Foxall@gov.bc.ca",
            "keycloak_username": "rfoxall",
            "email": "Ryan.Foxall@gov.bc.ca",
            "title": "",
            "phone": "",
            "mobile_phone": "",
            "organization_id": None,
            "is_active": True,
            "first_name": "Ryan",
            "last_name": "Foxall",
        },
        {
            "user_profile_id": 78,
            "keycloak_email": "sunny.singh@gov.bc.ca",
            "keycloak_username": "SUNSINGH",
            "email": "sunny.singh@gov.bc.ca",
            "title": "",
            "phone": "",
            "mobile_phone": "",
            "organization_id": None,
            "is_active": True,
            "first_name": "Sunny",
            "last_name": "Singh",
        },
        {
            "user_profile_id": 79,
            "keycloak_email": "Taylor.Lorenzen@gov.bc.ca",
            "keycloak_username": "tlorenze",
            "email": "Taylor.Lorenzen@gov.bc.ca",
            "title": "",
            "phone": "",
            "mobile_phone": "",
            "organization_id": None,
            "is_active": True,
            "first_name": "Taylor",
            "last_name": "Lorenzen",
        },
        {
            "user_profile_id": 80,
            "keycloak_email": "Taylor.Reiger@gov.bc.ca",
            "keycloak_username": "trieger",
            "email": "Taylor.Reiger@gov.bc.ca",
            "title": "",
            "phone": "",
            "mobile_phone": "",
            "organization_id": None,
            "is_active": True,
            "first_name": "Taylor",
            "last_name": "Reiger",
        },
        {
            "user_profile_id": 81,
            "keycloak_email": "veronika.fremlin@gov.bc.ca",
            "keycloak_username": "vfremlin",
            "email": "veronika.fremlin@gov.bc.ca",
            "title": "",
            "phone": "",
            "mobile_phone": "",
            "organization_id": None,
            "is_active": True,
            "first_name": "Veronika",
            "last_name": "Fremlin",
        },
    ]

    for user_profile_data in user_profiles_to_seed:
        # Check if the user profile already exists by keycloak_username or user_profile_id
        existing_user_profile = await session.execute(
            select(UserProfile).where(
                (
                    UserProfile.keycloak_username
                    == user_profile_data["keycloak_username"]
                )
                | (UserProfile.user_profile_id == user_profile_data["user_profile_id"])
            )
        )
        if existing_user_profile.scalar():
            logger.info(
                f"User profile with username/id {user_profile_data['keycloak_username']}/{user_profile_data['user_profile_id']} already exists, skipping."
            )
            continue

        user_profile = UserProfile(**user_profile_data)
        session.add(user_profile)

    await session.flush()
    logger.info(f"Seeded {len(user_profiles_to_seed)} user profiles.")
