services:
  nifi:
    image: apache/nifi:latest
    container_name: nifi
    ports:
      - "8080:8080"
    environment:
      - NIFI_WEB_HTTP_PORT=8080
    restart: unless-stopped
    depends_on:
      - tfrs
    volumes:
      - ./jdbc_drivers/postgresql-42.7.3.jar:/opt/nifi/nifi-current/lib/postgresql-42.7.3.jar
      - ./nifi_output:/nifi-output
      - ./nifi_scripts:/nifi-scripts

  tfrs:
    image: postgres:14.2
    container_name: tfrs
    environment:
      POSTGRES_USER: tfrs
      POSTGRES_PASSWORD: development_only
      POSTGRES_DB: tfrs
    ports:
      - "5435:5432"
    volumes:
      - tfrs_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  tfrs_data:
  nifi_output:
  nifi_scripts:
