import structlog
from sqlalchemy import select
from lcfs.db.models.user.UserProfile import UserProfile

logger = structlog.get_logger(__name__)


async def seed_user_profiles(session):
    """
    Seeds the user profiles into the database, if they do not already exist.

    Args:
        session: The database session for committing the new records.
    """

    # Define the user profiles to seed
    user_profiles_to_seed = [
        {
            "user_profile_id": 1,
            "keycloak_email": "alex.zorkin@gov.bc.ca",
            "keycloak_username": "ALZORKIN",
            "email": "alex.zorkin@gov.bc.ca",
            "title": "Developer",
            "phone": "1234567890",
            "mobile_phone": "1234567890",
            "organization_id": None,
            "is_active": True,
            "first_name": "Alex",
            "last_name": "Zorkin",
        },
        {
            "user_profile_id": 2,
            "keycloak_email": "hamed.valiollahibayeki@gov.bc.ca",
            "keycloak_username": "HVALIOLL",
            "email": "hamed.valiollahibayeki@gov.bc.ca",
            "title": "Developer",
            "phone": "1234567890",
            "mobile_phone": "1234567890",
            "organization_id": None,
            "is_active": True,
            "first_name": "Hamed",
            "last_name": "Bayeki",
        },
        {
            "user_profile_id": 3,
            "keycloak_email": "kevin.hashimoto@gov.bc.ca",
            "keycloak_username": "KHASHIMO",
            "email": "kevin.hashimoto@gov.bc.ca",
            "title": "Developer",
            "phone": "1234567890",
            "mobile_phone": "1234567890",
            "organization_id": None,
            "is_active": True,
            "first_name": "Kevin",
            "last_name": "Hashimoto",
        },
        {
            "user_profile_id": 4,
            "keycloak_email": "prashanth.venkateshappa@gov.bc.ca",
            "keycloak_username": "PVENKATE",
            "email": "prashanth.venkateshappa@gov.bc.ca",
            "title": "Developer",
            "phone": "1234567890",
            "mobile_phone": "1234567890",
            "organization_id": None,
            "is_active": True,
            "first_name": "Prashanth",
            "last_name": "V",
        },
        {
            "user_profile_id": 5,
            "keycloak_email": "justin.lepitzki@gov.bc.ca",
            "keycloak_username": "JLEPITZ",
            "email": "justin.lepitzki@gov.bc.ca",
            "title": "Admin",
            "phone": "1234567890",
            "mobile_phone": "1234567890",
            "organization_id": None,
            "is_active": True,
            "first_name": "Justin",
            "last_name": "Lepitzki",
        },
        {
            "user_profile_id": 6,
            "keycloak_email": "lindsy.grunert@gov.bc.ca",
            "keycloak_username": "LGRUNERT",
            "email": "lindsy.grunert@gov.bc.ca",
            "title": "Admin",
            "phone": "1234567890",
            "mobile_phone": "1234567890",
            "organization_id": None,
            "is_active": True,
            "first_name": "Lindsy",
            "last_name": "Grunert",
        },
        {
            "user_profile_id": 7,
            "keycloak_email": "tfrs@gov.bc.ca",
            "keycloak_username": "lcfs1",
            "email": "tfrs@gov.bc.ca",
            "title": "Analyst",
            "phone": "1112223333",
            "mobile_phone": "1112223333",
            "organization_id": 1,
            "is_active": True,
            "first_name": "Jane",
            "last_name": "Doe",
        },
        {
            "user_profile_id": 8,
            "keycloak_email": "tfrs@gov.bc.ca",
            "keycloak_username": "LCFS2",
            "email": "tfrs@gov.bc.ca",
            "title": "Analyst",
            "phone": "2223334444",
            "mobile_phone": "2223334444",
            "organization_id": 2,
            "is_active": True,
            "first_name": "John",
            "last_name": "Smith",
        },
        {
            "user_profile_id": 9,
            "keycloak_email": "tfrs@gov.bc.ca",
            "keycloak_username": "LCFS3",
            "email": "tfrs@gov.bc.ca",
            "title": "Analyst",
            "phone": "3334445555",
            "mobile_phone": "3334445555",
            "organization_id": 3,
            "is_active": True,
            "first_name": "Alice",
            "last_name": "Woo",
        },
        {
            "user_profile_id": 10,
            "keycloak_email": "tfrs@gov.bc.ca",
            "keycloak_username": "LCFS4",
            "email": "tfrs@gov.bc.ca",
            "title": "Analyst",
            "phone": "4445556666",
            "mobile_phone": "4445556666",
            "organization_id": 4,
            "is_active": True,
            "first_name": "Bob",
            "last_name": "Lee",
        },
        {
            "user_profile_id": 11,
            "keycloak_email": "tfrs@gov.bc.ca",
            "keycloak_username": "LCFS5",
            "email": "tfrs@gov.bc.ca",
            "title": "Analyst",
            "phone": "6667778888",
            "mobile_phone": "6667778888",
            "organization_id": 5,
            "is_active": True,
            "first_name": "David",
            "last_name": "Clark",
        },
        {
            "user_profile_id": 12,
            "keycloak_email": "tfrs@gov.bc.ca",
            "keycloak_username": "LCFS6",
            "email": "tfrs@gov.bc.ca",
            "title": "Analyst",
            "phone": "8889990000",
            "mobile_phone": "8889990000",
            "organization_id": 6,
            "is_active": True,
            "first_name": "Frank",
            "last_name": "Wilson",
        },
        {
            "user_profile_id": 13,
            "keycloak_email": "tfrs@gov.bc.ca",
            "keycloak_username": "LCFS7",
            "email": "tfrs@gov.bc.ca",
            "title": "Analyst",
            "phone": "0001112222",
            "mobile_phone": "0001112222",
            "organization_id": 7,
            "is_active": True,
            "first_name": "Bill",
            "last_name": "Teller",
        },
        {
            "user_profile_id": 14,
            "keycloak_email": "tfrs@gov.bc.ca",
            "keycloak_username": "LCFS8",
            "email": "tfrs@gov.bc.ca",
            "title": "Analyst",
            "phone": "2223334445",
            "mobile_phone": "2223334445",
            "organization_id": 8,
            "is_active": True,
            "first_name": "James",
            "last_name": "Bell",
        },
        {
            "user_profile_id": 15,
            "keycloak_email": "tfrs@gov.bc.ca",
            "keycloak_username": "LCFS9",
            "email": "tfrs@gov.bc.ca",
            "title": "Analyst",
            "phone": "4445556667",
            "mobile_phone": "4445556667",
            "organization_id": 9,
            "is_active": True,
            "first_name": "Leo",
            "last_name": "Martin",
        },
        {
            "user_profile_id": 16,
            "keycloak_email": "tfrs@gov.bc.ca",
            "keycloak_username": "LCFS10",
            "email": "tfrs@gov.bc.ca",
            "title": "Analyst",
            "phone": "6667778889",
            "mobile_phone": "6667778889",
            "organization_id": 10,
            "is_active": True,
            "first_name": "Noah",
            "last_name": "Thomas",
        },
        {
            "user_profile_id": 17,
            "keycloak_email": "kailee.douglas@gov.bc.ca",
            "keycloak_username": "KADOUGLA",
            "email": "kailee.douglas@gov.bc.ca",
            "title": "Admin",
            "phone": "1234567890",
            "mobile_phone": "1234567890",
            "organization_id": None,
            "is_active": True,
            "first_name": "Kailee",
            "last_name": "Douglas",
        },
        {
            "user_profile_id": 18,
            "keycloak_email": "alasdair.ring@gov.bc.ca",
            "keycloak_username": "AIRING",
            "email": "alasdair.ring@gov.bc.ca",
            "title": "Product Owner",
            "phone": "1234567890",
            "mobile_phone": "1234567890",
            "organization_id": None,
            "is_active": True,
            "first_name": "Al",
            "last_name": "Ring",
        },
        {
            "user_profile_id": 19,
            "keycloak_email": "rebekah.ford@gov.bc.ca",
            "keycloak_username": "RRFORD",
            "email": "rebekah.ford@gov.bc.ca",
            "title": "Scrum Master",
            "phone": "1234567890",
            "mobile_phone": "1234567890",
            "organization_id": None,
            "is_active": True,
            "first_name": "Rebekah",
            "last_name": "Ford",
        },
        {
            "user_profile_id": 20,
            "keycloak_email": "stuart.galloway@gov.bc.ca",
            "keycloak_username": "SGALLOWA",
            "email": "stuart.galloway@gov.bc.ca",
            "title": "UX Practicioner",
            "phone": "1234567890",
            "mobile_phone": "1234567890",
            "organization_id": None,
            "is_active": True,
            "first_name": "Stuart",
            "last_name": "Galloway",
        },
        {
            "user_profile_id": 21,
            "keycloak_email": "lcfstest@gov.bc.ca",
            "keycloak_username": "lcfstest",
            "email": "lcfstest@gov.bc.ca",
            "title": "Test Account",
            "phone": "1234567890",
            "mobile_phone": "1234567890",
            "organization_id": None,
            "is_active": True,
            "first_name": "LCFS_IDIR",
            "last_name": "TESTER",
        },
    ]

    try:
        for user_data in user_profiles_to_seed:
            # Check if the user already exists based on a unique attribute
            exists = await session.execute(
                select(UserProfile).where(
                    UserProfile.keycloak_username == user_data["keycloak_username"]
                )
            )
            if not exists.scalars().first():
                user_profile = UserProfile(**user_data)
                session.add(user_profile)

    except Exception as e:
        context = {
            "function": "seed_user_profiles",
        }
        logger.error(
            "Error occurred while seeding user profiles",
            error=str(e),
            exc_info=e,
            **context,
        )
        raise
