name: Auto Versioning

on:
  push:
    branches:
      - auto-versioning
  workflow_dispatch:

jobs:
  versioning:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@v3.1.11
        with:
          versionSpec: "6.0.x"

      - name: Determine Version
        id: version_step # step id used as reference for output values
        uses: gittools/actions/gitversion/execute@v3.1.11
        with:
          useConfigFile: true

      - run: |
          echo "FullSemVer (env.fullSemVer)            : ${{ env.fullSemVer }}"
        name: Display GitVersion variables (without prefix)

      - name: Update package.json Version
        run: |
          # Print GitVersion output for debugging
          echo "GitVersion JSON output: ${{ steps.version_step.outputs.output }}"
          # Extract SemVer from GitVersion JSON output
          VERSION=$(echo '${{ steps.version_step.outputs.output }}' | jq -r '.SemVer')
          echo "Updating package.json version to: $VERSION"
          # # Use Node.js to update the version field in package.json
          # node -e "let pkg = require('./package.json'); pkg.version = '$VERSION'; require('fs').writeFileSync('package.json', JSON.stringify(pkg, null, 2));"
