name: Auto Versioning

on:
  push:
    branches:
      - auto-versioning
  workflow_dispatch:

jobs:
  versioning:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Fetch All History
        run: git fetch --unshallow

      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@v4
        with:
          versionSpec: '6.0.x'

      - name: Determine Version
        id: version_step # step id used as reference for output values
        uses: gittools/actions/gitversion/execute@v4
        with:
          useConfigFile: true
