name: Backend Auto Test

on: 
  pull_request:
    types: [opened, edited, synchronize]
    branches: 
      - "feat/prashanth-ci-cd-test-pipeline-619"
    paths: 
      - "backend"
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:latest
        ports:
          - 5432:5432
        env:
          POSTGRES_DB: lcfs
          POSTGRES_USER: test_user
          POSTGRES_PASSWORD: test_password
        options: >-
          --health-cmd="pg_isready -U test_user -d lcfs"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:

      - name: Checkout Target Branch
        uses: actions/checkout@v4.1.6

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pwd
          cd backend
          poetry install

      - name: Wait for PostgreSQL to be ready
        run: |
          while ! pg_isready -h 127.0.0.1 -U test_user -d lcfs; do
            echo "Waiting for PostgreSQL to be ready..."
            sleep 1
          done

      - name: Run Backend Tests
        env:
          DATABASE_URL: postgresql://test_user:test_password@127.0.0.1:5432/lcfs
        run: |
          pwd
          cd backend
          poetry run pytest -s -v