name: Backend Test

on: 
  pull_request:
    types: [opened, edited, synchronize]
    branches: 
      - "feat/prashanth-ci-cd-test-pipeline-619"
    # paths: 
    #   - "backend"
  workflow_dispatch:

jobs:

  backend-test:
    
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:latest
        ports:
          - 5432:5432
        env:
          POSTGRES_DB: lcfs_test
          POSTGRES_USER: lcfs
          POSTGRES_PASSWORD: development_only
        options: >-
          --health-cmd="pg_isready -U lcfs -d lcfs_test"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

      redis:
        # Docker Hub image
        image: redis:latest
        ports: 
          - 6379:6379
        # Set health checks to wait until redis has started
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    env:
      REDIS_HOST: localhost
      REDIS_PORT: 6379
      REDIS_DB: lcfs
      REDIS_PASS: development_only       

    steps:

      - name: Checkout Target Branch
        uses: actions/checkout@v4.1.6

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pwd
          cd backend
          pip install poetry
          poetry install

      - name: Wait for PostgreSQL to be ready
        run: |
          while ! pg_isready -h 127.0.0.1 -U lcfs -d lcfs_test; do
            echo "Waiting for PostgreSQL to be ready..."
            sleep 1
          done

      - name: Run Backend Tests
        run: |
          pwd
          cd backend
          poetry run pytest -s -v