name: Devops Test

on:
  push:
    branches: [ devops-test-pipeline-0.2.0 ]
  workflow_dispatch:

jobs:

  devops-test:

    name: Devops test
    runs-on: ubuntu-latest

    steps:
      
      - name: print default branch name
        run: |
          echo "The default branch is ${{ github.event.repository.default_branch }}"