name: Label Triggered Build

on:
  pull_request:
    types: [labeled]

jobs:
  build:
    if: contains(github.event.pull_request.labels.*.name, 'build')
    runs-on: ubuntu-latest

    steps:

      - name: Run build
        run: echo "well done for pr build ..."

