
name: LCFS 0.2.0 Prod CI

on:
  workflow_dispatch:

env:
  GIT_URL: https://github.com/bcgov/lcfs.git 
  TEST_NAMESPACE: ${{ secrets.OPENSHIFT_NAMESPACE_PLATE }}-test
  PROD_NAMESPACE: ${{ secrets.OPENSHIFT_NAMESPACE_PLATE }}-prod

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:

  # Read the image tag from test environment
  get-image-tag:

    name: Read release number from Test environment
    runs-on: ubuntu-latest
  
    outputs:
      output1: ${{ steps.set-pre-release.outputs.PRE_RELEASE }}

    steps:

      # to do: verify the frontend image tag is same as the backend image tag
      - name: Get the image tag from values-test.yaml
        id: get-image-tag
        uses: mikefarah/yq@v4.40.5
        with:
            cmd: |
              imagetag=$(yq eval '.image.tag' lcfs/charts/lcfs-frontend/values-test.yaml)
              echo $imagetag >> $GITHUB_OUTPUT

  # Deplog the image which is running on test to prod
  deploy-on-prod:

    name: Deploy LCFS on Prod
    runs-on: ubuntu-latest
    needs: get-image-tag
    timeout-minutes: 60

    env:
      IMAGE_TAG: ${{ needs.get-image-tag.outputs.output1 }}

    steps:

      - name: Checkout Manifest repository
        uses: actions/checkout@v3
        with:
          repository: bcgov-c/tenant-gitops-d2bd59
          ref: main
          ssh-key: ${{ secrets.MANIFEST_REPO_DEPLOY_KEY }}

      - name: Ask for approval for LCFS ${{env.IMAGE_TAG }} Prod deployment
        uses: trstringer/manual-approval@v1.6.0
        with:
          secret: ${{ github.TOKEN }}
          approvers: AlexZorkin,kuanfandevops,hamed-valiollahi,airinggov,areyeslo,dhaselhan,Grulin,justin-lepitzki,kevin-hashimoto
          minimum-approvals: 2
          issue-title: "LCFS ${{env.IMAGE_TAG }} Prod Deployment"

      - name: Tag LCFS images from Test to Prod
        run: |
          oc tag ${{ env.TEST_NAMESPACE }}/lcfs-backend:${{env.IMAGE_TAG }} ${{ env.PROD_NAMESPACE }}/lcfs-backend:${{env.IMAGE_TAG }}
          oc tag ${{ env.TEST_NAMESPACE }}/lcfs-frontend:${{env.IMAGE_TAG }} ${{ env.PROD_NAMESPACE }}/lcfs-frontend:${{env.IMAGE_TAG }}

      - name: Update frontend tag for prod deployment
        uses: mikefarah/yq@v4.40.5
        with:
            cmd: yq -i '.image.tag = "${{env.IMAGE_TAG }}"' lcfs/charts/lcfs-frontend/values-prod.yaml
    
      - name: Update backend tag for prod deployment
        uses: mikefarah/yq@v4.40.5
        with:
            cmd: yq -i '.image.tag = "${{env.IMAGE_TAG }}"' lcfs/charts/lcfs-backend/values-prod.yaml

      - name: GitHub Commit & Push
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git add lcfs/charts/lcfs-frontend/values-prod.yaml
          git add lcfs/charts/lcfs-backend/values-prod.yaml
          git commit -m "update the version with pre-release number for prod"
          git push
              