name: Tag Release

on:
  push:
    branches: [tag-release-1.0.0]
  workflow_dispatch:

env:
  GIT_URL: https://github.com/bcgov/lcfs.git

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  tag:
    runs-on: ubuntu-latest
    env:
      IMAGE_TAG: sssss

    steps:
      - name: Check out repository
        uses: actions/checkout@v4.1.1

      - name: GitHub Commit & Push
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git fetch --tags
          git tag -l

      - name: Create GitHub Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Automatically provided by GitHub
        with:
          tag_name: ${{ env.IMAGE_TAG }} # The pushed tag
          release_name: "vv${{ env.IMAGE_TAG }}" # Release title
          body: "This is an automated release 🚀" # Release notes
          draft: false # Set to true if you want a draft release
          prerelease: false
