name: Show Environment Variable

on:
  workflow_dispatch:
    workflow_call:

jobs:
  create-variable:
    runs-on: ubuntu-latest

    steps:
    - name: Set Environment Variable
      id: set-env-variable
      run: echo "envvar=Hello" >> $GITHUB_OUTPUT

  show-variable:
    needs: create-variable
    runs-on: ubuntu-latest

    steps:
    - name: Display Environment Variable
      run: |
        echo "Environment Variable: ${{ jobs.create-variable.steps.set-env-variable.outputs.envvar }}"