export const apiRoutes = {
  exportUsers: '/users/export?format=xls',
  listUsers: '/users/list',
  orgUsers: '/organization/:orgId/users/list',
  transactions: '/transactions/',
  exportTransactions: '/transactions/export',
  filteredTransactionsByOrg: '/transactions/:orgId',
  exportFilteredTransactionsByOrg: '/transactions/:orgId/export',
  orgTransactions: '/organization/transactions',
  exportOrgTransactions: '/organization/transactions/export',
  fuelCodeSearch: '/fuel-codes/search?',
  getComplianceReports: '/reports/list',
  getDocument: '/documents/:parentType/:parentId/:documentId',
  getOrgComplianceReports: '/organization/:orgId/reports/list',
  getAllFinalSupplyEquipments: '/final-supply-equipments/list-all',
  searchFinalSupplyEquipments: '/final-supply-equipments/search?',
  getAllFuelSupplies: '/fuel-supply/list-all',
  getAllAllocationAgreements: '/allocation-agreement/list-all',
  organizationSearch: '/organizations/search?',
  getUserActivities: '/users/:userId/activity',
  getAllUserActivities: '/users/activities/all',
  getFuelTypeOthers: '/fuel-type/others/list',
  getAuditLogs: '/audit-log/list'
}
