export const apiRoutes = {
  currentUser: '/users/current',
  exportUsers: '/users/export?format=xls',
  listUsers: '/users/list',
  roles: '/roles/',
  orgUsers: '/organization/:orgID/users/list',
  transactions: '/transactions/',
  filteredTransactionsByOrg: '/transactions/:orgID',
  orgTransactions: '/organization/transactions',
  adminAdjustments: '/admin-adjustments/',
  initiativeAgreements: '/initiative-agreements/',
  openapi: '/openapi.json/',
  updateCategory: '/transfers/:transferId/category',
  getTransfer: '/transfers/:transferId',
  getFuelCode: '/fuel-codes/:fuelCodeId',
  fuelCodeOptions: '/fuel-codes/table-options',
  addFuelCodes: '/fuel-codes/save-fuel-codes',
  getFuelCodes: '/fuel-codes/list',
  updateFuelCode: '/fuel-codes/:fuelCodeId',
  getCompliancePeriods: '/reports/compliance-periods',
  getComplianceReports: '/reports/list',
  getOrgComplianceReports: '/organization/reports/list',
  createComplianceReport: '/organization/:orgID/reports'
}
